AmberCity_House2_MapScripts::
	.byte 0

AmberCity_House2_EventScript_Woman::
	msgbox AmberCity_House2_Text_SandstormForecast, MSGBOX_NPC
	end

AmberCity_House2_Text_SandstormForecast:
	.string "The weather report said to expect\n"
	.string "sandstorms this week.\p"
	.string "I really wanted to see the\n"
	.string "sand dunes on ROUTE 87.\p"
	.string "But I don't know if a sandstorm\n"
	.string "will blow through.$"
