DunTown_House3_MapScripts::
	.byte 0

DunTown_House3_EventScript_Notebook::
	msgbox DunTown_House3_Text_WeekdaySiblingsLocations, MSGBOX_SIGN
	end

DunTown_House3_Text_WeekdaySiblingsLocations:
	.string "MONTY - MONDAY, SHAMROCK ISLE\n"
	.string "TUCKER - TUESDAY, ROUTE 68\l"
	.string "WENDY - WEDNESDAY, ROUTE 97\l"
	.string "THORA - THURSDAY, AMBER CITY\l"
	.string "FRED - FRIDAY, ROUTE 72\l"
	.string "SADIE - SATURDAY, ROUTE 82\l"
	.string "SONNY - SUNDAY, ROUTE 94$"

