Route92_MapScripts::
	.byte 0

Route92_EventScript_Jo::
	trainerbattle_single TRAINER_JO, Route92_Text_JoIntro, Route92_Text_JoDefeated
	msgbox Route92_Text_JoPostBattle, MSGBOX_AUTOCLOSE
	end

Route92_EventScript_Edd::
	trainerbattle_single TRAINER_EDD, Route92_Text_EddIntro, Route92_Text_EddDefeated
	msgbox Route92_Text_EddPostBattle, MSGBOX_AUTOCLOSE
	end

Route92_EventScript_Burt::
	trainerbattle_single TRAINER_BURT, Route92_Text_BurtIntro, Route92_Text_BurtDefeated
	msgbox Route92_Text_BurtPostBattle, MSGBOX_AUTOCLOSE
	end

Route92_EventScript_Ambrose::
	trainerbattle_single TRAINER_AMBROSE, Route92_Text_AmbroseIntro, Route92_Text_AmbroseDefeated
	msgbox Route92_Text_AmbrosePostBattle, MSGBOX_AUTOCLOSE
	end

Route92_EventScript_Noah::
	trainerbattle_single TRAINER_NOAH, Route92_Text_NoahIntro, Route92_Text_NoahDefeated
	msgbox Route92_Text_NoahPostBattle, MSGBOX_AUTOCLOSE
	end

Route92_EventScript_Yeager::
	trainerbattle_single TRAINER_YEAGER, Route92_Text_YeagerIntro, Route92_Text_YeagerDefeated
	msgbox Route92_Text_YeagerPostBattle, MSGBOX_AUTOCLOSE
	end

Route92_EventScript_Deidre::
	trainerbattle_single TRAINER_DEIDRE, Route92_Text_DeidreIntro, Route92_Text_DeidreDefeated
	msgbox Route92_Text_DeidrePostBattle, MSGBOX_AUTOCLOSE
	end

Route92_EventScript_Yelena::
	trainerbattle_single TRAINER_YELENA, Route92_Text_YelenaIntro, Route92_Text_YelenaDefeated
	msgbox Route92_Text_YelenaPostBattle, MSGBOX_AUTOCLOSE
	end



