MindaroCity_Flat2_1F_MapScripts::
	.byte 0

MindaroCity_Flat2_1F_EventScript_Man::
	msgbox MindaroCity_Flat2_1F_Text_Tourism, MSGBOX_NPC
	end

MindaroCity_Flat2_1F_Text_Tourism:
	.string "Tourism is a big business\n"
	.string "around here.\p"
	.string "Why we're one of the most popular\n"
	.string "cities to visit in ISSHO!$"

MindaroCity_Flat2_1F_EventScript_Woman::
	msgbox MindaroCity_Flat2_1F_Text_TalkToPeople, MSGBOX_NPC
	end

MindaroCity_Flat2_1F_Text_TalkToPeople:
	.string "Whenever you're traveling, you should\n"
	.string "try talking to new people you meet.\p"
	.string "Some people go to see far off places\n"
	.string "without speaking to anyone there.\p"
	.string "Now what good is that!$"


