#ifndef GUARD_CONSTANTS_BATTLE_STRING_IDS_H
#define GUARD_CONSTANTS_BATTLE_STRING_IDS_H

<<<<<<< Updated upstream
enum StringID
{
    STRINGID_INTROMSG,
    STRINGID_INTROSENDOUT,
    STRINGID_RETURNMON,
    STRINGID_SWITCHINMON,
    STRINGID_USEDMOVE,
    STRINGID_BATTLEEND,
    STRINGID_TRAINERSLIDE,
    STRINGID_TABLE_START, // Make sure to add new messages below this marker
    // todo: make some of those names less vague: attacker/target vs pkmn, etc.
    STRINGID_TRAINER1LOSETEXT,
    STRINGID_PKMNGAINEDEXP,
    STRINGID_PKMNGREWTOLV,
    STRINGID_PKMNLEARNEDMOVE,
    STRINGID_TRYTOLEARNMOVE1,
    STRINGID_TRYTOLEARNMOVE2,
    STRINGID_TRYTOLEARNMOVE3,
    STRINGID_PKMNFORGOTMOVE,
    STRINGID_STOPLEARNINGMOVE,
    STRINGID_DIDNOTLEARNMOVE,
    STRINGID_PKMNLEARNEDMOVE2,
    STRINGID_ATTACKMISSED,
    STRINGID_PKMNPROTECTEDITSELF,
    STRINGID_STATSWONTINCREASE2,
    STRINGID_ITDOESNTAFFECT,
    STRINGID_SCR_ITDOESNTAFFECT,
    STRINGID_BATTLERFAINTED,
    STRINGID_PLAYERGOTMONEY,
    STRINGID_PLAYERWHITEOUT,
    STRINGID_PLAYERWHITEOUT2_WILD,
    STRINGID_PLAYERWHITEOUT2_TRAINER,
    STRINGID_PLAYERWHITEOUT3,
    STRINGID_PREVENTSESCAPE,
    STRINGID_HITXTIMES,
    STRINGID_PKMNFELLASLEEP,
    STRINGID_PKMNMADESLEEP,
    STRINGID_PKMNALREADYASLEEP,
    STRINGID_PKMNALREADYASLEEP2,
    STRINGID_PKMNWASPOISONED,
    STRINGID_PKMNPOISONEDBY,
    STRINGID_PKMNHURTBYPOISON,
    STRINGID_PKMNALREADYPOISONED,
    STRINGID_PKMNBADLYPOISONED,
    STRINGID_PKMNENERGYDRAINED,
    STRINGID_PKMNWASBURNED,
    STRINGID_PKMNBURNEDBY,
    STRINGID_PKMNHURTBYBURN,
    STRINGID_PKMNWASFROZEN,
    STRINGID_PKMNFROZENBY,
    STRINGID_PKMNISFROZEN,
    STRINGID_PKMNWASDEFROSTED,
    STRINGID_PKMNWASDEFROSTEDBY,
    STRINGID_PKMNWASPARALYZED,
    STRINGID_PKMNWASPARALYZEDBY,
    STRINGID_PKMNISPARALYZED,
    STRINGID_PKMNISALREADYPARALYZED,
    STRINGID_PKMNHEALEDPARALYSIS,
    STRINGID_STATSWONTINCREASE,
    STRINGID_STATSWONTDECREASE,
    STRINGID_PKMNISCONFUSED,
    STRINGID_PKMNHEALEDCONFUSION,
    STRINGID_PKMNWASCONFUSED,
    STRINGID_PKMNALREADYCONFUSED,
    STRINGID_PKMNFELLINLOVE,
    STRINGID_PKMNINLOVE,
    STRINGID_PKMNIMMOBILIZEDBYLOVE,
    STRINGID_PKMNCHANGEDTYPE,
    STRINGID_PKMNFLINCHED,
    STRINGID_PKMNREGAINEDHEALTH,
    STRINGID_PKMNHPFULL,
    STRINGID_PKMNRAISEDSPDEF,
    STRINGID_PKMNRAISEDDEF,
    STRINGID_PKMNCOVEREDBYVEIL,
    STRINGID_PKMNUSEDSAFEGUARD,
    STRINGID_PKMNSAFEGUARDEXPIRED,
    STRINGID_PKMNWENTTOSLEEP,
    STRINGID_PKMNSLEPTHEALTHY,
    STRINGID_PKMNWHIPPEDWHIRLWIND,
    STRINGID_PKMNTOOKSUNLIGHT,
    STRINGID_PKMNLOWEREDHEAD,
    STRINGID_PKMNISGLOWING,
    STRINGID_PKMNFLEWHIGH,
    STRINGID_PKMNDUGHOLE,
    STRINGID_PKMNSQUEEZEDBYBIND,
    STRINGID_PKMNTRAPPEDINVORTEX,
    STRINGID_PKMNWRAPPEDBY,
    STRINGID_PKMNCLAMPED,
    STRINGID_PKMNHURTBY,
    STRINGID_PKMNFREEDFROM,
    STRINGID_PKMNCRASHED,
    STRINGID_PKMNSHROUDEDINMIST,
    STRINGID_PKMNPROTECTEDBYMIST,
    STRINGID_PKMNGETTINGPUMPED,
    STRINGID_PKMNHITWITHRECOIL,
    STRINGID_PKMNPROTECTEDITSELF2,
    STRINGID_PKMNBUFFETEDBYSANDSTORM,
    STRINGID_PKMNPELTEDBYHAIL,
    STRINGID_PKMNSEEDED,
    STRINGID_PKMNEVADEDATTACK,
    STRINGID_PKMNSAPPEDBYLEECHSEED,
    STRINGID_PKMNFASTASLEEP,
    STRINGID_PKMNWOKEUP,
    STRINGID_PKMNWOKEUPINUPROAR,
    STRINGID_PKMNCAUSEDUPROAR,
    STRINGID_PKMNMAKINGUPROAR,
    STRINGID_PKMNCALMEDDOWN,
    STRINGID_PKMNSTOCKPILED,
    STRINGID_PKMNCANTSLEEPINUPROAR2,
    STRINGID_UPROARKEPTPKMNAWAKE,
    STRINGID_PKMNSTAYEDAWAKEUSING,
    STRINGID_PKMNSTORINGENERGY,
    STRINGID_PKMNUNLEASHEDENERGY,
    STRINGID_PKMNFATIGUECONFUSION,
    STRINGID_PLAYERPICKEDUPMONEY,
    STRINGID_PKMNUNAFFECTED,
    STRINGID_PKMNTRANSFORMEDINTO,
    STRINGID_PKMNMADESUBSTITUTE,
    STRINGID_PKMNHASSUBSTITUTE,
    STRINGID_SUBSTITUTEDAMAGED,
    STRINGID_PKMNSUBSTITUTEFADED,
    STRINGID_PKMNMUSTRECHARGE,
    STRINGID_PKMNRAGEBUILDING,
    STRINGID_PKMNMOVEWASDISABLED,
    STRINGID_PKMNMOVEISDISABLED,
    STRINGID_PKMNMOVEDISABLEDNOMORE,
    STRINGID_PKMNGOTENCORE,
    STRINGID_PKMNGOTENCOREDMOVE,
    STRINGID_PKMNENCOREENDED,
    STRINGID_PKMNTOOKAIM,
    STRINGID_PKMNSKETCHEDMOVE,
    STRINGID_PKMNTRYINGTOTAKEFOE,
    STRINGID_PKMNTOOKFOE,
    STRINGID_PKMNREDUCEDPP,
    STRINGID_PKMNSTOLEITEM,
    STRINGID_TARGETCANTESCAPENOW,
    STRINGID_PKMNFELLINTONIGHTMARE,
    STRINGID_PKMNLOCKEDINNIGHTMARE,
    STRINGID_PKMNLAIDCURSE,
    STRINGID_PKMNAFFLICTEDBYCURSE,
    STRINGID_SPIKESSCATTERED,
    STRINGID_PKMNHURTBYSPIKES,
    STRINGID_PKMNIDENTIFIED,
    STRINGID_PKMNPERISHCOUNTFELL,
    STRINGID_PKMNBRACEDITSELF,
    STRINGID_PKMNENDUREDHIT,
    STRINGID_MAGNITUDESTRENGTH,
    STRINGID_PKMNCUTHPMAXEDATTACK,
    STRINGID_PKMNCOPIEDSTATCHANGES,
    STRINGID_PKMNGOTFREE,
    STRINGID_PKMNSHEDLEECHSEED,
    STRINGID_PKMNBLEWAWAYSPIKES,
    STRINGID_PKMNFLEDFROMBATTLE,
    STRINGID_PKMNFORESAWATTACK,
    STRINGID_PKMNTOOKATTACK,
    STRINGID_PKMNATTACK,
    STRINGID_PKMNCENTERATTENTION,
    STRINGID_PKMNCHARGINGPOWER,
    STRINGID_NATUREPOWERTURNEDINTO,
    STRINGID_PKMNSTATUSNORMAL,
    STRINGID_PKMNHASNOMOVESLEFT,
    STRINGID_PKMNSUBJECTEDTOTORMENT,
    STRINGID_PKMNCANTUSEMOVETORMENT,
    STRINGID_PKMNTIGHTENINGFOCUS,
    STRINGID_PKMNFELLFORTAUNT,
    STRINGID_PKMNCANTUSEMOVETAUNT,
    STRINGID_PKMNREADYTOHELP,
    STRINGID_PKMNSWITCHEDITEMS,
    STRINGID_PKMNCOPIEDFOE,
    STRINGID_PKMNWISHCAMETRUE,
    STRINGID_PKMNPLANTEDROOTS,
    STRINGID_PKMNABSORBEDNUTRIENTS,
    STRINGID_PKMNANCHOREDITSELF,
    STRINGID_PKMNWASMADEDROWSY,
    STRINGID_PKMNKNOCKEDOFF,
    STRINGID_PKMNSWAPPEDABILITIES,
    STRINGID_PKMNSEALEDOPPONENTMOVE,
    STRINGID_PKMNCANTUSEMOVESEALED,
    STRINGID_PKMNWANTSGRUDGE,
    STRINGID_PKMNLOSTPPGRUDGE,
    STRINGID_PKMNSHROUDEDITSELF,
    STRINGID_PKMNMOVEBOUNCED,
    STRINGID_PKMNWAITSFORTARGET,
    STRINGID_PKMNSNATCHEDMOVE,
    STRINGID_PKMNMADEITRAIN,
    STRINGID_PKMNPROTECTEDBY,
    STRINGID_PKMNPREVENTSUSAGE,
    STRINGID_PKMNRESTOREDHPUSING,
    STRINGID_PKMNCHANGEDTYPEWITH,
    STRINGID_PKMNPREVENTSROMANCEWITH,
    STRINGID_PKMNPREVENTSCONFUSIONWITH,
    STRINGID_PKMNRAISEDFIREPOWERWITH,
    STRINGID_PKMNANCHORSITSELFWITH,
    STRINGID_PKMNCUTSATTACKWITH,
    STRINGID_PKMNPREVENTSSTATLOSSWITH,
    STRINGID_PKMNHURTSWITH,
    STRINGID_PKMNTRACED,
    STRINGID_STATSHARPLY,
    STRINGID_STATHARSHLY,
    STRINGID_ATTACKERSSTATROSE,
    STRINGID_DEFENDERSSTATROSE,
    STRINGID_ATTACKERSSTATFELL,
    STRINGID_DEFENDERSSTATFELL,
    STRINGID_SCRIPTINGSTATROSE,
    STRINGID_CRITICALHIT,
    STRINGID_ONEHITKO,
    STRINGID_123POOF,
    STRINGID_ANDELLIPSIS,
    STRINGID_NOTVERYEFFECTIVE,
    STRINGID_SUPEREFFECTIVE,
    STRINGID_GOTAWAYSAFELY,
    STRINGID_WILDPKMNFLED,
    STRINGID_NORUNNINGFROMTRAINERS,
    STRINGID_CANTESCAPE,
    STRINGID_DONTLEAVEBIRCH,
    STRINGID_BUTNOTHINGHAPPENED,
    STRINGID_BUTITFAILED,
    STRINGID_ITHURTCONFUSION,
    STRINGID_STARTEDTORAIN,
    STRINGID_DOWNPOURSTARTED,
    STRINGID_RAINCONTINUES,
    STRINGID_DOWNPOURCONTINUES,
    STRINGID_RAINSTOPPED,
    STRINGID_SANDSTORMBREWED,
    STRINGID_SANDSTORMRAGES,
    STRINGID_SANDSTORMSUBSIDED,
    STRINGID_SUNLIGHTGOTBRIGHT,
    STRINGID_SUNLIGHTSTRONG,
    STRINGID_SUNLIGHTFADED,
    STRINGID_STARTEDHAIL,
    STRINGID_HAILCONTINUES,
    STRINGID_HAILSTOPPED,
    STRINGID_STATCHANGESGONE,
    STRINGID_COINSSCATTERED,
    STRINGID_TOOWEAKFORSUBSTITUTE,
    STRINGID_SHAREDPAIN,
    STRINGID_BELLCHIMED,
    STRINGID_FAINTINTHREE,
    STRINGID_NOPPLEFT,
    STRINGID_BUTNOPPLEFT,
    STRINGID_PLAYERUSEDITEM,
    STRINGID_WALLYUSEDITEM,
    STRINGID_TRAINERBLOCKEDBALL,
    STRINGID_DONTBEATHIEF,
    STRINGID_ITDODGEDBALL,
    STRINGID_PKMNBROKEFREE,
    STRINGID_ITAPPEAREDCAUGHT,
    STRINGID_AARGHALMOSTHADIT,
    STRINGID_SHOOTSOCLOSE,
    STRINGID_GOTCHAPKMNCAUGHTPLAYER,
    STRINGID_GOTCHAPKMNCAUGHTWALLY,
    STRINGID_GIVENICKNAMECAPTURED,
    STRINGID_PKMNDATAADDEDTODEX,
    STRINGID_ITISRAINING,
    STRINGID_SANDSTORMISRAGING,
    STRINGID_CANTESCAPE2,
    STRINGID_PKMNIGNORESASLEEP,
    STRINGID_PKMNIGNOREDORDERS,
    STRINGID_PKMNBEGANTONAP,
    STRINGID_PKMNLOAFING,
    STRINGID_PKMNWONTOBEY,
    STRINGID_PKMNTURNEDAWAY,
    STRINGID_PKMNPRETENDNOTNOTICE,
    STRINGID_ENEMYABOUTTOSWITCHPKMN,
    STRINGID_CREPTCLOSER,
    STRINGID_CANTGETCLOSER,
    STRINGID_PKMNWATCHINGCAREFULLY,
    STRINGID_PKMNCURIOUSABOUTX,
    STRINGID_PKMNENTHRALLEDBYX,
    STRINGID_PKMNIGNOREDX,
    STRINGID_THREWPOKEBLOCKATPKMN,
    STRINGID_OUTOFSAFARIBALLS,
    STRINGID_PKMNSITEMCUREDPARALYSIS,
    STRINGID_PKMNSITEMCUREDPOISON,
    STRINGID_PKMNSITEMHEALEDBURN,
    STRINGID_PKMNSITEMDEFROSTEDIT,
    STRINGID_PKMNSITEMWOKEIT,
    STRINGID_PKMNSITEMSNAPPEDOUT,
    STRINGID_PKMNSITEMCUREDPROBLEM,
    STRINGID_PKMNSITEMRESTOREDHEALTH,
    STRINGID_PKMNSITEMRESTOREDPP,
    STRINGID_PKMNSITEMRESTOREDSTATUS,
    STRINGID_PKMNSITEMRESTOREDHPALITTLE,
    STRINGID_ITEMALLOWSONLYYMOVE,
    STRINGID_PKMNHUNGONWITHX,
    STRINGID_EMPTYSTRING3,
    STRINGID_PKMNSXRESTOREDHPALITTLE2,
    STRINGID_PKMNSXWHIPPEDUPSANDSTORM,
    STRINGID_PKMNSXPREVENTSYLOSS,
    STRINGID_PKMNSXINFATUATEDY,
    STRINGID_PKMNSXMADEYINEFFECTIVE,
    STRINGID_PKMNSXCUREDYPROBLEM,
    STRINGID_ITSUCKEDLIQUIDOOZE,
    STRINGID_PKMNTRANSFORMED,
    STRINGID_ELECTRICITYWEAKENED,
    STRINGID_FIREWEAKENED,
    STRINGID_PKMNHIDUNDERWATER,
    STRINGID_PKMNSPRANGUP,
    STRINGID_HMMOVESCANTBEFORGOTTEN,
    STRINGID_XFOUNDONEY,
    STRINGID_PLAYERDEFEATEDTRAINER1,
    STRINGID_SOOTHINGAROMA,
    STRINGID_ITEMSCANTBEUSEDNOW,
    STRINGID_USINGITEMSTATOFPKMNROSE,
    STRINGID_USINGITEMSTATOFPKMNFELL,
    STRINGID_PKMNUSEDXTOGETPUMPED,
    STRINGID_PKMNSXMADEYUSELESS,
    STRINGID_PKMNTRAPPEDBYSANDTOMB,
    STRINGID_EMPTYSTRING4,
    STRINGID_ABOOSTED,
    STRINGID_PKMNSXINTENSIFIEDSUN,
    STRINGID_YOUTHROWABALLNOWRIGHT,
    STRINGID_PKMNSXTOOKATTACK,
    STRINGID_PKMNCHOSEXASDESTINY,
    STRINGID_PKMNLOSTFOCUS,
    STRINGID_USENEXTPKMN,
    STRINGID_PKMNFLEDUSINGITS,
    STRINGID_PKMNFLEDUSING,
    STRINGID_PKMNWASDRAGGEDOUT,
    STRINGID_PKMNSITEMNORMALIZEDSTATUS,
    STRINGID_TRAINER1USEDITEM,
    STRINGID_BOXISFULL,
    STRINGID_PKMNAVOIDEDATTACK,
    STRINGID_PKMNSXMADEITINEFFECTIVE,
    STRINGID_PKMNSXPREVENTSFLINCHING,
    STRINGID_PKMNALREADYHASBURN,
    STRINGID_STATSWONTDECREASE2,
    STRINGID_PKMNSXBLOCKSY,
    STRINGID_PKMNSXWOREOFF,
    STRINGID_THEWALLSHATTERED,
    STRINGID_PKMNSXCUREDITSYPROBLEM,
    STRINGID_ATTACKERCANTESCAPE,
    STRINGID_PKMNOBTAINEDX,
    STRINGID_PKMNOBTAINEDX2,
    STRINGID_PKMNOBTAINEDXYOBTAINEDZ,
    STRINGID_BUTNOEFFECT,
    STRINGID_TWOENEMIESDEFEATED,
    STRINGID_TRAINER2LOSETEXT,
    STRINGID_PKMNINCAPABLEOFPOWER,
    STRINGID_GLINTAPPEARSINEYE,
    STRINGID_PKMNGETTINGINTOPOSITION,
    STRINGID_PKMNBEGANGROWLINGDEEPLY,
    STRINGID_PKMNEAGERFORMORE,
    STRINGID_DEFEATEDOPPONENTBYREFEREE,
    STRINGID_LOSTTOOPPONENTBYREFEREE,
    STRINGID_TIEDOPPONENTBYREFEREE,
    STRINGID_QUESTIONFORFEITMATCH,
    STRINGID_FORFEITEDMATCH,
    STRINGID_PKMNTRANSFERREDSOMEONESPC,
    STRINGID_PKMNTRANSFERREDLANETTESPC,
    STRINGID_PKMNBOXSOMEONESPCFULL,
    STRINGID_PKMNBOXLANETTESPCFULL,
    STRINGID_TRAINER1WINTEXT,
    STRINGID_TRAINER2WINTEXT,
    STRINGID_ENDUREDSTURDY,
    STRINGID_POWERHERB,
    STRINGID_HURTBYITEM,
    STRINGID_GRAVITYINTENSIFIED,
    STRINGID_TARGETWOKEUP,
    STRINGID_TAILWINDBLEW,
    STRINGID_PKMNWENTBACK,
    STRINGID_PKMNCANTUSEITEMSANYMORE,
    STRINGID_PKMNFLUNG,
    STRINGID_PKMNPREVENTEDFROMHEALING,
    STRINGID_PKMNSWITCHEDATKANDDEF,
    STRINGID_PKMNSABILITYSUPPRESSED,
    STRINGID_SHIELDEDFROMCRITICALHITS,
    STRINGID_PKMNACQUIREDABILITY,
    STRINGID_POISONSPIKESSCATTERED,
    STRINGID_PKMNSWITCHEDSTATCHANGES,
    STRINGID_PKMNSURROUNDEDWITHVEILOFWATER,
    STRINGID_PKMNLEVITATEDONELECTROMAGNETISM,
    STRINGID_PKMNTWISTEDDIMENSIONS,
    STRINGID_POINTEDSTONESFLOAT,
    STRINGID_TRAPPEDBYSWIRLINGMAGMA,
    STRINGID_VANISHEDINSTANTLY,
    STRINGID_PROTECTEDTEAM,
    STRINGID_SHAREDITSGUARD,
    STRINGID_SHAREDITSPOWER,
    STRINGID_SWAPSDEFANDSPDEFOFALLPOKEMON,
    STRINGID_BECAMENIMBLE,
    STRINGID_HURLEDINTOTHEAIR,
    STRINGID_HELDITEMSLOSEEFFECTS,
    STRINGID_FELLSTRAIGHTDOWN,
    STRINGID_TARGETCHANGEDTYPE,
    STRINGID_KINDOFFER,
    STRINGID_RESETSTARGETSSTATLEVELS,
    STRINGID_ALLYSWITCHPOSITION,
    STRINGID_REFLECTTARGETSTYPE,
    STRINGID_EMBARGOENDS,
    STRINGID_ELECTROMAGNETISM,
    STRINGID_BUFFERENDS,
    STRINGID_TELEKINESISENDS,
    STRINGID_TAILWINDENDS,
    STRINGID_LUCKYCHANTENDS,
    STRINGID_TRICKROOMENDS,
    STRINGID_WONDERROOMENDS,
    STRINGID_MAGICROOMENDS,
    STRINGID_MUDSPORTENDS,
    STRINGID_WATERSPORTENDS,
    STRINGID_GRAVITYENDS,
    STRINGID_AQUARINGHEAL,
    STRINGID_ELECTRICTERRAINENDS,
    STRINGID_MISTYTERRAINENDS,
    STRINGID_PSYCHICTERRAINENDS,
    STRINGID_GRASSYTERRAINENDS,
    STRINGID_TARGETABILITYSTATRAISE,
    STRINGID_TARGETSSTATWASMAXEDOUT,
    STRINGID_ATTACKERABILITYSTATRAISE,
    STRINGID_POISONHEALHPUP,
    STRINGID_BADDREAMSDMG,
    STRINGID_MOLDBREAKERENTERS,
    STRINGID_TERAVOLTENTERS,
    STRINGID_TURBOBLAZEENTERS,
    STRINGID_SLOWSTARTENTERS,
    STRINGID_SLOWSTARTEND,
    STRINGID_SOLARPOWERHPDROP,
    STRINGID_AFTERMATHDMG,
    STRINGID_ANTICIPATIONACTIVATES,
    STRINGID_FOREWARNACTIVATES,
    STRINGID_ICEBODYHPGAIN,
    STRINGID_SNOWWARNINGHAIL,
    STRINGID_FRISKACTIVATES,
    STRINGID_UNNERVEENTERS,
    STRINGID_HARVESTBERRY,
    STRINGID_PROTEANTYPECHANGE,
    STRINGID_SYMBIOSISITEMPASS,
    STRINGID_STEALTHROCKDMG,
    STRINGID_TOXICSPIKESABSORBED,
    STRINGID_TOXICSPIKESPOISONED,
    STRINGID_TOXICSPIKESBADLYPOISONED,
    STRINGID_STICKYWEBSWITCHIN,
    STRINGID_HEALINGWISHCAMETRUE,
    STRINGID_HEALINGWISHHEALED,
    STRINGID_LUNARDANCECAMETRUE,
    STRINGID_CURSEDBODYDISABLED,
    STRINGID_ATTACKERACQUIREDABILITY,
    STRINGID_TARGETABILITYSTATLOWER,
    STRINGID_TARGETSTATWONTGOHIGHER,
    STRINGID_PKMNMOVEBOUNCEDABILITY,
    STRINGID_IMPOSTERTRANSFORM,
    STRINGID_ASSAULTVESTDOESNTALLOW,
    STRINGID_GRAVITYPREVENTSUSAGE,
    STRINGID_HEALBLOCKPREVENTSUSAGE,
    STRINGID_NOTDONEYET,
    STRINGID_STICKYWEBUSED,
    STRINGID_QUASHSUCCESS,
    STRINGID_PKMNBLEWAWAYTOXICSPIKES,
    STRINGID_PKMNBLEWAWAYSTICKYWEB,
    STRINGID_PKMNBLEWAWAYSTEALTHROCK,
    STRINGID_IONDELUGEON,
    STRINGID_TOPSYTURVYSWITCHEDSTATS,
    STRINGID_TERRAINBECOMESMISTY,
    STRINGID_TERRAINBECOMESGRASSY,
    STRINGID_TERRAINBECOMESELECTRIC,
    STRINGID_TERRAINBECOMESPSYCHIC,
    STRINGID_TARGETELECTRIFIED,
    STRINGID_MEGAEVOREACTING,
    STRINGID_MEGAEVOEVOLVED,
    STRINGID_DRASTICALLY,
    STRINGID_SEVERELY,
    STRINGID_INFESTATION,
    STRINGID_NOEFFECTONTARGET,
    STRINGID_BURSTINGFLAMESHIT,
    STRINGID_BESTOWITEMGIVING,
    STRINGID_THIRDTYPEADDED,
    STRINGID_FELLFORFEINT,
    STRINGID_POKEMONCANNOTUSEMOVE,
    STRINGID_COVEREDINPOWDER,
    STRINGID_POWDEREXPLODES,
    STRINGID_BELCHCANTSELECT,
    STRINGID_SPECTRALTHIEFSTEAL,
    STRINGID_GRAVITYGROUNDING,
    STRINGID_MISTYTERRAINPREVENTS,
    STRINGID_GRASSYTERRAINHEALS,
    STRINGID_ELECTRICTERRAINPREVENTS,
    STRINGID_PSYCHICTERRAINPREVENTS,
    STRINGID_SAFETYGOGGLESPROTECTED,
    STRINGID_FLOWERVEILPROTECTED,
    STRINGID_AROMAVEILPROTECTED,
    STRINGID_CELEBRATEMESSAGE,
    STRINGID_USEDINSTRUCTEDMOVE,
    STRINGID_THROATCHOPENDS,
    STRINGID_PKMNCANTUSEMOVETHROATCHOP,
    STRINGID_LASERFOCUS,
    STRINGID_GEMACTIVATES,
    STRINGID_BERRYDMGREDUCES,
    STRINGID_AIRBALLOONFLOAT,
    STRINGID_AIRBALLOONPOP,
    STRINGID_INCINERATEBURN,
    STRINGID_BUGBITE,
    STRINGID_ILLUSIONWOREOFF,
    STRINGID_ATTACKERCUREDTARGETSTATUS,
    STRINGID_ATTACKERLOSTFIRETYPE,
    STRINGID_HEALERCURE,
    STRINGID_SCRIPTINGABILITYSTATRAISE,
    STRINGID_RECEIVERABILITYTAKEOVER,
    STRINGID_PKNMABSORBINGPOWER,
    STRINGID_NOONEWILLBEABLETORUNAWAY,
    STRINGID_DESTINYKNOTACTIVATES,
    STRINGID_CLOAKEDINAFREEZINGLIGHT,
    STRINGID_CLEARAMULETWONTLOWERSTATS,
    STRINGID_FERVENTWISHREACHED,
    STRINGID_AIRLOCKACTIVATES,
    STRINGID_PRESSUREENTERS,
    STRINGID_DARKAURAENTERS,
    STRINGID_FAIRYAURAENTERS,
    STRINGID_AURABREAKENTERS,
    STRINGID_COMATOSEENTERS,
    STRINGID_SCREENCLEANERENTERS,
    STRINGID_FETCHEDPOKEBALL,
    STRINGID_ASANDSTORMKICKEDUP,
    STRINGID_PKMNSWILLPERISHIN3TURNS,
    STRINGID_AURAFLAREDTOLIFE,
    STRINGID_ASONEENTERS,
    STRINGID_CURIOUSMEDICINEENTERS,
    STRINGID_CANACTFASTERTHANKSTO,
    STRINGID_MICLEBERRYACTIVATES,
    STRINGID_PKMNSHOOKOFFTHETAUNT,
    STRINGID_PKMNGOTOVERITSINFATUATION,
    STRINGID_ITEMCANNOTBEREMOVED,
    STRINGID_STICKYBARBTRANSFER,
    STRINGID_PKMNBURNHEALED,
    STRINGID_REDCARDACTIVATE,
    STRINGID_EJECTBUTTONACTIVATE,
    STRINGID_ATKGOTOVERINFATUATION,
    STRINGID_TORMENTEDNOMORE,
    STRINGID_HEALBLOCKEDNOMORE,
    STRINGID_ATTACKERBECAMEFULLYCHARGED,
    STRINGID_ATTACKERBECAMEASHSPECIES,
    STRINGID_EXTREMELYHARSHSUNLIGHT,
    STRINGID_EXTREMESUNLIGHTFADED,
    STRINGID_MOVEEVAPORATEDINTHEHARSHSUNLIGHT,
    STRINGID_EXTREMELYHARSHSUNLIGHTWASNOTLESSENED,
    STRINGID_HEAVYRAIN,
    STRINGID_HEAVYRAINLIFTED,
    STRINGID_MOVEFIZZLEDOUTINTHEHEAVYRAIN,
    STRINGID_NORELIEFROMHEAVYRAIN,
    STRINGID_MYSTERIOUSAIRCURRENT,
    STRINGID_STRONGWINDSDISSIPATED,
    STRINGID_MYSTERIOUSAIRCURRENTBLOWSON,
    STRINGID_ATTACKWEAKENEDBSTRONGWINDS,
    STRINGID_STUFFCHEEKSCANTSELECT,
    STRINGID_PKMNREVERTEDTOPRIMAL,
    STRINGID_BUTPOKEMONCANTUSETHEMOVE,
    STRINGID_BUTHOOPACANTUSEIT,
    STRINGID_BROKETHROUGHPROTECTION,
    STRINGID_ABILITYALLOWSONLYMOVE,
    STRINGID_SWAPPEDABILITIES,
    STRINGID_PASTELVEILENTERS,
    STRINGID_BATTLERTYPECHANGEDTO,
    STRINGID_BOTHCANNOLONGERESCAPE,
    STRINGID_CANTESCAPEDUETOUSEDMOVE,
    STRINGID_PKMNBECAMEWEAKERTOFIRE,
    STRINGID_ABOUTTOUSEPOLTERGEIST,
    STRINGID_CANTESCAPEBECAUSEOFCURRENTMOVE,
    STRINGID_NEUTRALIZINGGASENTERS,
    STRINGID_NEUTRALIZINGGASOVER,
    STRINGID_TARGETTOOHEAVY,
    STRINGID_PKMNTOOKTARGETHIGH,
    STRINGID_PKMNINSNAPTRAP,
    STRINGID_METEORBEAMCHARGING,
    STRINGID_HEATUPBEAK,
    STRINGID_COURTCHANGE,
    STRINGID_ZPOWERSURROUNDS,
    STRINGID_ZMOVEUNLEASHED,
    STRINGID_ZMOVERESETSSTATS,
    STRINGID_ZMOVEALLSTATSUP,
    STRINGID_ZMOVEZBOOSTCRIT,
    STRINGID_ZMOVERESTOREHP,
    STRINGID_ZMOVESTATUP,
    STRINGID_ZMOVEHPTRAP,
    STRINGID_ATTACKEREXPELLEDTHEPOISON,
    STRINGID_ATTACKERSHOOKITSELFAWAKE,
    STRINGID_ATTACKERBROKETHROUGHPARALYSIS,
    STRINGID_ATTACKERHEALEDITSBURN,
    STRINGID_ATTACKERMELTEDTHEICE,
    STRINGID_TARGETTOUGHEDITOUT,
    STRINGID_ATTACKERLOSTELECTRICTYPE,
    STRINGID_ATTACKERSWITCHEDSTATWITHTARGET,
    STRINGID_BEINGHITCHARGEDPKMNWITHPOWER,
    STRINGID_SUNLIGHTACTIVATEDABILITY,
    STRINGID_STATWASHEIGHTENED,
    STRINGID_ELECTRICTERRAINACTIVATEDABILITY,
    STRINGID_ABILITYWEAKENEDSURROUNDINGMONSSTAT,
    STRINGID_ATTACKERGAINEDSTRENGTHFROMTHEFALLEN,
    STRINGID_PKMNSABILITYPREVENTSABILITY,
    STRINGID_PREPARESHELLTRAP,
    STRINGID_SHELLTRAPDIDNTWORK,
    STRINGID_SPIKESDISAPPEAREDFROMTEAM,
    STRINGID_TOXICSPIKESDISAPPEAREDFROMTEAM,
    STRINGID_STICKYWEBDISAPPEAREDFROMTEAM,
    STRINGID_STEALTHROCKDISAPPEAREDFROMTEAM,
    STRINGID_COULDNTFULLYPROTECT,
    STRINGID_STOCKPILEDEFFECTWOREOFF,
    STRINGID_PKMNREVIVEDREADYTOFIGHT,
    STRINGID_ITEMRESTOREDSPECIESHEALTH,
    STRINGID_ITEMCUREDSPECIESSTATUS,
    STRINGID_ITEMRESTOREDSPECIESPP,
    STRINGID_THUNDERCAGETRAPPED,
    STRINGID_PKMNHURTBYFROSTBITE,
    STRINGID_PKMNGOTFROSTBITE,
    STRINGID_PKMNSITEMHEALEDFROSTBITE,
    STRINGID_ATTACKERHEALEDITSFROSTBITE,
    STRINGID_PKMNFROSTBITEHEALED,
    STRINGID_PKMNFROSTBITEHEALEDBY,
    STRINGID_MIRRORHERBCOPIED,
    STRINGID_STARTEDSNOW,
    STRINGID_SNOWCONTINUES,
    STRINGID_SNOWSTOPPED,
    STRINGID_SNOWWARNINGSNOW,
    STRINGID_PKMNITEMMELTED,
    STRINGID_ULTRABURSTREACTING,
    STRINGID_ULTRABURSTCOMPLETED,
    STRINGID_TEAMGAINEDEXP,
    STRINGID_CURRENTMOVECANTSELECT,
    STRINGID_TARGETISBEINGSALTCURED,
    STRINGID_TARGETISHURTBYSALTCURE,
    STRINGID_TARGETCOVEREDINSTICKYCANDYSYRUP,
    STRINGID_SHARPSTEELFLOATS,
    STRINGID_SHARPSTEELDMG,
    STRINGID_PKMNBLEWAWAYSHARPSTEEL,
    STRINGID_SHARPSTEELDISAPPEAREDFROMTEAM,
    STRINGID_TEAMTRAPPEDWITHVINES,
    STRINGID_PKMNHURTBYVINES,
    STRINGID_TEAMCAUGHTINVORTEX,
    STRINGID_PKMNHURTBYVORTEX,
    STRINGID_TEAMSURROUNDEDBYFIRE,
    STRINGID_PKMNBURNINGUP,
    STRINGID_TEAMSURROUNDEDBYROCKS,
    STRINGID_PKMNHURTBYROCKSTHROWN,
    STRINGID_MOVEBLOCKEDBYDYNAMAX,
    STRINGID_ZEROTOHEROTRANSFORMATION,
    STRINGID_THETWOMOVESBECOMEONE,
    STRINGID_ARAINBOWAPPEAREDONSIDE,
    STRINGID_THERAINBOWDISAPPEARED,
    STRINGID_WAITINGFORPARTNERSMOVE,
    STRINGID_SEAOFFIREENVELOPEDSIDE,
    STRINGID_HURTBYTHESEAOFFIRE,
    STRINGID_THESEAOFFIREDISAPPEARED,
    STRINGID_SWAMPENVELOPEDSIDE,
    STRINGID_THESWAMPDISAPPEARED,
    STRINGID_PKMNTELLCHILLINGRECEPTIONJOKE,
    STRINGID_HOSPITALITYRESTORATION,
    STRINGID_ELECTROSHOTCHARGING,
    STRINGID_ITEMWASUSEDUP,
    STRINGID_ATTACKERLOSTITSTYPE,
    STRINGID_SHEDITSTAIL,
    STRINGID_CLOAKEDINAHARSHLIGHT,
    STRINGID_SUPERSWEETAROMAWAFTS,
    STRINGID_DIMENSIONSWERETWISTED,
    STRINGID_BIZARREARENACREATED,
    STRINGID_BIZARREAREACREATED,
    STRINGID_TIDYINGUPCOMPLETE,
    STRINGID_PKMNTERASTALLIZEDINTO,
    STRINGID_BOOSTERENERGYACTIVATES,
    STRINGID_FOGCREPTUP,
    STRINGID_FOGISDEEP,
    STRINGID_FOGLIFTED,
    STRINGID_PKMNMADESHELLGLEAM,
    STRINGID_FICKLEBEAMDOUBLED,
    STRINGID_COMMANDERACTIVATES,
    STRINGID_POKEFLUTECATCHY,
    STRINGID_POKEFLUTE,
    STRINGID_MONHEARINGFLUTEAWOKE,
    STRINGID_SUNLIGHTISHARSH,
    STRINGID_ITISHAILING,
    STRINGID_ITISSNOWING,
    STRINGID_ISCOVEREDWITHGRASS,
    STRINGID_MISTSWIRLSAROUND,
    STRINGID_ELECTRICCURRENTISRUNNING,
    STRINGID_SEEMSWEIRD,
    STRINGID_WAGGLINGAFINGER,
    STRINGID_BLOCKEDBYSLEEPCLAUSE,
    STRINGID_SUPEREFFECTIVETWOFOES,
    STRINGID_NOTVERYEFFECTIVETWOFOES,
    STRINGID_ITDOESNTAFFECTTWOFOES,
    STRINGID_SENDCAUGHTMONPARTYORBOX,
    STRINGID_PKMNSENTTOPCAFTERCATCH,
    STRINGID_PKMNDYNAMAXED,
    STRINGID_PKMNGIGANTAMAXED,
    STRINGID_TIMETODYNAMAX,
    STRINGID_TIMETOGIGANTAMAX,
    STRINGID_QUESTIONFORFEITBATTLE,
    STRINGID_POWERCONSTRUCTPRESENCEOFMANY,
    STRINGID_POWERCONSTRUCTTRANSFORM,
    STRINGID_ABILITYSHIELDPROTECTS,
    STRINGID_MONTOOSCAREDTOMOVE,
    STRINGID_GHOSTGETOUTGETOUT,
    STRINGID_SILPHSCOPEUNVEILED,
    STRINGID_GHOSTWASMAROWAK,
    STRINGID_TRAINER1MON1COMEBACK,
    STRINGID_THREWROCK,
    STRINGID_THREWBAIT,
    STRINGID_PKMNANGRY,
    STRINGID_PKMNEATING,
    STRINGID_PKMNDISGUISEWASBUSTED,
    STRINGID_ZENMODETRIGGERED,
    STRINGID_ZENMODEENDED,
    STRINGID_COUNT
};
=======
#define STRINGID_INTROMSG       0
#define STRINGID_INTROSENDOUT   1
#define STRINGID_RETURNMON      2
#define STRINGID_SWITCHINMON    3
#define STRINGID_USEDMOVE       4
#define STRINGID_BATTLEEND      5
#define STRINGID_TRAINERSLIDE   6

// todo: make some of those names less vague: attacker/target vs pkmn, etc.
#define STRINGID_TRAINER1LOSETEXT                     12
#define STRINGID_PKMNGAINEDEXP                        13
#define STRINGID_PKMNGREWTOLV                         14
#define STRINGID_PKMNLEARNEDMOVE                      15
#define STRINGID_TRYTOLEARNMOVE1                      16
#define STRINGID_TRYTOLEARNMOVE2                      17
#define STRINGID_TRYTOLEARNMOVE3                      18
#define STRINGID_PKMNFORGOTMOVE                       19
#define STRINGID_STOPLEARNINGMOVE                     20
#define STRINGID_DIDNOTLEARNMOVE                      21
#define STRINGID_PKMNLEARNEDMOVE2                     22
#define STRINGID_ATTACKMISSED                         23
#define STRINGID_PKMNPROTECTEDITSELF                  24
#define STRINGID_STATSWONTINCREASE2                   25
#define STRINGID_AVOIDEDDAMAGE                        26
#define STRINGID_ITDOESNTAFFECT                       27
#define STRINGID_ATTACKERFAINTED                      28
#define STRINGID_TARGETFAINTED                        29
#define STRINGID_PLAYERGOTMONEY                       30
#define STRINGID_PLAYERWHITEOUT                       31
#define STRINGID_PLAYERWHITEOUT2                      32
#define STRINGID_PREVENTSESCAPE                       33
#define STRINGID_HITXTIMES                            34
#define STRINGID_PKMNFELLASLEEP                       35
#define STRINGID_PKMNMADESLEEP                        36
#define STRINGID_PKMNALREADYASLEEP                    37
#define STRINGID_PKMNALREADYASLEEP2                   38
#define STRINGID_PKMNWASNTAFFECTED                    39
#define STRINGID_PKMNWASPOISONED                      40
#define STRINGID_PKMNPOISONEDBY                       41
#define STRINGID_PKMNHURTBYPOISON                     42
#define STRINGID_PKMNALREADYPOISONED                  43
#define STRINGID_PKMNBADLYPOISONED                    44
#define STRINGID_PKMNENERGYDRAINED                    45
#define STRINGID_PKMNWASBURNED                        46
#define STRINGID_PKMNBURNEDBY                         47
#define STRINGID_PKMNHURTBYBURN                       48
#define STRINGID_PKMNWASFROZEN                        49
#define STRINGID_PKMNFROZENBY                         50
#define STRINGID_PKMNISFROZEN                         51
#define STRINGID_PKMNWASDEFROSTED                     52
#define STRINGID_PKMNWASDEFROSTED2                    53
#define STRINGID_PKMNWASDEFROSTEDBY                   54
#define STRINGID_PKMNWASPARALYZED                     55
#define STRINGID_PKMNWASPARALYZEDBY                   56
#define STRINGID_PKMNISPARALYZED                      57
#define STRINGID_PKMNISALREADYPARALYZED               58
#define STRINGID_PKMNHEALEDPARALYSIS                  59
#define STRINGID_PKMNDREAMEATEN                       60
#define STRINGID_STATSWONTINCREASE                    61
#define STRINGID_STATSWONTDECREASE                    62
#define STRINGID_TEAMSTOPPEDWORKING                   63
#define STRINGID_FOESTOPPEDWORKING                    64
#define STRINGID_PKMNISCONFUSED                       65
#define STRINGID_PKMNHEALEDCONFUSION                  66
#define STRINGID_PKMNWASCONFUSED                      67
#define STRINGID_PKMNALREADYCONFUSED                  68
#define STRINGID_PKMNFELLINLOVE                       69
#define STRINGID_PKMNINLOVE                           70
#define STRINGID_PKMNIMMOBILIZEDBYLOVE                71
#define STRINGID_PKMNBLOWNAWAY                        72
#define STRINGID_PKMNCHANGEDTYPE                      73
#define STRINGID_PKMNFLINCHED                         74
#define STRINGID_PKMNREGAINEDHEALTH                   75
#define STRINGID_PKMNHPFULL                           76
#define STRINGID_PKMNRAISEDSPDEF                      77
#define STRINGID_PKMNRAISEDDEF                        78
#define STRINGID_PKMNCOVEREDBYVEIL                    79
#define STRINGID_PKMNUSEDSAFEGUARD                    80
#define STRINGID_PKMNSAFEGUARDEXPIRED                 81
#define STRINGID_PKMNWENTTOSLEEP                      82
#define STRINGID_PKMNSLEPTHEALTHY                     83
#define STRINGID_PKMNWHIPPEDWHIRLWIND                 84
#define STRINGID_PKMNTOOKSUNLIGHT                     85
#define STRINGID_PKMNLOWEREDHEAD                      86
#define STRINGID_PKMNISGLOWING                        87
#define STRINGID_PKMNFLEWHIGH                         88
#define STRINGID_PKMNDUGHOLE                          89
#define STRINGID_PKMNSQUEEZEDBYBIND                   90
#define STRINGID_PKMNTRAPPEDINVORTEX                  91
#define STRINGID_PKMNWRAPPEDBY                        92
#define STRINGID_PKMNCLAMPED                          93
#define STRINGID_PKMNHURTBY                           94
#define STRINGID_PKMNFREEDFROM                        95
#define STRINGID_PKMNCRASHED                          96
#define STRINGID_PKMNSHROUDEDINMIST                   97
#define STRINGID_PKMNPROTECTEDBYMIST                  98
#define STRINGID_PKMNGETTINGPUMPED                    99
#define STRINGID_PKMNHITWITHRECOIL                    100
#define STRINGID_PKMNPROTECTEDITSELF2                 101
#define STRINGID_PKMNBUFFETEDBYSANDSTORM              102
#define STRINGID_PKMNPELTEDBYHAIL                     103
#define STRINGID_PKMNSEEDED                           104
#define STRINGID_PKMNEVADEDATTACK                     105
#define STRINGID_PKMNSAPPEDBYLEECHSEED                106
#define STRINGID_PKMNFASTASLEEP                       107
#define STRINGID_PKMNWOKEUP                           108
#define STRINGID_PKMNUPROARKEPTAWAKE                  109
#define STRINGID_PKMNWOKEUPINUPROAR                   110
#define STRINGID_PKMNCAUSEDUPROAR                     111
#define STRINGID_PKMNMAKINGUPROAR                     112
#define STRINGID_PKMNCALMEDDOWN                       113
#define STRINGID_PKMNCANTSLEEPINUPROAR                114
#define STRINGID_PKMNSTOCKPILED                       115
#define STRINGID_PKMNCANTSTOCKPILE                    116
#define STRINGID_PKMNCANTSLEEPINUPROAR2               117
#define STRINGID_UPROARKEPTPKMNAWAKE                  118
#define STRINGID_PKMNSTAYEDAWAKEUSING                 119
#define STRINGID_PKMNSTORINGENERGY                    120
#define STRINGID_PKMNUNLEASHEDENERGY                  121
#define STRINGID_PKMNFATIGUECONFUSION                 122
#define STRINGID_PLAYERPICKEDUPMONEY                  123
#define STRINGID_PKMNUNAFFECTED                       124
#define STRINGID_PKMNTRANSFORMEDINTO                  125
#define STRINGID_PKMNMADESUBSTITUTE                   126
#define STRINGID_PKMNHASSUBSTITUTE                    127
#define STRINGID_SUBSTITUTEDAMAGED                    128
#define STRINGID_PKMNSUBSTITUTEFADED                  129
#define STRINGID_PKMNMUSTRECHARGE                     130
#define STRINGID_PKMNRAGEBUILDING                     131
#define STRINGID_PKMNMOVEWASDISABLED                  132
#define STRINGID_PKMNMOVEISDISABLED                   133
#define STRINGID_PKMNMOVEDISABLEDNOMORE               134
#define STRINGID_PKMNGOTENCORE                        135
#define STRINGID_PKMNENCOREENDED                      136
#define STRINGID_PKMNTOOKAIM                          137
#define STRINGID_PKMNSKETCHEDMOVE                     138
#define STRINGID_PKMNTRYINGTOTAKEFOE                  139
#define STRINGID_PKMNTOOKFOE                          140
#define STRINGID_PKMNREDUCEDPP                        141
#define STRINGID_PKMNSTOLEITEM                        142
#define STRINGID_TARGETCANTESCAPENOW                  143
#define STRINGID_PKMNFELLINTONIGHTMARE                144
#define STRINGID_PKMNLOCKEDINNIGHTMARE                145
#define STRINGID_PKMNLAIDCURSE                        146
#define STRINGID_PKMNAFFLICTEDBYCURSE                 147
#define STRINGID_SPIKESSCATTERED                      148
#define STRINGID_PKMNHURTBYSPIKES                     149
#define STRINGID_PKMNIDENTIFIED                       150
#define STRINGID_PKMNPERISHCOUNTFELL                  151
#define STRINGID_PKMNBRACEDITSELF                     152
#define STRINGID_PKMNENDUREDHIT                       153
#define STRINGID_MAGNITUDESTRENGTH                    154
#define STRINGID_PKMNCUTHPMAXEDATTACK                 155
#define STRINGID_PKMNCOPIEDSTATCHANGES                156
#define STRINGID_PKMNGOTFREE                          157
#define STRINGID_PKMNSHEDLEECHSEED                    158
#define STRINGID_PKMNBLEWAWAYSPIKES                   159
#define STRINGID_PKMNFLEDFROMBATTLE                   160
#define STRINGID_PKMNFORESAWATTACK                    161
#define STRINGID_PKMNTOOKATTACK                       162
#define STRINGID_PKMNATTACK                           163
#define STRINGID_PKMNCENTERATTENTION                  164
#define STRINGID_PKMNCHARGINGPOWER                    165
#define STRINGID_NATUREPOWERTURNEDINTO                166
#define STRINGID_PKMNSTATUSNORMAL                     167
#define STRINGID_PKMNHASNOMOVESLEFT                   168
#define STRINGID_PKMNSUBJECTEDTOTORMENT               169
#define STRINGID_PKMNCANTUSEMOVETORMENT               170
#define STRINGID_PKMNTIGHTENINGFOCUS                  171
#define STRINGID_PKMNFELLFORTAUNT                     172
#define STRINGID_PKMNCANTUSEMOVETAUNT                 173
#define STRINGID_PKMNREADYTOHELP                      174
#define STRINGID_PKMNSWITCHEDITEMS                    175
#define STRINGID_PKMNCOPIEDFOE                        176
#define STRINGID_PKMNMADEWISH                         177
#define STRINGID_PKMNWISHCAMETRUE                     178
#define STRINGID_PKMNPLANTEDROOTS                     179
#define STRINGID_PKMNABSORBEDNUTRIENTS                180
#define STRINGID_PKMNANCHOREDITSELF                   181
#define STRINGID_PKMNWASMADEDROWSY                    182
#define STRINGID_PKMNKNOCKEDOFF                       183
#define STRINGID_PKMNSWAPPEDABILITIES                 184
#define STRINGID_PKMNSEALEDOPPONENTMOVE               185
#define STRINGID_PKMNCANTUSEMOVESEALED                186
#define STRINGID_PKMNWANTSGRUDGE                      187
#define STRINGID_PKMNLOSTPPGRUDGE                     188
#define STRINGID_PKMNSHROUDEDITSELF                   189
#define STRINGID_PKMNMOVEBOUNCED                      190
#define STRINGID_PKMNWAITSFORTARGET                   191
#define STRINGID_PKMNSNATCHEDMOVE                     192
#define STRINGID_PKMNMADEITRAIN                       193
#define STRINGID_PKMNRAISEDSPEED                      194
#define STRINGID_PKMNPROTECTEDBY                      195
#define STRINGID_PKMNPREVENTSUSAGE                    196
#define STRINGID_PKMNRESTOREDHPUSING                  197
#define STRINGID_PKMNCHANGEDTYPEWITH                  198
#define STRINGID_PKMNPREVENTSPARALYSISWITH            199
#define STRINGID_PKMNPREVENTSROMANCEWITH              200
#define STRINGID_PKMNPREVENTSPOISONINGWITH            201
#define STRINGID_PKMNPREVENTSCONFUSIONWITH            202
#define STRINGID_PKMNRAISEDFIREPOWERWITH              203
#define STRINGID_PKMNANCHORSITSELFWITH                204
#define STRINGID_PKMNCUTSATTACKWITH                   205
#define STRINGID_PKMNPREVENTSSTATLOSSWITH             206
#define STRINGID_PKMNHURTSWITH                        207
#define STRINGID_PKMNTRACED                           208
#define STRINGID_STATSHARPLY                          209
#define STRINGID_STATROSE                             210
#define STRINGID_STATHARSHLY                          211
#define STRINGID_STATFELL                             212
#define STRINGID_ATTACKERSSTATROSE                    213
#define STRINGID_DEFENDERSSTATROSE                    214
#define STRINGID_ATTACKERSSTATFELL                    215
#define STRINGID_DEFENDERSSTATFELL                    216
#define STRINGID_CRITICALHIT                          217
#define STRINGID_ONEHITKO                             218
#define STRINGID_123POOF                              219
#define STRINGID_ANDELLIPSIS                          220
#define STRINGID_NOTVERYEFFECTIVE                     221
#define STRINGID_SUPEREFFECTIVE                       222
#define STRINGID_GOTAWAYSAFELY                        223
#define STRINGID_WILDPKMNFLED                         224
#define STRINGID_NORUNNINGFROMTRAINERS                225
#define STRINGID_CANTESCAPE                           226
#define STRINGID_DONTLEAVEBIRCH                       227
#define STRINGID_BUTNOTHINGHAPPENED                   228
#define STRINGID_BUTITFAILED                          229
#define STRINGID_ITHURTCONFUSION                      230
#define STRINGID_MIRRORMOVEFAILED                     231
#define STRINGID_STARTEDTORAIN                        232
#define STRINGID_DOWNPOURSTARTED                      233
#define STRINGID_RAINCONTINUES                        234
#define STRINGID_DOWNPOURCONTINUES                    235
#define STRINGID_RAINSTOPPED                          236
#define STRINGID_SANDSTORMBREWED                      237
#define STRINGID_SANDSTORMRAGES                       238
#define STRINGID_SANDSTORMSUBSIDED                    239
#define STRINGID_SUNLIGHTGOTBRIGHT                    240
#define STRINGID_SUNLIGHTSTRONG                       241
#define STRINGID_SUNLIGHTFADED                        242
#define STRINGID_STARTEDHAIL                          243
#define STRINGID_HAILCONTINUES                        244
#define STRINGID_HAILSTOPPED                          245
#define STRINGID_FAILEDTOSPITUP                       246
#define STRINGID_FAILEDTOSWALLOW                      247
#define STRINGID_WINDBECAMEHEATWAVE                   248
#define STRINGID_STATCHANGESGONE                      249
#define STRINGID_COINSSCATTERED                       250
#define STRINGID_TOOWEAKFORSUBSTITUTE                 251
#define STRINGID_SHAREDPAIN                           252
#define STRINGID_BELLCHIMED                           253
#define STRINGID_FAINTINTHREE                         254
#define STRINGID_NOPPLEFT                             255
#define STRINGID_BUTNOPPLEFT                          256
#define STRINGID_PLAYERUSEDITEM                       257
#define STRINGID_WALLYUSEDITEM                        258
#define STRINGID_TRAINERBLOCKEDBALL                   259
#define STRINGID_DONTBEATHIEF                         260
#define STRINGID_ITDODGEDBALL                         261
#define STRINGID_YOUMISSEDPKMN                        262
#define STRINGID_PKMNBROKEFREE                        263
#define STRINGID_ITAPPEAREDCAUGHT                     264
#define STRINGID_AARGHALMOSTHADIT                     265
#define STRINGID_SHOOTSOCLOSE                         266
#define STRINGID_GOTCHAPKMNCAUGHTPLAYER               267
#define STRINGID_GOTCHAPKMNCAUGHTWALLY                268
#define STRINGID_GIVENICKNAMECAPTURED                 269
#define STRINGID_PKMNSENTTOPC                         270
#define STRINGID_PKMNDATAADDEDTODEX                   271
#define STRINGID_ITISRAINING                          272
#define STRINGID_SANDSTORMISRAGING                    273
#define STRINGID_CANTESCAPE2                          274
#define STRINGID_PKMNIGNORESASLEEP                    275
#define STRINGID_PKMNIGNOREDORDERS                    276
#define STRINGID_PKMNBEGANTONAP                       277
#define STRINGID_PKMNLOAFING                          278
#define STRINGID_PKMNWONTOBEY                         279
#define STRINGID_PKMNTURNEDAWAY                       280
#define STRINGID_PKMNPRETENDNOTNOTICE                 281
#define STRINGID_ENEMYABOUTTOSWITCHPKMN               282
#define STRINGID_CREPTCLOSER                          283
#define STRINGID_CANTGETCLOSER                        284
#define STRINGID_PKMNWATCHINGCAREFULLY                285
#define STRINGID_PKMNCURIOUSABOUTX                    286
#define STRINGID_PKMNENTHRALLEDBYX                    287
#define STRINGID_PKMNIGNOREDX                         288
#define STRINGID_THREWPOKEBLOCKATPKMN                 289
#define STRINGID_OUTOFSAFARIBALLS                     290
#define STRINGID_PKMNSITEMCUREDPARALYSIS              291
#define STRINGID_PKMNSITEMCUREDPOISON                 292
#define STRINGID_PKMNSITEMHEALEDBURN                  293
#define STRINGID_PKMNSITEMDEFROSTEDIT                 294
#define STRINGID_PKMNSITEMWOKEIT                      295
#define STRINGID_PKMNSITEMSNAPPEDOUT                  296
#define STRINGID_PKMNSITEMCUREDPROBLEM                297
#define STRINGID_PKMNSITEMRESTOREDHEALTH              298
#define STRINGID_PKMNSITEMRESTOREDPP                  299
#define STRINGID_PKMNSITEMRESTOREDSTATUS              300
#define STRINGID_PKMNSITEMRESTOREDHPALITTLE           301
#define STRINGID_ITEMALLOWSONLYYMOVE                  302
#define STRINGID_PKMNHUNGONWITHX                      303
#define STRINGID_EMPTYSTRING3                         304
#define STRINGID_PKMNSXPREVENTSBURNS                  305
#define STRINGID_PKMNSXBLOCKSY                        306
#define STRINGID_PKMNSXRESTOREDHPALITTLE2             307
#define STRINGID_PKMNSXWHIPPEDUPSANDSTORM             308
#define STRINGID_PKMNSXPREVENTSYLOSS                  309
#define STRINGID_PKMNSXINFATUATEDY                    310
#define STRINGID_PKMNSXMADEYINEFFECTIVE               311
#define STRINGID_PKMNSXCUREDYPROBLEM                  312
#define STRINGID_ITSUCKEDLIQUIDOOZE                   313
#define STRINGID_PKMNTRANSFORMED                      314
#define STRINGID_ELECTRICITYWEAKENED                  315
#define STRINGID_FIREWEAKENED                         316
#define STRINGID_PKMNHIDUNDERWATER                    317
#define STRINGID_PKMNSPRANGUP                         318
#define STRINGID_HMMOVESCANTBEFORGOTTEN               319
#define STRINGID_XFOUNDONEY                           320
#define STRINGID_PLAYERDEFEATEDTRAINER1               321
#define STRINGID_SOOTHINGAROMA                        322
#define STRINGID_ITEMSCANTBEUSEDNOW                   323
#define STRINGID_FORXCOMMAYZ                          324
#define STRINGID_USINGITEMSTATOFPKMNROSE              325
#define STRINGID_PKMNUSEDXTOGETPUMPED                 326
#define STRINGID_PKMNSXMADEYUSELESS                   327
#define STRINGID_PKMNTRAPPEDBYSANDTOMB                328
#define STRINGID_EMPTYSTRING4                         329
#define STRINGID_ABOOSTED                             330
#define STRINGID_PKMNSXINTENSIFIEDSUN                 331
#define STRINGID_PKMNMAKESGROUNDMISS                  332
#define STRINGID_YOUTHROWABALLNOWRIGHT                333
#define STRINGID_PKMNSXTOOKATTACK                     334
#define STRINGID_PKMNCHOSEXASDESTINY                  335
#define STRINGID_PKMNLOSTFOCUS                        336
#define STRINGID_USENEXTPKMN                          337
#define STRINGID_PKMNFLEDUSINGITS                     338
#define STRINGID_PKMNFLEDUSING                        339
#define STRINGID_PKMNWASDRAGGEDOUT                    340
#define STRINGID_PREVENTEDFROMWORKING                 341
#define STRINGID_PKMNSITEMNORMALIZEDSTATUS            342
#define STRINGID_TRAINER1USEDITEM                     343
#define STRINGID_BOXISFULL                            344
#define STRINGID_PKMNAVOIDEDATTACK                    345
#define STRINGID_PKMNSXMADEITINEFFECTIVE              346
#define STRINGID_PKMNSXPREVENTSFLINCHING              347
#define STRINGID_PKMNALREADYHASBURN                   348
#define STRINGID_STATSWONTDECREASE2                   349
#define STRINGID_PKMNSXBLOCKSY2                       350
#define STRINGID_PKMNSXWOREOFF                        351
#define STRINGID_PKMNRAISEDDEFALITTLE                 352
#define STRINGID_PKMNRAISEDSPDEFALITTLE               353
#define STRINGID_THEWALLSHATTERED                     354
#define STRINGID_PKMNSXPREVENTSYSZ                    355
#define STRINGID_PKMNSXCUREDITSYPROBLEM               356
#define STRINGID_ATTACKERCANTESCAPE                   357
#define STRINGID_PKMNOBTAINEDX                        358
#define STRINGID_PKMNOBTAINEDX2                       359
#define STRINGID_PKMNOBTAINEDXYOBTAINEDZ              360
#define STRINGID_BUTNOEFFECT                          361
#define STRINGID_PKMNSXHADNOEFFECTONY                 362
#define STRINGID_TWOENEMIESDEFEATED                   363
#define STRINGID_TRAINER2LOSETEXT                     364
#define STRINGID_PKMNINCAPABLEOFPOWER                 365
#define STRINGID_GLINTAPPEARSINEYE                    366
#define STRINGID_PKMNGETTINGINTOPOSITION              367
#define STRINGID_PKMNBEGANGROWLINGDEEPLY              368
#define STRINGID_PKMNEAGERFORMORE                     369
#define STRINGID_DEFEATEDOPPONENTBYREFEREE            370
#define STRINGID_LOSTTOOPPONENTBYREFEREE              371
#define STRINGID_TIEDOPPONENTBYREFEREE                372
#define STRINGID_QUESTIONFORFEITMATCH                 373
#define STRINGID_FORFEITEDMATCH                       374
#define STRINGID_PKMNTRANSFERREDSOMEONESPC            375
#define STRINGID_PKMNTRANSFERREDLANETTESPC            376
#define STRINGID_PKMNBOXSOMEONESPCFULL                377
#define STRINGID_PKMNBOXLANETTESPCFULL                378
#define STRINGID_TRAINER1WINTEXT                      379
#define STRINGID_TRAINER2WINTEXT                      380

#define STRINGID_ENDUREDSTURDY                        381
#define STRINGID_POWERHERB                            382
#define STRINGID_HURTBYITEM                           383
#define STRINGID_PSNBYITEM                            384
#define STRINGID_BRNBYITEM                            385
#define STRINGID_DEFABILITYIN                         386
#define STRINGID_GRAVITYINTENSIFIED                   387
#define STRINGID_TARGETIDENTIFIED                     388
#define STRINGID_TARGETWOKEUP                         389
#define STRINGID_PKMNSTOLEANDATEITEM                  390
#define STRINGID_TAILWINDBLEW                         391
#define STRINGID_PKMNWENTBACK                         392
#define STRINGID_PKMNCANTUSEITEMSANYMORE              393
#define STRINGID_PKMNFLUNG                            394
#define STRINGID_PKMNPREVENTEDFROMHEALING             395
#define STRINGID_PKMNSWITCHEDATKANDDEF                396
#define STRINGID_PKMNSABILITYSUPPRESSED               397
#define STRINGID_SHIELDEDFROMCRITICALHITS             398
#define STRINGID_SWITCHEDATKANDSPATK                  399
#define STRINGID_SWITCHEDDEFANDSPDEF                  400
#define STRINGID_PKMNACQUIREDABILITY                  401
#define STRINGID_POISONSPIKESSCATTERED                402
#define STRINGID_PKMNSWITCHEDSTATCHANGES              403
#define STRINGID_PKMNSURROUNDEDWITHVEILOFWATER        404
#define STRINGID_PKMNLEVITATEDONELECTROMAGNETISM      405
#define STRINGID_PKMNTWISTEDDIMENSIONS                406
#define STRINGID_POINTEDSTONESFLOAT                   407
#define STRINGID_CLOAKEDINMYSTICALMOONLIGHT           408
#define STRINGID_TRAPPEDBYSWIRLINGMAGMA               409
#define STRINGID_VANISHEDINSTANTLY                    410
#define STRINGID_PROTECTEDTEAM                        411
#define STRINGID_SHAREDITSGUARD                       412
#define STRINGID_SHAREDITSPOWER                       413
#define STRINGID_SWAPSDEFANDSPDEFOFALLPOKEMON         414
#define STRINGID_BECAMENIMBLE                         415
#define STRINGID_HURLEDINTOTHEAIR                     416
#define STRINGID_HELDITEMSLOSEEFFECTS                 417
#define STRINGID_FELLSTRAIGHTDOWN                     418
#define STRINGID_TARGETCHANGEDTYPE                    419
#define STRINGID_PKMNACQUIREDSIMPLE                   420
#define STRINGID_EMPTYSTRING5                         421
#define STRINGID_KINDOFFER                            422
#define STRINGID_RESETSTARGETSSTATLEVELS              423
#define STRINGID_EMPTYSTRING6                         424
#define STRINGID_ALLYSWITCHPOSITION                   425
#define STRINGID_RESTORETARGETSHEALTH                 426
#define STRINGID_TOOKPJMNINTOTHESKY                   427
#define STRINGID_FREEDFROMSKYDROP                     428
#define STRINGID_POSTPONETARGETMOVE                   429
#define STRINGID_REFLECTTARGETSTYPE                   430
#define STRINGID_TRANSFERHELDITEM                     431
#define STRINGID_EMBARGOENDS                          432
#define STRINGID_ELECTROMAGNETISM                     433
#define STRINGID_BUFFERENDS                           434
#define STRINGID_TELEKINESISENDS                      435
#define STRINGID_TAILWINDENDS                         436
#define STRINGID_LUCKYCHANTENDS                       437
#define STRINGID_TRICKROOMENDS                        438
#define STRINGID_WONDERROOMENDS                       439
#define STRINGID_MAGICROOMENDS                        440
#define STRINGID_MUDSPORTENDS                         441
#define STRINGID_WATERSPORTENDS                       442
#define STRINGID_GRAVITYENDS                          443
#define STRINGID_AQUARINGHEAL                         444
#define STRINGID_AURORAVEILENDS                       445
#define STRINGID_ELECTRICTERRAINENDS                  446
#define STRINGID_MISTYTERRAINENDS                     447
#define STRINGID_PSYCHICTERRAINENDS                   448
#define STRINGID_GRASSYTERRAINENDS                    449
#define STRINGID_TARGETABILITYSTATRAISE               450
#define STRINGID_TARGETSSTATWASMAXEDOUT               451
#define STRINGID_ATTACKERABILITYSTATRAISE             452
#define STRINGID_POISONHEALHPUP                       453
#define STRINGID_BADDREAMSDMG                         454
#define STRINGID_MOLDBREAKERENTERS                    455
#define STRINGID_TERAVOLTENTERS                       456
#define STRINGID_TURBOBLAZEENTERS                     457
#define STRINGID_SLOWSTARTENTERS                      458
#define STRINGID_SLOWSTARTEND                         459
#define STRINGID_SOLARPOWERHPDROP                     460
#define STRINGID_AFTERMATHDMG                         461
#define STRINGID_ANTICIPATIONACTIVATES                462
#define STRINGID_FOREWARNACTIVATES                    463
#define STRINGID_ICEBODYHPGAIN                        464
#define STRINGID_SNOWWARNINGHAIL                      465
#define STRINGID_FRISKACTIVATES                       466
#define STRINGID_UNNERVEENTERS                        467
#define STRINGID_HARVESTBERRY                         468
#define STRINGID_LASTABILITYRAISEDSTAT                469
#define STRINGID_MAGICBOUNCEACTIVATES                 470
#define STRINGID_PROTEANTYPECHANGE                    471
#define STRINGID_SYMBIOSISITEMPASS                    472
#define STRINGID_STEALTHROCKDMG                       473
#define STRINGID_TOXICSPIKESABSORBED                  474
#define STRINGID_TOXICSPIKESPOISONED                  475
#define STRINGID_STICKYWEBSWITCHIN                    476
#define STRINGID_HEALINGWISHCAMETRUE                  477
#define STRINGID_HEALINGWISHHEALED                    478
#define STRINGID_LUNARDANCECAMETRUE                   479
#define STRINGID_CUSEDBODYDISABLED                    480
#define STRINGID_ATTACKERACQUIREDABILITY              481
#define STRINGID_TARGETABILITYSTATLOWER               482
#define STRINGID_TARGETSTATWONTGOHIGHER               483
#define STRINGID_PKMNMOVEBOUNCEDABILITY               484
#define STRINGID_IMPOSTERTRANSFORM                    485
#define STRINGID_ASSAULTVESTDOESNTALLOW               486
#define STRINGID_GRAVITYPREVENTSUSAGE                 487
#define STRINGID_HEALBLOCKPREVENTSUSAGE               488
#define STRINGID_NOTDONEYET                           489
#define STRINGID_STICKYWEBUSED                        490
#define STRINGID_QUASHSUCCESS                         491
#define	STRINGID_PKMNBLEWAWAYTOXICSPIKES              492
#define	STRINGID_PKMNBLEWAWAYSTICKYWEB                493
#define	STRINGID_PKMNBLEWAWAYSTEALTHROCK              494
#define	STRINGID_IONDELUGEON                          495
#define	STRINGID_TOPSYTURVYSWITCHEDSTATS              496
#define	STRINGID_TERRAINBECOMESMISTY                  497
#define	STRINGID_TERRAINBECOMESGRASSY                 498
#define	STRINGID_TERRAINBECOMESELECTRIC               499
#define	STRINGID_TERRAINBECOMESPSYCHIC                500
#define	STRINGID_TARGETELECTRIFIED                    501
#define	STRINGID_MEGAEVOREACTING                      502
#define	STRINGID_MEGAEVOEVOLVED                       503
#define	STRINGID_DRASTICALLY                          504
#define	STRINGID_SEVERELY                             505
#define	STRINGID_INFESTATION                          506
#define	STRINGID_NOEFFECTONTARGET                     507
#define	STRINGID_BURSTINGFLAMESHIT                    508
#define	STRINGID_BESTOWITEMGIVING                     509
#define	STRINGID_THIRDTYPEADDED                       510
#define STRINGID_FELLFORFEINT                         511
#define STRINGID_POKEMONCANNOTUSEMOVE                 512
#define STRINGID_COVEREDINPOWDER                      513
#define STRINGID_POWDEREXPLODES                       514
#define STRINGID_BELCHCANTSELECT                      515
#define STRINGID_SPECTRALTHIEFSTEAL                   516
#define STRINGID_GRAVITYGROUNDING                     517
#define STRINGID_MISTYTERRAINPREVENTS                 518
#define STRINGID_GRASSYTERRAINHEALS                   519
#define STRINGID_ELECTRICTERRAINPREVENTS              520
#define STRINGID_PSYCHICTERRAINPREVENTS               521
#define STRINGID_SAFETYGOGGLESPROTECTED               522
#define STRINGID_FLOWERVEILPROTECTED                  523
#define STRINGID_SWEETVEILPROTECTED                   524
#define STRINGID_AROMAVEILPROTECTED                   525
#define STRINGID_CELEBRATEMESSAGE                     526
#define STRINGID_USEDINSTRUCTEDMOVE                   527
#define STRINGID_THROATCHOPENDS                       528
#define STRINGID_PKMNCANTUSEMOVETHROATCHOP            529
#define STRINGID_LASERFOCUS                           530
#define STRINGID_GEMACTIVATES                         531
#define STRINGID_BERRYDMGREDUCES                      532
#define STRINGID_TARGETATEITEM                        533
#define STRINGID_AIRBALLOONFLOAT                      534
#define STRINGID_AIRBALLOONPOP                        535
#define STRINGID_INCINERATEBURN                       536
#define STRINGID_BUGBITE                              537
#define STRINGID_ILLUSIONWOREOFF                      538
#define STRINGID_ATTACKERCUREDTARGETSTATUS            539
#define STRINGID_ATTACKERLOSTFIRETYPE                 540
#define STRINGID_HEALERCURE                           541
#define STRINGID_SCRIPTINGABILITYSTATRAISE            542
#define STRINGID_RECEIVERABILITYTAKEOVER              543
#define STRINGID_PKNMABSORBINGPOWER                   544
#define STRINGID_NOONEWILLBEABLETORUNAWAY             545
#define STRINGID_DESTINYKNOTACTIVATES                 546
#define STRINGID_CLOAKEDINAFREEZINGLIGHT              547
#define STRINGID_STATWASNOTLOWERED                    548
#define STRINGID_FERVENTWISHREACHED                   549
#define STRINGID_AIRLOCKACTIVATES                     550
#define STRINGID_PRESSUREENTERS                       551
#define STRINGID_DARKAURAENTERS                       552
#define STRINGID_FAIRYAURAENTERS                      553
#define STRINGID_AURABREAKENTERS                      554
#define STRINGID_COMATOSEENTERS                       555
#define STRINGID_SCREENCLEANERENTERS                  556
#define STRINGID_FETCHEDPOKEBALL                      557
#define STRINGID_BATTLERABILITYRAISEDSTAT             558
#define STRINGID_ASANDSTORMKICKEDUP                   559
#define STRINGID_PKMNSWILLPERISHIN3TURNS              560
#define STRINGID_ABILITYRAISEDSTATDRASTICALLY         561
#define STRINGID_AURAFLAREDTOLIFE                     562
#define STRINGID_ASONEENTERS                          563
#define STRINGID_CURIOUSMEDICINEENTERS                564
#define STRINGID_CANACTFASTERTHANKSTO                 565
#define STRINGID_MICLEBERRYACTIVATES                  566
#define STRINGID_PKMNSHOOKOFFTHETAUNT                 567
#define STRINGID_PKMNGOTOVERITSINFATUATION            568
#define STRINGID_ITEMCANNOTBEREMOVED                  569
#define STRINGID_STICKYBARBTRANSFER                   570
#define STRINGID_PKMNBURNHEALED                       571
#define STRINGID_REDCARDACTIVATE                      572
#define STRINGID_EJECTBUTTONACTIVATE                  573
#define STRINGID_ATKGOTOVERINFATUATION                574
#define STRINGID_TORMENTEDNOMORE                      575
#define STRINGID_HEALBLOCKEDNOMORE                    576
#define STRINGID_ATTACKERBECAMEFULLYCHARGED           577
#define STRINGID_ATTACKERBECAMEASHSPECIES             578
#define STRINGID_EXTREMELYHARSHSUNLIGHT               579
#define STRINGID_EXTREMESUNLIGHTFADED                 580
#define STRINGID_MOVEEVAPORATEDINTHEHARSHSUNLIGHT     581
#define STRINGID_EXTREMELYHARSHSUNLIGHTWASNOTLESSENED 582
#define STRINGID_HEAVYRAIN                            583
#define STRINGID_HEAVYRAINLIFTED                      584
#define STRINGID_MOVEFIZZLEDOUTINTHEHEAVYRAIN         585
#define STRINGID_NORELIEFROMHEAVYRAIN                 586
#define STRINGID_MYSTERIOUSAIRCURRENT                 587
#define STRINGID_STRONGWINDSDISSIPATED                588
#define STRINGID_MYSTERIOUSAIRCURRENTBLOWSON          589
#define STRINGID_ATTACKWEAKENEDBSTRONGWINDS           590
#define STRINGID_STUFFCHEEKSCANTSELECT                591
#define STRINGID_PKMNREVERTEDTOPRIMAL                 592
#define STRINGID_BUTPOKEMONCANTUSETHEMOVE             593
#define STRINGID_BUTHOOPACANTUSEIT                    594
#define STRINGID_BROKETHROUGHPROTECTION               595
#define STRINGID_ABILITYALLOWSONLYMOVE                596
#define STRINGID_SWAPPEDABILITIES                     597
#define STRINGID_PASTELVEILPROTECTED                  598
#define STRINGID_PASTELVEILENTERS                     599
#define STRINGID_BATTLERTYPECHANGEDTO                 600
#define STRINGID_BOTHCANNOLONGERESCAPE                601
#define STRINGID_CANTESCAPEDUETOUSEDMOVE              602
#define STRINGID_PKMNBECAMEWEAKERTOFIRE               603
#define STRINGID_ABOUTTOUSEPOLTERGEIST                604
#define STRINGID_CANTESCAPEBECAUSEOFCURRENTMOVE       605
#define STRINGID_NEUTRALIZINGGASENTERS                606
#define STRINGID_NEUTRALIZINGGASOVER                  607
#define STRINGID_TARGETTOOHEAVY                       608
#define STRINGID_PKMNTOOKTARGETHIGH                   609
#define STRINGID_PKMNINSNAPTRAP                       610
#define STRINGID_METEORBEAMCHARGING                   611
#define STRINGID_HEATUPBEAK                           612
#define STRINGID_COURTCHANGE                          613
#define STRINGID_PLAYERLOSTTOENEMYTRAINER             614
#define STRINGID_PLAYERPAIDPRIZEMONEY                 615
#define STRINGID_ZPOWERSURROUNDS                      616
#define STRINGID_ZMOVEUNLEASHED                       617
#define STRINGID_ZMOVERESETSSTATS                     618
#define STRINGID_ZMOVEALLSTATSUP                      619
#define STRINGID_ZMOVEZBOOSTCRIT                      620
#define STRINGID_ZMOVERESTOREHP                       621
#define STRINGID_ZMOVESTATUP                          622
#define STRINGID_ZMOVEHPTRAP                          623
#define STRINGID_TERRAINREMOVED                       624
#define STRINGID_ATTACKEREXPELLEDTHEPOISON            625
#define STRINGID_ATTACKERSHOOKITSELFAWAKE             626
#define STRINGID_ATTACKERBROKETHROUGHPARALYSIS        627
#define STRINGID_ATTACKERHEALEDITSBURN                628
#define STRINGID_ATTACKERMELTEDTHEICE                 629
#define STRINGID_TARGETTOUGHEDITOUT                   630
#define STRINGID_ATTACKERLOSTELECTRICTYPE             631
#define STRINGID_ATTACKERSWITCHEDSTATWITHTARGET       632
#define STRINGID_BEINGHITCHARGEDPKMNWITHPOWER         633
#define STRINGID_SUNLIGHTACTIVATEDABILITY             634
#define STRINGID_STATWASHEIGHTENED                    635
#define STRINGID_ELECTRICTERRAINACTIVATEDABILITY      636
#define STRINGID_ABILITYWEAKENEDFSURROUNDINGMONSSTAT  637
#define STRINGID_ATTACKERGAINEDSTRENGTHFROMTHEFALLEN  638
#define STRINGID_PKMNSABILITYPREVENTSABILITY          639
#define STRINGID_PREPARESHELLTRAP                     640
#define STRINGID_SHELLTRAPDIDNTWORK                   641
#define STRINGID_SPIKESDISAPPEAREDFROMTEAM            642
#define STRINGID_TOXICSPIKESDISAPPEAREDFROMTEAM       643
#define STRINGID_STICKYWEBDISAPPEAREDFROMTEAM         644
#define STRINGID_STEALTHROCKDISAPPEAREDFROMTEAM       645
#define STRINGID_COULDNTFULLYPROTECT                  646
#define STRINGID_STOCKPILEDEFFECTWOREOFF              647
#define STRINGID_STARTEDACIDRAIN                      648
#define STRINGID_ACIDRAINCONTINUES                    649
#define STRINGID_ACIDRAINSTOPPED                      650
#define STRINGID_MOONLIGHTGOTBRIGHT                   651
#define STRINGID_MOONLIGHTSTRONG                      652
#define STRINGID_MOONLIGHTFADED                       653

#define STRINGID_PKMNWASINFECTED                      654
#define STRINGID_PKMNINFECTEDBY                       655
#define STRINGID_PKMNWASDAZED                         656
#define STRINGID_PKMNDAZEDBY                          657
#define STRINGID_PKMNGOTOVERDAZE                      658
#define STRINGID_PKMNWASEXHAUSTED                     659
#define STRINGID_PKMNEXHAUSTEDBY                      660
#define STRINGID_PKMNBECAMEAFRAID                     661
#define STRINGID_PKMNAFRAIDOF                         662

#define STRINGID_PKMNINFECTPREVENTSHEAL               663
#define STRINGID_PKMNISDAZED                          664
#define STRINGID_PKMNEXHAUSTPP                        665
#define STRINGID_PKMNISAFRAID                         666

#define STRINGID_PKMNPREVENTSINFECTIONWITH            667
#define STRINGID_PKMNPREVENTSDAZEWITH                 668
#define STRINGID_PKMNPREVENTSEXHAUSTIONWITH           669
#define STRINGID_PKMNPREVENTSFEARWITH                 670

#define STRINGID_PKMNALREADYINFECTED                  671
#define STRINGID_PKMNALREADYDAZED                     672
#define STRINGID_PKMNALREADYEXHAUSTED                 673
#define STRINGID_PKMNALREADYAFRAID                    674

#define STRINGID_PKMNSITEMDISINFECTED                 675
#define STRINGID_PKMNSITEMCUREDDAZE                   676
#define STRINGID_PKMNSITEMINVIGORATED                 677
#define STRINGID_PKMNSITEMCUREDFEAR                   678

#define STRINGID_TOXICFUMESACIDRAIN                   679
#define STRINGID_ECLIPSEFULLMOON                      680

#define STRINGID_PKMNSPIRITROSE                       681
#define STRINGID_PKMNINFECTDAMAGE                     682
#define STRINGID_PKMNCUTSSPATTACKWITH                 683
#define STRINGID_RADIATIONDMG                         684

#define STRINGID_PLAYERWHITEOUT3                      685

#define STRINGID_PKMNBREATHEDINSMAZE                  686
#define STRINGID_PKMNGLOWEDMOONLIGHT                  687

#define STRINGID_MYSTERIOUSDUSTFLOATS                 688
#define STRINGID_FAIRYDUSTDMG                         689
#define STRINGID_PKMNBLEWAWAYFAIRYDUST                690
#define STRINGID_FAIRYDUSTDISAPPEAREDFROMTEAM         691

#define STRINGID_PKMNRAISEDACC                        692
#define STRINGID_PKMNTOOKMOONLIGHT                    693

#define STRINGID_STEALTHROCKSABSORBED                 694

#define BATTLESTRINGS_COUNT                           695

// This is the string id that gBattleStringsTable starts with.
// String ids before this (e.g. STRINGID_INTROMSG) are not in the table,
// and are instead handled explicitly by BufferStringBattle.
#define BATTLESTRINGS_TABLE_START  STRINGID_TRAINER1LOSETEXT
>>>>>>> Stashed changes

// The below IDs are all indexes into battle message tables,
// used to determine which of a set of messages to print.
// They are assigned to the MULTISTRING_CHOOSER byte of gBattleCommunication
// and read when e.g. the command printfromtable is used.

// gStatUpStringIds and gStatDownStringIds
enum StatChangedStringID
{
    B_MSG_ATTACKER_STAT_CHANGED,
    B_MSG_DEFENDER_STAT_CHANGED,
    B_MSG_STAT_WONT_CHANGE,
    B_MSG_STAT_CHANGE_EMPTY,
    B_MSG_STAT_CHANGED_ITEM,
    B_MSG_USED_DIRE_HIT,
};

// gMissStringIds
enum MissStringID
{
    B_MSG_MISSED,
    B_MSG_PROTECTED,
    B_MSG_AVOIDED_ATK,
};

// gAbsorbDrainStringIds
enum AbsorbDrainStringID
{
    B_MSG_ABSORB,
    B_MSG_ABSORB_OOZE,
};

// gLeechSeedStringIds
<<<<<<< Updated upstream
enum LeechSeedStringID
{
    B_MSG_LEECH_SEED_SET,
    B_MSG_LEECH_SEED_MISS,
    B_MSG_LEECH_SEED_FAIL,
    B_MSG_LEECH_SEED_DRAIN,
    B_MSG_LEECH_SEED_OOZE,
};

// gMoveWeatherChangeStringIds
enum MoveWeatherChangeStringID
{
    B_MSG_STARTED_RAIN,
    B_MSG_STARTED_DOWNPOUR,
    B_MSG_WEATHER_FAILED,
    B_MSG_STARTED_SANDSTORM,
    B_MSG_STARTED_SUNLIGHT,
    B_MSG_STARTED_HAIL,
    B_MSG_STARTED_SNOW,
    B_MSG_STARTED_FOG,
};
=======
#define B_MSG_LEECH_SEED_SET   0
#define B_MSG_LEECH_SEED_MISS  1
#define B_MSG_LEECH_SEED_FAIL  2
#define B_MSG_LEECH_SEED_DRAIN 3
#define B_MSG_LEECH_SEED_OOZE  4

// gFirstTurnOfTwoStringIds
#define B_MSG_TURN1_RAZOR_WIND     0
#define B_MSG_TURN1_SOLAR_BEAM     1
#define B_MSG_TURN1_SKULL_BASH     2
#define B_MSG_TURN1_SKY_ATTACK     3
#define B_MSG_TURN1_FLY            4
#define B_MSG_TURN1_DIG            5
#define B_MSG_TURN1_DIVE           6
#define B_MSG_TURN1_BOUNCE         7
#define B_MSG_TURN1_PHANTOM_FORCE  8
#define B_MSG_TURN1_GEOMANCY       9
#define B_MSG_TURN1_FREEZE_SHOCK   10
#define B_MSG_TURN1_SKY_DROP       11
#define B_MSG_TURN1_METEOR_BEAM    12
#define B_MSG_TURN1_MOONBLAST      13

// gMoveWeatherChangeStringIds
#define B_MSG_STARTED_RAIN      0
#define B_MSG_STARTED_DOWNPOUR  1
#define B_MSG_WEATHER_FAILED    2
#define B_MSG_STARTED_SANDSTORM 3
#define B_MSG_STARTED_SUNLIGHT  4
#define B_MSG_STARTED_HAIL      5
#define B_MSG_STARTED_ACIDRAIN  6
#define B_MSG_STARTED_FULLMOON  7
>>>>>>> Stashed changes

// gAbilityWeatherChangeStringId
enum AbilityWeatherChangeStringID
{
    B_MSG_STARTED_DRIZZLE,
    B_MSG_STARTED_SAND_STREAM,
    B_MSG_STARTED_DROUGHT,
    B_MSG_STARTED_HAIL_WARNING,
    B_MSG_STARTED_SNOW_WARNING,
    B_MSG_STARTED_DESOLATE_LAND,
    B_MSG_STARTED_PRIMORDIAL_SEA,
    B_MSG_STARTED_STRONG_WINDS,
};

// gWeatherEndsStringIds
enum WeatherEndStringID
{
    B_MSG_WEATHER_END_RAIN,
    B_MSG_WEATHER_END_SUN,
    B_MSG_WEATHER_END_SANDSTORM,
    B_MSG_WEATHER_END_HAIL,
    B_MSG_WEATHER_END_SNOW,
    B_MSG_WEATHER_END_FOG,
    B_MSG_WEATHER_END_STRONG_WINDS,
    B_MSG_WEATHER_END_COUNT
};

<<<<<<< Updated upstream
// gWeatherTurnStringIds
enum WeatherTurnStringID
{
    B_MSG_WEATHER_TURN_RAIN,
    B_MSG_WEATHER_TURN_DOWNPOUR,
    B_MSG_WEATHER_TURN_SUN,
    B_MSG_WEATHER_TURN_SANDSTORM,
    B_MSG_WEATHER_TURN_HAIL,
    B_MSG_WEATHER_TURN_SNOW,
    B_MSG_WEATHER_TURN_FOG,
    B_MSG_WEATHER_TURN_STRONG_WINDS,
};

// gSandStormHailSnowContinuesStringIds / gSandStormHailDmgStringIds/ gSandStormHailSnowEndStringIds
enum SandstormHailSnowStringID
{
    B_MSG_SANDSTORM,
    B_MSG_HAIL,
};
=======
// gSandStormHailContinuesStringIds / gSandStormHailDmgStringIds/ gSandStormHailEndStringIds
#define B_MSG_SANDSTORM  0
#define B_MSG_HAIL       1
#define B_MSG_ACIDRAIN   2
#define B_MSG_FULLMOON   3
>>>>>>> Stashed changes

// gReflectLightScreenSafeguardStringIds
enum ReflectLightScreenSafeguardStringID
{
    B_MSG_SIDE_STATUS_FAILED,
    B_MSG_SET_REFLECT_SINGLE,
    B_MSG_SET_REFLECT_DOUBLE,
    B_MSG_SET_LIGHTSCREEN_SINGLE,
    B_MSG_SET_LIGHTSCREEN_DOUBLE,
    B_MSG_SET_SAFEGUARD,
};

// gProtectLikeUsedStringIds
enum ProtectLikeUsedStringID
{
    B_MSG_PROTECTED_ITSELF,
    B_MSG_BRACED_ITSELF,
    B_MSG_PROTECTED_TEAM,
};

// gRestUsedStringIds
enum RestUsedStringID
{
    B_MSG_REST,
    B_MSG_REST_STATUSED,
};

// gWokeUpStringIds
enum WokeUpStringID
{
    B_MSG_WOKE_UP,
    B_MSG_WOKE_UP_UPROAR,
};

// gUproarAwakeStringIds
enum UproarAwakeStringID
{
    B_MSG_CANT_SLEEP_UPROAR,
    B_MSG_UPROAR_KEPT_AWAKE,
};

// gUproarOverTurnStringIds
enum UproarOverTurnStringID
{
    B_MSG_UPROAR_CONTINUES,
    B_MSG_UPROAR_ENDS,
};

// gKOFailedStringIds
enum KOFailedStringID
{
    B_MSG_KO_MISS,
    B_MSG_KO_UNAFFECTED,
};

// gMistUsedStringIds
enum MistUsedStringID
{
    B_MSG_SET_MIST,
    B_MSG_MIST_FAILED,
};

// gFocusEnergyUsedStringIds
enum FocusEnergyUsedStringID
{
    B_MSG_GETTING_PUMPED,
    B_MSG_FOCUS_ENERGY_FAILED,
};

// gTransformUsedStringIds
enum TransformUsedStringID
{
    B_MSG_TRANSFORMED,
    B_MSG_TRANSFORM_FAILED,
};

// gSubstituteUsedStringIds
enum SubstituteUsedStringID
{
    B_MSG_SET_SUBSTITUTE,
    B_MSG_SUBSTITUTE_FAILED,
};

// gPartyStatusHealStringIds
enum PartyStatusHealStringID
{
    B_MSG_BELL,
    B_MSG_BELL_SOUNDPROOF_ATTACKER,
    B_MSG_BELL_SOUNDPROOF_PARTNER,
    B_MSG_BELL_BOTH_SOUNDPROOF,
    B_MSG_SOOTHING_AROMA,
};

// gFutureMoveUsedStringIds
enum FutureMoveUsedStringID
{
    B_MSG_FUTURE_SIGHT,
    B_MSG_DOOM_DESIRE,
};

// gItemSwapStringIds
enum ItemSwapStringID
{
    B_MSG_ITEM_SWAP_TAKEN,
    B_MSG_ITEM_SWAP_GIVEN,
    B_MSG_ITEM_SWAP_BOTH,
};

// gSportsUsedStringIds
enum SportsUsedStringID
{
    B_MSG_WEAKEN_ELECTRIC,
    B_MSG_WEAKEN_FIRE,
};

// gCaughtMonStringIds
enum CaughtMonStringID
{
    B_MSG_NO_MESSSAGE_SKIP,
    // "Lanette's" should always follow "someone's"
    B_MSG_SENT_SOMEONES_PC,
    B_MSG_SENT_LANETTES_PC,
    B_MSG_SOMEONES_BOX_FULL,
    B_MSG_LANETTES_BOX_FULL,
    B_MSG_SWAPPED_INTO_PARTY,
};

// gPrimalWeatherBlocksStringIds
enum PrimalWeatherBlockStringID
{
    B_MSG_PRIMAL_WEATHER_FIZZLED_BY_RAIN,
    B_MSG_PRIMAL_WEATHER_EVAPORATED_IN_SUN,
};

// gInobedientStringIds
enum InobedientStringID
{
    B_MSG_LOAFING,
    B_MSG_WONT_OBEY,
    B_MSG_TURNED_AWAY,
    B_MSG_PRETEND_NOT_NOTICE,
    B_MSG_INCAPABLE_OF_POWER,
};

// For randomly selecting a disobey string
// Skips the one used for Battle Palace
#define NUM_LOAF_STRINGS (B_MSG_PRETEND_NOT_NOTICE + 1)

// gSafariReactionStringIds
enum SafariReactionStringID
{
    B_MSG_MON_WATCHING,
    B_MSG_MON_ANGRY,
    B_MSG_MON_EATING,
    NUM_SAFARI_REACTIONS
};

// gSafariGetNearStringIds
enum SafariGetNearStringID
{
    B_MSG_CREPT_CLOSER,
    B_MSG_CANT_GET_CLOSER,
};

// gSafariPokeblockResultStringIds
enum SafariPokeblockResultStringID
{
    B_MSG_MON_CURIOUS,
    B_MSG_MON_ENTHRALLED,
    B_MSG_MON_IGNORED,
};

// gFlashFireStringIds
enum FlashFireStringID
{
    B_MSG_FLASH_FIRE_BOOST,
    B_MSG_FLASH_FIRE_NO_BOOST,
};

// CureStatusBerryEffectStringID
enum CureStatusBerryEffectStringID
{
    B_MSG_CURED_PARALYSIS,
    B_MSG_CURED_POISON,
    B_MSG_CURED_BURN,
    B_MSG_CURED_FREEEZE,
    B_MSG_CURED_FROSTBITE,
    B_MSG_CURED_SLEEP,
    B_MSG_CURED_PROBLEM,
    B_MSG_NORMALIZED_STATUS,
};

// gNoEscapeStringIds
enum NoEscapeStringID
{
    B_MSG_CANT_ESCAPE,
    B_MSG_DONT_LEAVE_BIRCH,
    B_MSG_PREVENTS_ESCAPE,
    B_MSG_CANT_ESCAPE_2,
    B_MSG_ATTACKER_CANT_ESCAPE,
};

// gGotPoisonedStringIds / gGotParalyzedStringIds / gFellAsleepStringIds
// gGotBurnedStringIds / gGotFrozenStringIds / gAttractUsedStringIds
<<<<<<< Updated upstream
enum GotStatusedStringID
{
    B_MSG_STATUSED,
    B_MSG_STATUSED_BY_ABILITY,
};
=======
#define B_MSG_STATUSED            0
#define B_MSG_STATUSED_BY_ABILITY 1

// gBRNPreventionStringIds / gPRLZPreventionStringIds / gPSNPreventionStringIds / gINFPreventionStringIds / gDAZPreventionStringIds / gEXHPreventionStringIds / gFERPreventionStringIds
#define B_MSG_ABILITY_PREVENTS_MOVE_STATUS    0
#define B_MSG_ABILITY_PREVENTS_ABILITY_STATUS 1
#define B_MSG_STATUS_HAD_NO_EFFECT            2
>>>>>>> Stashed changes

// gGotDefrostedStringIds
enum GotDefrostedStringID
{
    B_MSG_DEFROSTED,
    B_MSG_DEFROSTED_BY_MOVE,
};

// gFrostbiteHealedStringIds
enum FrostbiteHealedStringID
{
    B_MSG_FROSTBITE_HEALED,
    B_MSG_FROSTBITE_HEALED_BY_MOVE,
};

// gBattlePalaceFlavorTextTable
enum BattlePalaceFlavorTextID
{
    B_MSG_GLINT_IN_EYE,
    B_MSG_GETTING_IN_POS,
    B_MSG_GROWL_DEEPLY,
    B_MSG_EAGER_FOR_MORE,
};

// gRefereeStringsTable
enum RefereeStringID
{
    B_MSG_REF_NOTHING_IS_DECIDED = 0, // Default, likely actually a magic number somewhere that should be assigned this instead if used at all
    B_MSG_REF_THATS_IT,
    B_MSG_REF_JUDGE_MIND,
    B_MSG_REF_JUDGE_SKILL,
    B_MSG_REF_JUDGE_BODY,
    B_MSG_REF_PLAYER_WON,
    B_MSG_REF_OPPONENT_WON,
    B_MSG_REF_DRAW,
    B_MSG_REF_COMMENCE_BATTLE,
};

// gSwitchInAbilityStringIds
enum SwitchInAbilityStringID
{
    B_MSG_SWITCHIN_MOLDBREAKER,
    B_MSG_SWITCHIN_TERAVOLT,
    B_MSG_SWITCHIN_TURBOBLAZE,
    B_MSG_SWITCHIN_SLOWSTART,
    B_MSG_SWITCHIN_UNNERVE,
    B_MSG_SWITCHIN_ANTICIPATION,
    B_MSG_SWITCHIN_FOREWARN,
    B_MSG_SWITCHIN_PRESSURE,
    B_MSG_SWITCHIN_DARKAURA,
    B_MSG_SWITCHIN_FAIRYAURA,
    B_MSG_SWITCHIN_AURABREAK,
    B_MSG_SWITCHIN_COMATOSE,
    B_MSG_SWITCHIN_SCREENCLEANER,
    B_MSG_SWITCHIN_ASONE,
    B_MSG_SWITCHIN_CURIOUS_MEDICINE,
    B_MSG_SWITCHIN_PASTEL_VEIL,
    B_MSG_SWITCHIN_NEUTRALIZING_GAS,
};

// gMentalHerbCureStringIds
enum MentalHerbCureStringID
{
    B_MSG_MENTALHERBCURE_INFATUATION,
    B_MSG_MENTALHERBCURE_TAUNT,
    B_MSG_MENTALHERBCURE_ENCORE,
    B_MSG_MENTALHERBCURE_TORMENT,
    B_MSG_MENTALHERBCURE_HEALBLOCK,
    B_MSG_MENTALHERBCURE_DISABLE,
};

// gTerrainPreventsStringIds
enum TerrainPreventsStringID
{
    B_MSG_TERRAINPREVENTS_MISTY,
    B_MSG_TERRAINPREVENTS_ELECTRIC,
    B_MSG_TERRAINPREVENTS_PSYCHIC,
};

// gTerrainStringIds
enum TerrainStringID
{
    B_MSG_TERRAIN_SET_MISTY,
    B_MSG_TERRAIN_SET_ELECTRIC,
    B_MSG_TERRAIN_SET_PSYCHIC,
    B_MSG_TERRAIN_SET_GRASSY,
    B_MSG_TERRAIN_END_MISTY,
    B_MSG_TERRAIN_END_ELECTRIC,
    B_MSG_TERRAIN_END_PSYCHIC,
    B_MSG_TERRAIN_END_GRASSY,
    B_MSG_TERRAIN_COUNT
};

// gStartingStatusStringIds
enum StartingStatusStringID
{
    B_MSG_SET_TRICK_ROOM = (B_MSG_TERRAIN_SET_GRASSY + 1),
    B_MSG_SET_MAGIC_ROOM,
    B_MSG_SET_WONDER_ROOM,
    B_MSG_SET_TAILWIND,
    B_MSG_SET_RAINBOW,
    B_MSG_SET_SEA_OF_FIRE,
    B_MSG_SET_SWAMP,
    B_MSG_SET_SPIKES,
    B_MSG_SET_POISON_SPIKES,
    B_MSG_SET_STICKY_WEB,
    B_MSG_SET_STEALTH_ROCK,
    B_MSG_SET_SHARP_STEEL,
    B_MSG_STARTING_STATUS_COUNT,
};

// gWrappedStringIds
enum __attribute__((packed)) WrappedStringID
{
    B_MSG_WRAPPED_BIND,
    B_MSG_WRAPPED_WRAP,
    B_MSG_WRAPPED_FIRE_SPIN,
    B_MSG_WRAPPED_CLAMP,
    B_MSG_WRAPPED_WHIRLPOOL,
    B_MSG_WRAPPED_SAND_TOMB,
    B_MSG_WRAPPED_MAGMA_STORM,
    B_MSG_WRAPPED_INFESTATION,
    B_MSG_WRAPPED_SNAP_TRAP,
    B_MSG_WRAPPED_THUNDER_CAGE,
    NUM_TRAPPING_MOVES,
};

// z effects
enum ZEffectStringID
{
    B_MSG_Z_RESET_STATS,
    B_MSG_Z_ALL_STATS_UP,
    B_MSG_Z_BOOST_CRITS,
    B_MSG_Z_FOLLOW_ME,
    B_MSG_Z_RECOVER_HP,
    B_MSG_Z_STAT_UP,
    B_MSG_Z_HP_TRAP,
};

// gDmgHazardsStringIds
<<<<<<< Updated upstream
enum DmgHazardStringID
{
    B_MSG_PKMNHURTBYSPIKES,
    B_MSG_STEALTHROCKDMG,
    B_MSG_SHARPSTEELDMG,
    B_MSG_POINTEDSTONESFLOAT,
    B_MSG_SPIKESSCATTERED,
    B_MSG_SHARPSTEELFLOATS,
};

// gDamageNonTypesStartStringIds
enum DamageNonTypesStartStringID
{
    B_MSG_TRAPPED_WITH_VINES,
    B_MSG_CAUGHT_IN_VORTEX,
    B_MSG_SURROUNDED_BY_FIRE,
    B_MSG_SURROUNDED_BY_ROCKS,
};

// gDamageNonTypesDmgStringIds
enum DamageNonTypesDmgStringID
{
    B_MSG_HURT_BY_VINES,
    B_MSG_HURT_BY_VORTEX,
    B_MSG_BURNING_UP,
    B_MSG_HURT_BY_ROCKS_THROWN,
};
=======
#define B_MSG_PKMNHURTBYSPIKES     0
#define B_MSG_STEALTHROCKDMG       1
#define B_MSG_POINTEDSTONESFLOAT   2
#define B_MSG_SPIKESSCATTERED      3
#define B_MSG_FAIRYDUSTDMG         4
#define B_MSG_MYSTERIOUSDUSTFLOATS 5
>>>>>>> Stashed changes

// gZenModeStringIds
enum ZenModeStringID
{
    B_MSG_ZEN_MODE_TRIGGERED,
    B_MSG_ZEN_MODE_ENDED,
};

#endif // GUARD_CONSTANTS_BATTLE_STRING_IDS_H
