#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

enum BerryFirmness
{
    BERRY_FIRMNESS_UNKNOWN,
    BERRY_FIRMNESS_VERY_SOFT,
    BERRY_FIRMNESS_SOFT,
    BERRY_FIRMNESS_HARD,
    BERRY_FIRMNESS_VERY_HARD,
    BERRY_FIRMNESS_SUPER_HARD,
};

enum BerryColor
{
    BERRY_COLOR_RED,
    BERRY_COLOR_BLUE,
    BERRY_COLOR_PURPLE,
    BERRY_COLOR_GREEN,
    BERRY_COLOR_YELLOW,
    BERRY_COLOR_PINK,
};

enum __attribute__((__packed__)) Flavor
{
    FLAVOR_SPICY,
    FLAVOR_DRY,
    FLAVOR_SWEET,
    FLAVOR_BITTER,
    FLAVOR_SOUR,
    FLAVOR_COUNT,
};

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_TRUNK       6 // These follow BERRY_STAGE_BERRIES to preserve save compatibility
#define BERRY_STAGE_BUDDING     7
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"
#define BERRY_TREE_ROUTE_102_PECHA    1
#define BERRY_TREE_ROUTE_102_ORAN     2
#define BERRY_TREE_ROUTE_104_SOIL_1   3
#define BERRY_TREE_ROUTE_104_ORAN_1   4
#define BERRY_TREE_ROUTE_103_CHERI_1  5
#define BERRY_TREE_ROUTE_103_LEPPA    6
#define BERRY_TREE_ROUTE_103_CHERI_2  7
#define BERRY_TREE_ROUTE_104_CHERI_1  8
#define BERRY_TREE_ROUTE_104_SOIL_2   9
#define BERRY_TREE_ROUTE_104_LEPPA    10
#define BERRY_TREE_ROUTE_104_ORAN_2   11
#define BERRY_TREE_ROUTE_104_SOIL_3   12
#define BERRY_TREE_ROUTE_104_PECHA    13
#define BERRY_TREE_ROUTE_123_QUALOT_1 14
#define BERRY_TREE_ROUTE_123_POMEG_1  15
#define BERRY_TREE_ROUTE_110_NANAB_1  16
#define BERRY_TREE_ROUTE_110_NANAB_2  17
#define BERRY_TREE_ROUTE_110_NANAB_3  18
#define BERRY_TREE_ROUTE_111_RAZZ_1   19
#define BERRY_TREE_ROUTE_111_RAZZ_2   20
#define BERRY_TREE_ROUTE_112_RAWST_1  21
#define BERRY_TREE_ROUTE_112_PECHA_1  22
#define BERRY_TREE_ROUTE_112_PECHA_2  23
#define BERRY_TREE_ROUTE_112_RAWST_2  24
#define BERRY_TREE_ROUTE_116_PINAP_1  25
#define BERRY_TREE_ROUTE_116_CHESTO_1 26
#define BERRY_TREE_ROUTE_117_WEPEAR_1 27
#define BERRY_TREE_ROUTE_117_WEPEAR_2 28
#define BERRY_TREE_ROUTE_117_WEPEAR_3 29
#define BERRY_TREE_ROUTE_123_POMEG_2  30
#define BERRY_TREE_ROUTE_118_SITRUS_1 31
#define BERRY_TREE_ROUTE_118_SOIL     32
#define BERRY_TREE_ROUTE_118_SITRUS_2 33
#define BERRY_TREE_ROUTE_119_POMEG_1  34
#define BERRY_TREE_ROUTE_119_POMEG_2  35
#define BERRY_TREE_ROUTE_119_POMEG_3  36
#define BERRY_TREE_ROUTE_120_ASPEAR_1 37
#define BERRY_TREE_ROUTE_120_ASPEAR_2 38
#define BERRY_TREE_ROUTE_120_ASPEAR_3 39
#define BERRY_TREE_ROUTE_120_PECHA_1  40
#define BERRY_TREE_ROUTE_120_PECHA_2  41
#define BERRY_TREE_ROUTE_120_PECHA_3  42
#define BERRY_TREE_ROUTE_120_RAZZ     43
#define BERRY_TREE_ROUTE_120_NANAB    44
#define BERRY_TREE_ROUTE_120_PINAP    45
#define BERRY_TREE_ROUTE_120_WEPEAR   46
#define BERRY_TREE_ROUTE_121_PERSIM   47
#define BERRY_TREE_ROUTE_121_ASPEAR   48
#define BERRY_TREE_ROUTE_121_RAWST    49
#define BERRY_TREE_ROUTE_121_CHESTO   50
#define BERRY_TREE_ROUTE_121_SOIL_1   51
#define BERRY_TREE_ROUTE_121_NANAB_1  52
#define BERRY_TREE_ROUTE_121_NANAB_2  53
#define BERRY_TREE_ROUTE_121_SOIL_2   54
#define BERRY_TREE_ROUTE_115_BLUK_1   55
#define BERRY_TREE_ROUTE_115_BLUK_2   56
//#define BERRY_TREE_UNUSED             57
#define BERRY_TREE_ROUTE_93_OCCA_1    57
#define BERRY_TREE_ROUTE_123_POMEG_3  58
#define BERRY_TREE_ROUTE_123_POMEG_4  59
#define BERRY_TREE_ROUTE_123_GREPA_1  60
#define BERRY_TREE_ROUTE_123_GREPA_2  61
#define BERRY_TREE_ROUTE_123_LEPPA_1  62
#define BERRY_TREE_ROUTE_123_SOIL     63
#define BERRY_TREE_ROUTE_123_LEPPA_2  64
#define BERRY_TREE_ROUTE_123_GREPA_3  65
#define BERRY_TREE_ROUTE_116_CHESTO_2 66
#define BERRY_TREE_ROUTE_116_PINAP_2  67
#define BERRY_TREE_ROUTE_114_PERSIM_1 68
#define BERRY_TREE_ROUTE_115_KELPSY_1 69
#define BERRY_TREE_ROUTE_115_KELPSY_2 70
#define BERRY_TREE_ROUTE_115_KELPSY_3 71
#define BERRY_TREE_ROUTE_123_GREPA_4  72
#define BERRY_TREE_ROUTE_123_QUALOT_2 73
#define BERRY_TREE_ROUTE_123_QUALOT_3 74
#define BERRY_TREE_ROUTE_104_SOIL_4   75
#define BERRY_TREE_ROUTE_104_CHERI_2  76
#define BERRY_TREE_ROUTE_114_PERSIM_2 77
#define BERRY_TREE_ROUTE_114_PERSIM_3 78
#define BERRY_TREE_ROUTE_123_QUALOT_4 79
#define BERRY_TREE_ROUTE_111_ORAN_1   80
#define BERRY_TREE_ROUTE_111_ORAN_2   81
#define BERRY_TREE_ROUTE_130_LIECHI   82
#define BERRY_TREE_ROUTE_119_HONDEW_1 83
#define BERRY_TREE_ROUTE_119_HONDEW_2 84
#define BERRY_TREE_ROUTE_119_SITRUS   85
#define BERRY_TREE_ROUTE_119_LEPPA    86
#define BERRY_TREE_ROUTE_123_PECHA    87
#define BERRY_TREE_ROUTE_123_SITRUS   88
#define BERRY_TREE_ROUTE_123_RAWST    89
#define BERRY_TREE_RESEDA_WOODS_ORAN_1    90
#define BERRY_TREE_RESEDA_WOODS_ORAN_2    91
#define BERRY_TREE_RESEDA_WOODS_ORAN_3    92
#define BERRY_TREE_ROUTE_82_SALAC_1   93
#define BERRY_TREE_ROUTE_82_SALAC_2   94
#define BERRY_TREE_ROUTE_88_CHERI_1   95
#define BERRY_TREE_ROUTE_88_CHERI_2   96
#define BERRY_TREE_ROUTE_88_NOMEL_1   97
#define BERRY_TREE_ROUTE_88_NOMEL_2   98
#define BERRY_TREE_ROUTE_88_EGGANT_1  99
#define BERRY_TREE_ROUTE_88_EGGANT_2  100
#define BERRY_TREE_ROUTE_84_CORNN_1   101
#define BERRY_TREE_ROUTE_84_CORNN_2   102
#define BERRY_TREE_RESEDA_WOODS_RINDO_1   103
#define BERRY_TREE_RESEDA_WOODS_RINDO_2   104
#define BERRY_TREE_ROUTE_78_SITRUS_1  105
#define BERRY_TREE_ROUTE_78_SITRUS_2  106
#define BERRY_TREE_ROUTE_79_PECHA_1   107
#define BERRY_TREE_ROUTE_79_PECHA_2   108

#define BERRY_TREE_ROUTE_93_OCCA_2    109
#define BERRY_TREE_MINDARO_GARDENS_LEPPA_1    110
#define BERRY_TREE_MINDARO_GARDENS_LEPPA_2    111
#define BERRY_TREE_MINDARO_GARDENS_BABIRI_1   112
#define BERRY_TREE_MINDARO_GARDENS_BABIRI_2   113
#define BERRY_TREE_MINDARO_GARDENS_PERSIM_1   114
#define BERRY_TREE_MINDARO_GARDENS_PERSIM_2   115
#define BERRY_TREE_MINDARO_GARDENS_DRASH_1    116
#define BERRY_TREE_MINDARO_GARDENS_DRASH_2    117
#define BERRY_TREE_MINDARO_GARDENS_APICOT_1   118
#define BERRY_TREE_MINDARO_GARDENS_APICOT_2   119
#define BERRY_TREE_MINDARO_GARDENS_TAMATO_1   120
#define BERRY_TREE_MINDARO_GARDENS_TAMATO_2   121
#define BERRY_TREE_ROUTE_69_ASPEAR_1          122
#define BERRY_TREE_ROUTE_69_ASPEAR_2          123
#define BERRY_TREE_ROUTE_91_PUMKIN_1          124
#define BERRY_TREE_ROUTE_91_PUMKIN_2          125
#define BERRY_TREE_SCARLET_WOODS_GREPA_1      126
#define BERRY_TREE_SCARLET_WOODS_GREPA_2      127
#define BERRY_TREE_ROUTE_95_GANLON_1          128
#define BERRY_TREE_ROUTE_95_GANLON_2          129

#define BERRY_TREE_SHAMROCK_ISLE_GINEMA_1     130
#define BERRY_TREE_SHAMROCK_ISLE_GINEMA_2     131
#define BERRY_TREE_SHAMROCK_ISLE_TANGA_1      132
#define BERRY_TREE_SHAMROCK_ISLE_TANGA_2      133
#define BERRY_TREE_SHAMROCK_ISLE_YACHE_1      134
#define BERRY_TREE_SHAMROCK_ISLE_YACHE_2      135
#define BERRY_TREE_SHAMROCK_ISLE_PASSHO_1     136
#define BERRY_TREE_SHAMROCK_ISLE_PASSHO_2     137
#define BERRY_TREE_SHAMROCK_ISLE_TOUGA_1      138
#define BERRY_TREE_SHAMROCK_ISLE_TOUGA_2      139
#define BERRY_TREE_SHAMROCK_ISLE_IAPAPA_1     140
#define BERRY_TREE_SHAMROCK_ISLE_IAPAPA_2     141
#define BERRY_TREE_SHAMROCK_ISLE_QUALOT_1     142
#define BERRY_TREE_SHAMROCK_ISLE_QUALOT_2     143

// Remainder are unused

//#define BERRY_TREES_COUNT 128
#define BERRY_TREES_COUNT 160 //256


#endif // GUARD_CONSTANTS_BERRY_H
