#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/heal_locations.json and Inja template src/data/heal_locations.constants.json.txt
//


enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F,
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F,
    HEAL_LOCATION_PETALBURG_CITY,
    HEAL_LOCATION_SLATEPORT_CITY,
    HEAL_LOCATION_MAUVILLE_CITY,
    HEAL_LOCATION_RUSTBORO_CITY,
    HEAL_LOCATION_FORTREE_CITY,
    HEAL_LOCATION_LILYCOVE_CITY,
    HEAL_LOCATION_MOSSDEEP_CITY,
    HEAL_LOCATION_SOOTOPOLIS_CITY,
    HEAL_LOCATION_EVER_GRANDE_CITY,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE,
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE,
    HEAL_LOCATION_OLDALE_TOWN,
    HEAL_LOCATION_DEWFORD_TOWN,
    HEAL_LOCATION_LAVARIDGE_TOWN,
    HEAL_LOCATION_FALLARBOR_TOWN,
    HEAL_LOCATION_VERDANTURF_TOWN,
    HEAL_LOCATION_PACIFIDLOG_TOWN,
    HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE,
    HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR,
    HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST,
    HEAL_LOCATION_UMBER_TOWN_MALE_MCHOUSE_2F,
    HEAL_LOCATION_CINEROUS_TOWN,
    HEAL_LOCATION_XANTHOS_CITY,
    HEAL_LOCATION_RESEDA_TOWN,
    HEAL_LOCATION_AMBER_CITY,
    HEAL_LOCATION_COBALT_CITY,
    HEAL_LOCATION_TURQUOISE_CITY,
    HEAL_LOCATION_MINDARO_CITY,
    HEAL_LOCATION_OFFWITE_TOWN,
    HEAL_LOCATION_SCARLET_TOWN,
    HEAL_LOCATION_PITCHBLAK_CITY,
    HEAL_LOCATION_MAROON_CITY,
    HEAL_LOCATION_HAEWEN_TOWN,
    HEAL_LOCATION_WISTERIA_CITY,
    HEAL_LOCATION_DUN_TOWN,
    HEAL_LOCATION_BURGUNDY_TOWN,
    HEAL_LOCATION_ROUTE_100,
    HEAL_LOCATION_X_COSMOPOLIS,
    NUM_HEAL_LOCATIONS
};

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
