#ifndef GUARD_CONSTANTS_MAP_TYPES_H
#define GUARD_CONSTANTS_MAP_TYPES_H

enum MapType
{
    MAP_TYPE_NONE,
    MAP_TYPE_TOWN,
    MAP_TYPE_CITY,
    MAP_TYPE_ROUTE,
    MAP_TYPE_UNDERGROUND,
    MAP_TYPE_UNDERWATER,
    MAP_TYPE_OCEAN_ROUTE,
    MAP_TYPE_UNKNOWN, // Not used by any map.
    MAP_TYPE_INDOOR,
    MAP_TYPE_SECRET_BASE,
};

<<<<<<< Updated upstream
enum MapBattleScene
{
    MAP_BATTLE_SCENE_NORMAL,
    MAP_BATTLE_SCENE_GYM,
    MAP_BATTLE_SCENE_MAGMA,
    MAP_BATTLE_SCENE_AQUA,
    MAP_BATTLE_SCENE_SIDNEY,
    MAP_BATTLE_SCENE_PHOEBE,
    MAP_BATTLE_SCENE_GLACIA,
    MAP_BATTLE_SCENE_DRAKE,
    MAP_BATTLE_SCENE_FRONTIER,
};
=======
#define MAP_BATTLE_SCENE_NORMAL       0
#define MAP_BATTLE_SCENE_GYM          1
#define MAP_BATTLE_SCENE_MAGMA        2
#define MAP_BATTLE_SCENE_AQUA         3
#define MAP_BATTLE_SCENE_SIDNEY       4
#define MAP_BATTLE_SCENE_PHOEBE       5
#define MAP_BATTLE_SCENE_GLACIA       6
#define MAP_BATTLE_SCENE_DRAKE        7
#define MAP_BATTLE_SCENE_FRONTIER     8
#define MAP_BATTLE_SCENE_LISIA        9
#define MAP_BATTLE_SCENE_IAN          10
#define MAP_BATTLE_SCENE_SIDNEY2      11
#define MAP_BATTLE_SCENE_PETRA        12
#define MAP_BATTLE_SCENE_NORMAN       13
>>>>>>> Stashed changes

#define MAP_BATTLE_SCENE_INDOOR_1 MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_INDOOR_2 MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LORELEI  MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_BRUNO    MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_AGATHA   MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LANCE    MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_LINK     MAP_BATTLE_SCENE_NORMAL

#endif  // GUARD_CONSTANTS_MAP_TYPES_H
