#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

enum
{
    // gMapGroup_TownsAndRoutes
    MAP_PETALBURG_CITY             = (0 | (0 << 8)),
    MAP_SLATEPORT_CITY             = (1 | (0 << 8)),
    MAP_MAUVILLE_CITY              = (2 | (0 << 8)),
    MAP_RUSTBORO_CITY              = (3 | (0 << 8)),
    MAP_FORTREE_CITY               = (4 | (0 << 8)),
    MAP_LILYCOVE_CITY              = (5 | (0 << 8)),
    MAP_MOSSDEEP_CITY              = (6 | (0 << 8)),
    MAP_SOOTOPOLIS_CITY            = (7 | (0 << 8)),
    MAP_EVER_GRANDE_CITY           = (8 | (0 << 8)),
    MAP_LITTLEROOT_TOWN            = (9 | (0 << 8)),
    MAP_OLDALE_TOWN                = (10 | (0 << 8)),
    MAP_DEWFORD_TOWN               = (11 | (0 << 8)),
    MAP_LAVARIDGE_TOWN             = (12 | (0 << 8)),
    MAP_FALLARBOR_TOWN             = (13 | (0 << 8)),
    MAP_VERDANTURF_TOWN            = (14 | (0 << 8)),
    MAP_PACIFIDLOG_TOWN            = (15 | (0 << 8)),
    MAP_ROUTE101                   = (16 | (0 << 8)),
    MAP_ROUTE102                   = (17 | (0 << 8)),
    MAP_ROUTE103                   = (18 | (0 << 8)),
    MAP_ROUTE104                   = (19 | (0 << 8)),
    MAP_ROUTE105                   = (20 | (0 << 8)),
    MAP_ROUTE106                   = (21 | (0 << 8)),
    MAP_ROUTE107                   = (22 | (0 << 8)),
    MAP_ROUTE108                   = (23 | (0 << 8)),
    MAP_ROUTE109                   = (24 | (0 << 8)),
    MAP_ROUTE110                   = (25 | (0 << 8)),
    MAP_ROUTE111                   = (26 | (0 << 8)),
    MAP_ROUTE112                   = (27 | (0 << 8)),
    MAP_ROUTE113                   = (28 | (0 << 8)),
    MAP_ROUTE114                   = (29 | (0 << 8)),
    MAP_ROUTE115                   = (30 | (0 << 8)),
    MAP_ROUTE116                   = (31 | (0 << 8)),
    MAP_ROUTE117                   = (32 | (0 << 8)),
    MAP_ROUTE118                   = (33 | (0 << 8)),
    MAP_ROUTE119                   = (34 | (0 << 8)),
    MAP_ROUTE120                   = (35 | (0 << 8)),
    MAP_ROUTE121                   = (36 | (0 << 8)),
    MAP_ROUTE122                   = (37 | (0 << 8)),
    MAP_ROUTE123                   = (38 | (0 << 8)),
    MAP_ROUTE124                   = (39 | (0 << 8)),
    MAP_ROUTE125                   = (40 | (0 << 8)),
    MAP_ROUTE126                   = (41 | (0 << 8)),
    MAP_ROUTE127                   = (42 | (0 << 8)),
    MAP_ROUTE128                   = (43 | (0 << 8)),
    MAP_ROUTE129                   = (44 | (0 << 8)),
    MAP_ROUTE130                   = (45 | (0 << 8)),
    MAP_ROUTE131                   = (46 | (0 << 8)),
    MAP_ROUTE132                   = (47 | (0 << 8)),
    MAP_ROUTE133                   = (48 | (0 << 8)),
    MAP_ROUTE134                   = (49 | (0 << 8)),
    MAP_UNDERWATER_ROUTE124        = (50 | (0 << 8)),
    MAP_UNDERWATER_ROUTE126        = (51 | (0 << 8)),
    MAP_UNDERWATER_ROUTE127        = (52 | (0 << 8)),
    MAP_UNDERWATER_ROUTE128        = (53 | (0 << 8)),
    MAP_UNDERWATER_ROUTE129        = (54 | (0 << 8)),
    MAP_UNDERWATER_ROUTE105        = (55 | (0 << 8)),
    MAP_UNDERWATER_ROUTE125        = (56 | (0 << 8)),
    MAP_UMBER_TOWN                 = (57 | (0 << 8)),
    MAP_CINEROUS_TOWN              = (58 | (0 << 8)),
    MAP_XANTHOS_CITY               = (59 | (0 << 8)),
    MAP_RESEDA_TOWN                = (60 | (0 << 8)),
    MAP_AMBER_CITY                 = (61 | (0 << 8)),
    MAP_COBALT_CITY                = (62 | (0 << 8)),
    MAP_ROUTE80                    = (63 | (0 << 8)),
    MAP_ROUTE81                    = (64 | (0 << 8)),
    MAP_ROUTE82                    = (65 | (0 << 8)),
    MAP_ROUTE83                    = (66 | (0 << 8)),
    MAP_ROUTE84                    = (67 | (0 << 8)),
    MAP_ROUTE89                    = (68 | (0 << 8)),
    MAP_ROUTE85                    = (69 | (0 << 8)),
    MAP_ROUTE86                    = (70 | (0 << 8)),
    MAP_ROUTE87                    = (71 | (0 << 8)),
    MAP_ROUTE88                    = (72 | (0 << 8)),
    MAP_ROUTE79                    = (73 | (0 << 8)),
    MAP_ROUTE78                    = (74 | (0 << 8)),
    MAP_ROUTE77                    = (75 | (0 << 8)),
    MAP_ROUTE76                    = (76 | (0 << 8)),
    MAP_ROUTE75                    = (77 | (0 << 8)),
    MAP_ROUTE74                    = (78 | (0 << 8)),
    MAP_ROUTE73                    = (79 | (0 << 8)),
    MAP_ROUTE72                    = (80 | (0 << 8)),
    MAP_ROUTE71                    = (81 | (0 << 8)),
    MAP_ROUTE70                    = (82 | (0 << 8)),
    MAP_TURQUOISE_CITY             = (83 | (0 << 8)),
    MAP_MINDARO_CITY               = (84 | (0 << 8)),
    MAP_OFFWITE_TOWN               = (85 | (0 << 8)),
    MAP_SCARLET_TOWN               = (86 | (0 << 8)),
    MAP_PITCHBLAK_CITY             = (87 | (0 << 8)),
    MAP_MAROON_CITY                = (88 | (0 << 8)),
    MAP_ROUTE99                    = (89 | (0 << 8)),
    MAP_ROUTE98                    = (90 | (0 << 8)),
    MAP_ROUTE97                    = (91 | (0 << 8)),
    MAP_ROUTE96                    = (92 | (0 << 8)),
    MAP_ROUTE95                    = (93 | (0 << 8)),
    MAP_ROUTE94                    = (94 | (0 << 8)),
    MAP_ROUTE93                    = (95 | (0 << 8)),
    MAP_ROUTE92                    = (96 | (0 << 8)),
    MAP_ROUTE91                    = (97 | (0 << 8)),
    MAP_ROUTE90                    = (98 | (0 << 8)),
    MAP_HAEWEN_TOWN                = (99 | (0 << 8)),
    MAP_WISTERIA_CITY              = (100 | (0 << 8)),
    MAP_DUN_TOWN                   = (101 | (0 << 8)),
    MAP_BURGUNDY_TOWN              = (102 | (0 << 8)),
    MAP_ROUTE69                    = (103 | (0 << 8)),
    MAP_ROUTE68                    = (104 | (0 << 8)),
    MAP_ROUTE67                    = (105 | (0 << 8)),
    MAP_ROUTE66                    = (106 | (0 << 8)),
    MAP_ROUTE65                    = (107 | (0 << 8)),
    MAP_UNDERWATER_ROUTE75         = (108 | (0 << 8)),
    MAP_UNDERGROUND_ROUTE68        = (109 | (0 << 8)),
    MAP_UNDERGROUND_ROUTE70        = (110 | (0 << 8)),
    MAP_UNDERGROUND_HAEWEN_TOWN    = (111 | (0 << 8)),
    MAP_ROUTE100                   = (112 | (0 << 8)),
    MAP_UNDERWATER_ROUTE100        = (113 | (0 << 8)),
    MAP_UNDERGROUND_ROUTE70_STAIRS = (114 | (0 << 8)),

    // gMapGroup_IndoorLittleroot
    MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    = (0 | (1 << 8)),
    MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    = (1 | (1 << 8)),
    MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        = (2 | (1 << 8)),
    MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        = (3 | (1 << 8)),
    MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB = (4 | (1 << 8)),

    // gMapGroup_IndoorOldale
    MAP_OLDALE_TOWN_HOUSE1            = (0 | (2 << 8)),
    MAP_OLDALE_TOWN_HOUSE2            = (1 | (2 << 8)),
    MAP_OLDALE_TOWN_POKEMON_CENTER_1F = (2 | (2 << 8)),
    MAP_OLDALE_TOWN_POKEMON_CENTER_2F = (3 | (2 << 8)),
    MAP_OLDALE_TOWN_MART              = (4 | (2 << 8)),

    // gMapGroup_IndoorDewford
    MAP_DEWFORD_TOWN_HOUSE1            = (0 | (3 << 8)),
    MAP_DEWFORD_TOWN_POKEMON_CENTER_1F = (1 | (3 << 8)),
    MAP_DEWFORD_TOWN_POKEMON_CENTER_2F = (2 | (3 << 8)),
    MAP_DEWFORD_TOWN_GYM               = (3 | (3 << 8)),
    MAP_DEWFORD_TOWN_HALL              = (4 | (3 << 8)),
    MAP_DEWFORD_TOWN_HOUSE2            = (5 | (3 << 8)),

    // gMapGroup_IndoorLavaridge
    MAP_LAVARIDGE_TOWN_HERB_SHOP         = (0 | (4 << 8)),
    MAP_LAVARIDGE_TOWN_GYM_1F            = (1 | (4 << 8)),
    MAP_LAVARIDGE_TOWN_GYM_B1F           = (2 | (4 << 8)),
    MAP_LAVARIDGE_TOWN_HOUSE             = (3 | (4 << 8)),
    MAP_LAVARIDGE_TOWN_MART              = (4 | (4 << 8)),
    MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F = (5 | (4 << 8)),
    MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F = (6 | (4 << 8)),

    // gMapGroup_IndoorFallarbor
    MAP_FALLARBOR_TOWN_MART                    = (0 | (5 << 8)),
    MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       = (1 | (5 << 8)),
    MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    = (2 | (5 << 8)),
    MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM = (3 | (5 << 8)),
    MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       = (4 | (5 << 8)),
    MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       = (5 | (5 << 8)),
    MAP_FALLARBOR_TOWN_COZMOS_HOUSE            = (6 | (5 << 8)),
    MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   = (7 | (5 << 8)),

    // gMapGroup_IndoorVerdanturf
    MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       = (0 | (6 << 8)),
    MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    = (1 | (6 << 8)),
    MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM = (2 | (6 << 8)),
    MAP_VERDANTURF_TOWN_MART                    = (3 | (6 << 8)),
    MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       = (4 | (6 << 8)),
    MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       = (5 | (6 << 8)),
    MAP_VERDANTURF_TOWN_WANDAS_HOUSE            = (6 | (6 << 8)),
    MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE = (7 | (6 << 8)),
    MAP_VERDANTURF_TOWN_HOUSE                   = (8 | (6 << 8)),

    // gMapGroup_IndoorPacifidlog
    MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F = (0 | (7 << 8)),
    MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F = (1 | (7 << 8)),
    MAP_PACIFIDLOG_TOWN_HOUSE1            = (2 | (7 << 8)),
    MAP_PACIFIDLOG_TOWN_HOUSE2            = (3 | (7 << 8)),
    MAP_PACIFIDLOG_TOWN_HOUSE3            = (4 | (7 << 8)),
    MAP_PACIFIDLOG_TOWN_HOUSE4            = (5 | (7 << 8)),
    MAP_PACIFIDLOG_TOWN_HOUSE5            = (6 | (7 << 8)),

    // gMapGroup_IndoorPetalburg
    MAP_PETALBURG_CITY_WALLYS_HOUSE      = (0 | (8 << 8)),
    MAP_PETALBURG_CITY_GYM               = (1 | (8 << 8)),
    MAP_PETALBURG_CITY_HOUSE1            = (2 | (8 << 8)),
    MAP_PETALBURG_CITY_HOUSE2            = (3 | (8 << 8)),
    MAP_PETALBURG_CITY_POKEMON_CENTER_1F = (4 | (8 << 8)),
    MAP_PETALBURG_CITY_POKEMON_CENTER_2F = (5 | (8 << 8)),
    MAP_PETALBURG_CITY_MART              = (6 | (8 << 8)),

    // gMapGroup_IndoorSlateport
    MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      = (0 | (9 << 8)),
    MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      = (1 | (9 << 8)),
    MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       = (2 | (9 << 8)),
    MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    = (3 | (9 << 8)),
    MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM = (4 | (9 << 8)),
    MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       = (5 | (9 << 8)),
    MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        = (6 | (9 << 8)),
    MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       = (7 | (9 << 8)),
    MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       = (8 | (9 << 8)),
    MAP_SLATEPORT_CITY_HARBOR                  = (9 | (9 << 8)),
    MAP_SLATEPORT_CITY_HOUSE                   = (10 | (9 << 8)),
    MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       = (11 | (9 << 8)),
    MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       = (12 | (9 << 8)),
    MAP_SLATEPORT_CITY_MART                    = (13 | (9 << 8)),

    // gMapGroup_IndoorMauville
    MAP_MAUVILLE_CITY_GYM               = (0 | (10 << 8)),
    MAP_MAUVILLE_CITY_BIKE_SHOP         = (1 | (10 << 8)),
    MAP_MAUVILLE_CITY_HOUSE1            = (2 | (10 << 8)),
    MAP_MAUVILLE_CITY_GAME_CORNER       = (3 | (10 << 8)),
    MAP_MAUVILLE_CITY_HOUSE2            = (4 | (10 << 8)),
    MAP_MAUVILLE_CITY_POKEMON_CENTER_1F = (5 | (10 << 8)),
    MAP_MAUVILLE_CITY_POKEMON_CENTER_2F = (6 | (10 << 8)),
    MAP_MAUVILLE_CITY_MART              = (7 | (10 << 8)),

    // gMapGroup_IndoorRustboro
    MAP_RUSTBORO_CITY_DEVON_CORP_1F     = (0 | (11 << 8)),
    MAP_RUSTBORO_CITY_DEVON_CORP_2F     = (1 | (11 << 8)),
    MAP_RUSTBORO_CITY_DEVON_CORP_3F     = (2 | (11 << 8)),
    MAP_RUSTBORO_CITY_GYM               = (3 | (11 << 8)),
    MAP_RUSTBORO_CITY_POKEMON_SCHOOL    = (4 | (11 << 8)),
    MAP_RUSTBORO_CITY_POKEMON_CENTER_1F = (5 | (11 << 8)),
    MAP_RUSTBORO_CITY_POKEMON_CENTER_2F = (6 | (11 << 8)),
    MAP_RUSTBORO_CITY_MART              = (7 | (11 << 8)),
    MAP_RUSTBORO_CITY_FLAT1_1F          = (8 | (11 << 8)),
    MAP_RUSTBORO_CITY_FLAT1_2F          = (9 | (11 << 8)),
    MAP_RUSTBORO_CITY_HOUSE1            = (10 | (11 << 8)),
    MAP_RUSTBORO_CITY_CUTTERS_HOUSE     = (11 | (11 << 8)),
    MAP_RUSTBORO_CITY_HOUSE2            = (12 | (11 << 8)),
    MAP_RUSTBORO_CITY_FLAT2_1F          = (13 | (11 << 8)),
    MAP_RUSTBORO_CITY_FLAT2_2F          = (14 | (11 << 8)),
    MAP_RUSTBORO_CITY_FLAT2_3F          = (15 | (11 << 8)),
    MAP_RUSTBORO_CITY_HOUSE3            = (16 | (11 << 8)),

    // gMapGroup_IndoorFortree
    MAP_FORTREE_CITY_HOUSE1            = (0 | (12 << 8)),
    MAP_FORTREE_CITY_GYM               = (1 | (12 << 8)),
    MAP_FORTREE_CITY_POKEMON_CENTER_1F = (2 | (12 << 8)),
    MAP_FORTREE_CITY_POKEMON_CENTER_2F = (3 | (12 << 8)),
    MAP_FORTREE_CITY_MART              = (4 | (12 << 8)),
    MAP_FORTREE_CITY_HOUSE2            = (5 | (12 << 8)),
    MAP_FORTREE_CITY_HOUSE3            = (6 | (12 << 8)),
    MAP_FORTREE_CITY_HOUSE4            = (7 | (12 << 8)),
    MAP_FORTREE_CITY_HOUSE5            = (8 | (12 << 8)),
    MAP_FORTREE_CITY_DECORATION_SHOP   = (9 | (12 << 8)),

    // gMapGroup_IndoorLilycove
    MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        = (0 | (13 << 8)),
    MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        = (1 | (13 << 8)),
    MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        = (2 | (13 << 8)),
    MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        = (3 | (13 << 8)),
    MAP_LILYCOVE_CITY_CONTEST_LOBBY             = (4 | (13 << 8)),
    MAP_LILYCOVE_CITY_CONTEST_HALL              = (5 | (13 << 8)),
    MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         = (6 | (13 << 8)),
    MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         = (7 | (13 << 8)),
    MAP_LILYCOVE_CITY_UNUSED_MART               = (8 | (13 << 8)),
    MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  = (9 | (13 << 8)),
    MAP_LILYCOVE_CITY_HARBOR                    = (10 | (13 << 8)),
    MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       = (11 | (13 << 8)),
    MAP_LILYCOVE_CITY_HOUSE1                    = (12 | (13 << 8)),
    MAP_LILYCOVE_CITY_HOUSE2                    = (13 | (13 << 8)),
    MAP_LILYCOVE_CITY_HOUSE3                    = (14 | (13 << 8)),
    MAP_LILYCOVE_CITY_HOUSE4                    = (15 | (13 << 8)),
    MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       = (16 | (13 << 8)),
    MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       = (17 | (13 << 8)),
    MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       = (18 | (13 << 8)),
    MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       = (19 | (13 << 8)),
    MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       = (20 | (13 << 8)),
    MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  = (21 | (13 << 8)),
    MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR = (22 | (13 << 8)),

    // gMapGroup_IndoorMossdeep
    MAP_MOSSDEEP_CITY_GYM               = (0 | (14 << 8)),
    MAP_MOSSDEEP_CITY_HOUSE1            = (1 | (14 << 8)),
    MAP_MOSSDEEP_CITY_HOUSE2            = (2 | (14 << 8)),
    MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F = (3 | (14 << 8)),
    MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F = (4 | (14 << 8)),
    MAP_MOSSDEEP_CITY_MART              = (5 | (14 << 8)),
    MAP_MOSSDEEP_CITY_HOUSE3            = (6 | (14 << 8)),
    MAP_MOSSDEEP_CITY_STEVENS_HOUSE     = (7 | (14 << 8)),
    MAP_MOSSDEEP_CITY_HOUSE4            = (8 | (14 << 8)),
    MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   = (9 | (14 << 8)),
    MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   = (10 | (14 << 8)),
    MAP_MOSSDEEP_CITY_GAME_CORNER_1F    = (11 | (14 << 8)),
    MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   = (12 | (14 << 8)),

    // gMapGroup_IndoorSootopolis
    MAP_SOOTOPOLIS_CITY_GYM_1F                   = (0 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_GYM_B1F                  = (1 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        = (2 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        = (3 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_MART                     = (4 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_HOUSE1                   = (5 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_HOUSE2                   = (6 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_HOUSE3                   = (7 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_HOUSE4                   = (8 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_HOUSE5                   = (9 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_HOUSE6                   = (10 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_HOUSE7                   = (11 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   = (12 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  = (13 | (15 << 8)),
    MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F = (14 | (15 << 8)),

    // gMapGroup_IndoorEverGrande
    MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      = (0 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      = (1 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      = (2 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_DRAKES_ROOM       = (3 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    = (4 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_HALL1             = (5 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_HALL2             = (6 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_HALL3             = (7 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_HALL4             = (8 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_HALL5             = (9 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F = (10 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_HALL_OF_FAME      = (11 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F = (12 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F = (13 | (16 << 8)),
    MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F = (14 | (16 << 8)),
    MAP_ROUTE100_POKEMON_CENTER_1F         = (15 | (16 << 8)),
    MAP_ROUTE100_POKEMON_CENTER_2F         = (16 | (16 << 8)),

    // gMapGroup_IndoorRoute104
    MAP_ROUTE104_MR_BRINEYS_HOUSE         = (0 | (17 << 8)),
    MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP = (1 | (17 << 8)),

    // gMapGroup_IndoorRoute111
    MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE = (0 | (18 << 8)),
    MAP_ROUTE111_OLD_LADYS_REST_STOP     = (1 | (18 << 8)),

    // gMapGroup_IndoorRoute112
    MAP_ROUTE112_CABLE_CAR_STATION   = (0 | (19 << 8)),
    MAP_MT_CHIMNEY_CABLE_CAR_STATION = (1 | (19 << 8)),

    // gMapGroup_IndoorRoute114
    MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  = (0 | (20 << 8)),
    MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL = (1 | (20 << 8)),
    MAP_ROUTE114_LANETTES_HOUSE        = (2 | (20 << 8)),

    // gMapGroup_IndoorRoute116
    MAP_ROUTE116_TUNNELERS_REST_HOUSE = (0 | (21 << 8)),

    // gMapGroup_IndoorRoute117
    MAP_ROUTE117_POKEMON_DAY_CARE = (0 | (22 << 8)),

    // gMapGroup_IndoorRoute121
    MAP_ROUTE121_SAFARI_ZONE_ENTRANCE = (0 | (23 << 8)),

    // gMapGroup_Dungeons
    MAP_METEOR_FALLS_1F_1R                       = (0 | (24 << 8)),
    MAP_METEOR_FALLS_1F_2R                       = (1 | (24 << 8)),
    MAP_METEOR_FALLS_B1F_1R                      = (2 | (24 << 8)),
    MAP_METEOR_FALLS_B1F_2R                      = (3 | (24 << 8)),
    MAP_RUSTURF_TUNNEL                           = (4 | (24 << 8)),
    MAP_UNDERWATER_SOOTOPOLIS_CITY               = (5 | (24 << 8)),
    MAP_DESERT_RUINS                             = (6 | (24 << 8)),
    MAP_GRANITE_CAVE_1F                          = (7 | (24 << 8)),
    MAP_GRANITE_CAVE_B1F                         = (8 | (24 << 8)),
    MAP_GRANITE_CAVE_B2F                         = (9 | (24 << 8)),
    MAP_GRANITE_CAVE_STEVENS_ROOM                = (10 | (24 << 8)),
    MAP_PETALBURG_WOODS                          = (11 | (24 << 8)),
    MAP_MT_CHIMNEY                               = (12 | (24 << 8)),
    MAP_JAGGED_PASS                              = (13 | (24 << 8)),
    MAP_FIERY_PATH                               = (14 | (24 << 8)),
    MAP_MT_PYRE_1F                               = (15 | (24 << 8)),
    MAP_MT_PYRE_2F                               = (16 | (24 << 8)),
    MAP_MT_PYRE_3F                               = (17 | (24 << 8)),
    MAP_MT_PYRE_4F                               = (18 | (24 << 8)),
    MAP_MT_PYRE_5F                               = (19 | (24 << 8)),
    MAP_MT_PYRE_6F                               = (20 | (24 << 8)),
    MAP_MT_PYRE_EXTERIOR                         = (21 | (24 << 8)),
    MAP_MT_PYRE_SUMMIT                           = (22 | (24 << 8)),
    MAP_AQUA_HIDEOUT_1F                          = (23 | (24 << 8)),
    MAP_AQUA_HIDEOUT_B1F                         = (24 | (24 << 8)),
    MAP_AQUA_HIDEOUT_B2F                         = (25 | (24 << 8)),
    MAP_UNDERWATER_SEAFLOOR_CAVERN               = (26 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ENTRANCE                 = (27 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM1                    = (28 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM2                    = (29 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM3                    = (30 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM4                    = (31 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM5                    = (32 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM6                    = (33 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM7                    = (34 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM8                    = (35 | (24 << 8)),
    MAP_SEAFLOOR_CAVERN_ROOM9                    = (36 | (24 << 8)),
    MAP_CAVE_OF_ORIGIN_ENTRANCE                  = (37 | (24 << 8)),
    MAP_CAVE_OF_ORIGIN_1F                        = (38 | (24 << 8)),
    MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 = (39 | (24 << 8)),
    MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 = (40 | (24 << 8)),
    MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 = (41 | (24 << 8)),
    MAP_CAVE_OF_ORIGIN_B1F                       = (42 | (24 << 8)),
    MAP_VICTORY_ROAD_1F                          = (43 | (24 << 8)),
    MAP_VICTORY_ROAD_B1F                         = (44 | (24 << 8)),
    MAP_VICTORY_ROAD_B2F                         = (45 | (24 << 8)),
    MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        = (46 | (24 << 8)),
    MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           = (47 | (24 << 8)),
    MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          = (48 | (24 << 8)),
    MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           = (49 | (24 << 8)),
    MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       = (50 | (24 << 8)),
    MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          = (51 | (24 << 8)),
    MAP_NEW_MAUVILLE_ENTRANCE                    = (52 | (24 << 8)),
    MAP_NEW_MAUVILLE_INSIDE                      = (53 | (24 << 8)),
    MAP_ABANDONED_SHIP_DECK                      = (54 | (24 << 8)),
    MAP_ABANDONED_SHIP_CORRIDORS_1F              = (55 | (24 << 8)),
    MAP_ABANDONED_SHIP_ROOMS_1F                  = (56 | (24 << 8)),
    MAP_ABANDONED_SHIP_CORRIDORS_B1F             = (57 | (24 << 8)),
    MAP_ABANDONED_SHIP_ROOMS_B1F                 = (58 | (24 << 8)),
    MAP_ABANDONED_SHIP_ROOMS2_B1F                = (59 | (24 << 8)),
    MAP_ABANDONED_SHIP_UNDERWATER1               = (60 | (24 << 8)),
    MAP_ABANDONED_SHIP_ROOM_B1F                  = (61 | (24 << 8)),
    MAP_ABANDONED_SHIP_ROOMS2_1F                 = (62 | (24 << 8)),
    MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           = (63 | (24 << 8)),
    MAP_ABANDONED_SHIP_UNDERWATER2               = (64 | (24 << 8)),
    MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    = (65 | (24 << 8)),
    MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        = (66 | (24 << 8)),
    MAP_ISLAND_CAVE                              = (67 | (24 << 8)),
    MAP_ANCIENT_TOMB                             = (68 | (24 << 8)),
    MAP_UNDERWATER_ROUTE134                      = (69 | (24 << 8)),
    MAP_UNDERWATER_SEALED_CHAMBER                = (70 | (24 << 8)),
    MAP_SEALED_CHAMBER_OUTER_ROOM                = (71 | (24 << 8)),
    MAP_SEALED_CHAMBER_INNER_ROOM                = (72 | (24 << 8)),
    MAP_SCORCHED_SLAB                            = (73 | (24 << 8)),
    MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            = (74 | (24 << 8)),
    MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            = (75 | (24 << 8)),
    MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            = (76 | (24 << 8)),
    MAP_SKY_PILLAR_ENTRANCE                      = (77 | (24 << 8)),
    MAP_SKY_PILLAR_OUTSIDE                       = (78 | (24 << 8)),
    MAP_SKY_PILLAR_1F                            = (79 | (24 << 8)),
    MAP_SKY_PILLAR_2F                            = (80 | (24 << 8)),
    MAP_SKY_PILLAR_3F                            = (81 | (24 << 8)),
    MAP_SKY_PILLAR_4F                            = (82 | (24 << 8)),
    MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             = (83 | (24 << 8)),
    MAP_SKY_PILLAR_5F                            = (84 | (24 << 8)),
    MAP_SKY_PILLAR_TOP                           = (85 | (24 << 8)),
    MAP_MAGMA_HIDEOUT_1F                         = (86 | (24 << 8)),
    MAP_MAGMA_HIDEOUT_2F_1R                      = (87 | (24 << 8)),
    MAP_MAGMA_HIDEOUT_2F_2R                      = (88 | (24 << 8)),
    MAP_MAGMA_HIDEOUT_3F_1R                      = (89 | (24 << 8)),
    MAP_MAGMA_HIDEOUT_3F_2R                      = (90 | (24 << 8)),
    MAP_MAGMA_HIDEOUT_4F                         = (91 | (24 << 8)),
    MAP_MAGMA_HIDEOUT_3F_3R                      = (92 | (24 << 8)),
    MAP_MAGMA_HIDEOUT_2F_3R                      = (93 | (24 << 8)),
    MAP_MIRAGE_TOWER_1F                          = (94 | (24 << 8)),
    MAP_MIRAGE_TOWER_2F                          = (95 | (24 << 8)),
    MAP_MIRAGE_TOWER_3F                          = (96 | (24 << 8)),
    MAP_MIRAGE_TOWER_4F                          = (97 | (24 << 8)),
    MAP_DESERT_UNDERPASS                         = (98 | (24 << 8)),
    MAP_ARTISAN_CAVE_B1F                         = (99 | (24 << 8)),
    MAP_ARTISAN_CAVE_1F                          = (100 | (24 << 8)),
    MAP_UNDERWATER_MARINE_CAVE                   = (101 | (24 << 8)),
    MAP_MARINE_CAVE_ENTRANCE                     = (102 | (24 << 8)),
    MAP_MARINE_CAVE_END                          = (103 | (24 << 8)),
    MAP_TERRA_CAVE_ENTRANCE                      = (104 | (24 << 8)),
    MAP_TERRA_CAVE_END                           = (105 | (24 << 8)),
    MAP_ALTERING_CAVE                            = (106 | (24 << 8)),
    MAP_METEOR_FALLS_STEVENS_CAVE                = (107 | (24 << 8)),
    MAP_ARTISAN_CAVE_PUZZLE_CHAMBER1             = (108 | (24 << 8)),
    MAP_ARTISAN_CAVE_PUZZLE_CHAMBER2             = (109 | (24 << 8)),
    MAP_ARTISAN_CAVE_PUZZLE_CHAMBER3             = (110 | (24 << 8)),
    MAP_ARTISAN_CAVE_PUZZLE_CHAMBER4             = (111 | (24 << 8)),
    MAP_ARTISAN_CAVE_PUZZLE_CHAMBER5             = (112 | (24 << 8)),
    MAP_ARTISAN_CAVE_PUZZLE_CHAMBER6             = (113 | (24 << 8)),
    MAP_DEWFORD_MEADOW                           = (114 | (24 << 8)),

    // gMapGroup_IndoorDynamic
    MAP_SECRET_BASE_RED_CAVE1       = (0 | (25 << 8)),
    MAP_SECRET_BASE_BROWN_CAVE1     = (1 | (25 << 8)),
    MAP_SECRET_BASE_BLUE_CAVE1      = (2 | (25 << 8)),
    MAP_SECRET_BASE_YELLOW_CAVE1    = (3 | (25 << 8)),
    MAP_SECRET_BASE_TREE1           = (4 | (25 << 8)),
    MAP_SECRET_BASE_SHRUB1          = (5 | (25 << 8)),
    MAP_SECRET_BASE_RED_CAVE2       = (6 | (25 << 8)),
    MAP_SECRET_BASE_BROWN_CAVE2     = (7 | (25 << 8)),
    MAP_SECRET_BASE_BLUE_CAVE2      = (8 | (25 << 8)),
    MAP_SECRET_BASE_YELLOW_CAVE2    = (9 | (25 << 8)),
    MAP_SECRET_BASE_TREE2           = (10 | (25 << 8)),
    MAP_SECRET_BASE_SHRUB2          = (11 | (25 << 8)),
    MAP_SECRET_BASE_RED_CAVE3       = (12 | (25 << 8)),
    MAP_SECRET_BASE_BROWN_CAVE3     = (13 | (25 << 8)),
    MAP_SECRET_BASE_BLUE_CAVE3      = (14 | (25 << 8)),
    MAP_SECRET_BASE_YELLOW_CAVE3    = (15 | (25 << 8)),
    MAP_SECRET_BASE_TREE3           = (16 | (25 << 8)),
    MAP_SECRET_BASE_SHRUB3          = (17 | (25 << 8)),
    MAP_SECRET_BASE_RED_CAVE4       = (18 | (25 << 8)),
    MAP_SECRET_BASE_BROWN_CAVE4     = (19 | (25 << 8)),
    MAP_SECRET_BASE_BLUE_CAVE4      = (20 | (25 << 8)),
    MAP_SECRET_BASE_YELLOW_CAVE4    = (21 | (25 << 8)),
    MAP_SECRET_BASE_TREE4           = (22 | (25 << 8)),
    MAP_SECRET_BASE_SHRUB4          = (23 | (25 << 8)),
    MAP_BATTLE_COLOSSEUM_2P         = (24 | (25 << 8)),
    MAP_TRADE_CENTER                = (25 | (25 << 8)),
    MAP_RECORD_CORNER               = (26 | (25 << 8)),
    MAP_BATTLE_COLOSSEUM_4P         = (27 | (25 << 8)),
    MAP_CONTEST_HALL                = (28 | (25 << 8)),
    MAP_UNUSED_CONTEST_HALL1        = (29 | (25 << 8)),
    MAP_UNUSED_CONTEST_HALL2        = (30 | (25 << 8)),
    MAP_UNUSED_CONTEST_HALL3        = (31 | (25 << 8)),
    MAP_UNUSED_CONTEST_HALL4        = (32 | (25 << 8)),
    MAP_UNUSED_CONTEST_HALL5        = (33 | (25 << 8)),
    MAP_UNUSED_CONTEST_HALL6        = (34 | (25 << 8)),
    MAP_CONTEST_HALL_BEAUTY         = (35 | (25 << 8)),
    MAP_CONTEST_HALL_TOUGH          = (36 | (25 << 8)),
    MAP_CONTEST_HALL_COOL           = (37 | (25 << 8)),
    MAP_CONTEST_HALL_SMART          = (38 | (25 << 8)),
    MAP_CONTEST_HALL_CUTE           = (39 | (25 << 8)),
    MAP_INSIDE_OF_TRUCK             = (40 | (25 << 8)),
    MAP_SS_TIDAL_CORRIDOR           = (41 | (25 << 8)),
    MAP_SS_TIDAL_LOWER_DECK         = (42 | (25 << 8)),
    MAP_SS_TIDAL_ROOMS              = (43 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE01     = (44 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE02     = (45 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE03     = (46 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE04     = (47 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE05     = (48 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE06     = (49 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE07     = (50 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE08     = (51 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE09     = (52 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE10     = (53 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE11     = (54 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE12     = (55 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE13     = (56 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE14     = (57 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE15     = (58 | (25 << 8)),
    MAP_BATTLE_PYRAMID_SQUARE16     = (59 | (25 << 8)),
    MAP_UNION_ROOM                  = (60 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE82       = (61 | (25 << 8)),
    MAP_HIDDEN_GROTTO_RESEDA_WOODS  = (62 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE85       = (63 | (25 << 8)),
    MAP_HIDDEN_GROTTO_QUARTZ_CAVE   = (64 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE93       = (65 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE96       = (66 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE92       = (67 | (25 << 8)),
    MAP_HIDDEN_GROTTO_SCARLET_WOODS = (68 | (25 << 8)),
    MAP_HIDDEN_GROTTO_MT_SHIRO      = (69 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE70       = (70 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE66       = (71 | (25 << 8)),
    MAP_HIDDEN_GROTTO_SHAMROCK_ISLE = (72 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE87       = (73 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE78       = (74 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE91       = (75 | (25 << 8)),
    MAP_HIDDEN_GROTTO_ROUTE97       = (76 | (25 << 8)),

    // gMapGroup_SpecialArea
    MAP_SAFARI_ZONE_NORTHWEST                           = (0 | (26 << 8)),
    MAP_SAFARI_ZONE_NORTH                               = (1 | (26 << 8)),
    MAP_SAFARI_ZONE_SOUTHWEST                           = (2 | (26 << 8)),
    MAP_SAFARI_ZONE_SOUTH                               = (3 | (26 << 8)),
    MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    = (4 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              = (5 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           = (6 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           = (7 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        = (8 | (26 << 8)),
    MAP_SOUTHERN_ISLAND_EXTERIOR                        = (9 | (26 << 8)),
    MAP_SOUTHERN_ISLAND_INTERIOR                        = (10 | (26 << 8)),
    MAP_SAFARI_ZONE_REST_HOUSE                          = (11 | (26 << 8)),
    MAP_SAFARI_ZONE_NORTHEAST                           = (12 | (26 << 8)),
    MAP_SAFARI_ZONE_SOUTHEAST                           = (13 | (26 << 8)),
    MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    = (14 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM = (15 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     = (16 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  = (17 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               = (18 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            = (19 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     = (20 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         = (21 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             = (22 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          = (23 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       = (24 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            = (25 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            = (26 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              = (27 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              = (28 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           = (29 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        = (30 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            = (31 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  = (32 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      = (33 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               = (34 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            = (35 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     = (36 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         = (37 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          = (38 | (26 << 8)),
    MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      = (39 | (26 << 8)),
    MAP_BATTLE_FRONTIER_RANKING_HALL                    = (40 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE1                         = (41 | (26 << 8)),
    MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         = (42 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE2                         = (43 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE3                         = (44 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE4                         = (45 | (26 << 8)),
    MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    = (46 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE5                         = (47 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE6                         = (48 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE7                         = (49 | (26 << 8)),
    MAP_BATTLE_FRONTIER_RECEPTION_GATE                  = (50 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE8                         = (51 | (26 << 8)),
    MAP_BATTLE_FRONTIER_LOUNGE9                         = (52 | (26 << 8)),
    MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               = (53 | (26 << 8)),
    MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               = (54 | (26 << 8)),
    MAP_BATTLE_FRONTIER_MART                            = (55 | (26 << 8)),
    MAP_FARAWAY_ISLAND_ENTRANCE                         = (56 | (26 << 8)),
    MAP_FARAWAY_ISLAND_INTERIOR                         = (57 | (26 << 8)),
    MAP_BIRTH_ISLAND_EXTERIOR                           = (58 | (26 << 8)),
    MAP_BIRTH_ISLAND_HARBOR                             = (59 | (26 << 8)),
    MAP_TRAINER_HILL_ENTRANCE                           = (60 | (26 << 8)),
    MAP_TRAINER_HILL_1F                                 = (61 | (26 << 8)),
    MAP_TRAINER_HILL_2F                                 = (62 | (26 << 8)),
    MAP_TRAINER_HILL_3F                                 = (63 | (26 << 8)),
    MAP_TRAINER_HILL_4F                                 = (64 | (26 << 8)),
    MAP_TRAINER_HILL_ROOF                               = (65 | (26 << 8)),
    MAP_NAVEL_ROCK_EXTERIOR                             = (66 | (26 << 8)),
    MAP_NAVEL_ROCK_HARBOR                               = (67 | (26 << 8)),
    MAP_NAVEL_ROCK_ENTRANCE                             = (68 | (26 << 8)),
    MAP_NAVEL_ROCK_B1F                                  = (69 | (26 << 8)),
    MAP_NAVEL_ROCK_FORK                                 = (70 | (26 << 8)),
    MAP_NAVEL_ROCK_UP1                                  = (71 | (26 << 8)),
    MAP_NAVEL_ROCK_UP2                                  = (72 | (26 << 8)),
    MAP_NAVEL_ROCK_UP3                                  = (73 | (26 << 8)),
    MAP_NAVEL_ROCK_UP4                                  = (74 | (26 << 8)),
    MAP_NAVEL_ROCK_TOP                                  = (75 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN01                               = (76 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN02                               = (77 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN03                               = (78 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN04                               = (79 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN05                               = (80 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN06                               = (81 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN07                               = (82 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN08                               = (83 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN09                               = (84 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN10                               = (85 | (26 << 8)),
    MAP_NAVEL_ROCK_DOWN11                               = (86 | (26 << 8)),
    MAP_NAVEL_ROCK_BOTTOM                               = (87 | (26 << 8)),
    MAP_TRAINER_HILL_ELEVATOR                           = (88 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_EXTERIOR                       = (89 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_HARBOR                         = (90 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_1F                             = (91 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_2F                             = (92 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_B1                             = (93 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_3F_WEST                        = (94 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_3F_EAST                        = (95 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_4F_WEST                        = (96 | (26 << 8)),
    MAP_PERENNIAL_PILLAR_4F_EAST                        = (97 | (26 << 8)),

    // gMapGroup_IndoorRoute104Prototype
    MAP_ROUTE104_PROTOTYPE                          = (0 | (27 << 8)),
    MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP = (1 | (27 << 8)),

    // gMapGroup_IndoorRoute109
    MAP_ROUTE109_SEASHORE_HOUSE = (0 | (28 << 8)),

    // gMapGroup_IndoorRoute110
    MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                = (0 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_END                     = (1 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                = (2 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 = (3 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 = (4 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 = (5 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 = (6 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 = (7 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 = (8 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 = (9 | (29 << 8)),
    MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 = (10 | (29 << 8)),
    MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE = (11 | (29 << 8)),
    MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE = (12 | (29 << 8)),

    // gMapGroup_IndoorRoute113
    MAP_ROUTE113_GLASS_WORKSHOP = (0 | (30 << 8)),

    // gMapGroup_IndoorRoute123
    MAP_ROUTE123_BERRY_MASTERS_HOUSE = (0 | (31 << 8)),

    // gMapGroup_IndoorRoute119
    MAP_ROUTE119_WEATHER_INSTITUTE_1F = (0 | (32 << 8)),
    MAP_ROUTE119_WEATHER_INSTITUTE_2F = (1 | (32 << 8)),
    MAP_ROUTE119_HOUSE                = (2 | (32 << 8)),

    // gMapGroup_IndoorRoute124
    MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE = (0 | (33 << 8)),

    // gMapGroup_IndoorUmberTown
    MAP_UMBER_TOWN_MALE_MCHOUSE      = (0 | (34 << 8)),
    MAP_UMBER_TOWN_MALE_MCHOUSE_2F   = (1 | (34 << 8)),
    MAP_UMBER_TOWN_FEMALE_MCHOUSE    = (2 | (34 << 8)),
    MAP_UMBER_TOWN_FEMALE_MCHOUSE_2F = (3 | (34 << 8)),
    MAP_UMBER_TOWN_JACE_HOUSE        = (4 | (34 << 8)),
    MAP_UMBER_TOWN_JACE_HOUSE_2F     = (5 | (34 << 8)),
    MAP_UMBER_TOWN_HAZELS_LAB        = (6 | (34 << 8)),

    // gMapGroup_IndoorCinerousTown
    MAP_CINEROUS_TOWN_POKEMON_CENTER    = (0 | (35 << 8)),
    MAP_CINEROUS_TOWN_MART              = (1 | (35 << 8)),
    MAP_CINEROUS_TOWN_HOUSE1            = (2 | (35 << 8)),
    MAP_CINEROUS_TOWN_HOUSE2            = (3 | (35 << 8)),
    MAP_CINEROUS_TOWN_POKEMON_CENTER_2F = (4 | (35 << 8)),

    // gMapGroup_IndoorXanthosCity
    MAP_XANTHOS_CITY_POKEMON_CENTER         = (0 | (36 << 8)),
    MAP_XANTHOS_CITY_MART                   = (1 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT1_1F               = (2 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT1_2F               = (3 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT1_3F               = (4 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT1_4F               = (5 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT2_1F               = (6 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT2_2F               = (7 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT2_3F               = (8 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT3_1F               = (9 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT3_2F               = (10 | (36 << 8)),
    MAP_XANTHOS_CITY_FLAT3_3F               = (11 | (36 << 8)),
    MAP_XANTHOS_CITY_HARBOR                 = (12 | (36 << 8)),
    MAP_XANTHOS_CITY_WEST_TUNNEL_ENTRANCE   = (13 | (36 << 8)),
    MAP_XANTHOS_CITY_EAST_TUNNEL_ENTRANCE   = (14 | (36 << 8)),
    MAP_XANTHOS_CITY_XANTHOS_UNDERGROUND    = (15 | (36 << 8)),
    MAP_XANTHOS_CITY_MAYS_HOUSE             = (16 | (36 << 8)),
    MAP_XANTHOS_CITY_LIBRARY_1F             = (17 | (36 << 8)),
    MAP_XANTHOS_CITY_LIBRARY_2F             = (18 | (36 << 8)),
    MAP_UNDERGROUND_CITY_ENTRANCE           = (19 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING1_1F       = (20 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING1_2F       = (21 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING1_3F       = (22 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING1_4F       = (23 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING2_1F       = (24 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING2_2F       = (25 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING2_3F       = (26 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING2_4F       = (27 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING3_1F       = (28 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING3_2F       = (29 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING3_3F       = (30 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING3_4F       = (31 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING4_1F       = (32 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING4_2F       = (33 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING5_1F       = (34 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING5_2F       = (35 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING6_1F       = (36 | (36 << 8)),
    MAP_UNDERGROUND_CITY_BUILDING6_2F       = (37 | (36 << 8)),
    MAP_UNDERGROUND_CITY_SEWER              = (38 | (36 << 8)),
    MAP_UNDERGROUND_CITY_SEWER_ROOMS        = (39 | (36 << 8)),
    MAP_UNDERGROUND_CITY_FINAL_ROOM         = (40 | (36 << 8)),
    MAP_UNDERGROUND_CITY_HALLWAY            = (41 | (36 << 8)),
    MAP_UNDERGROUND_CITY_ENTRANCE_AFTERMATH = (42 | (36 << 8)),
    MAP_XANTHOS_CITY_POKEMON_CENTER_2F      = (43 | (36 << 8)),
    MAP_XANTHOS_CITY_BATTLE_CAFE            = (44 | (36 << 8)),

    // gMapGroup_IndoorResedaTown
    MAP_RESEDA_TOWN_HOUSE1            = (0 | (37 << 8)),
    MAP_RESEDA_TOWN_HOUSE2            = (1 | (37 << 8)),
    MAP_RESEDA_TOWN_POKEMON_CENTER    = (2 | (37 << 8)),
    MAP_RESEDA_TOWN_MART              = (3 | (37 << 8)),
    MAP_RESEDA_TOWN_GYM               = (4 | (37 << 8)),
    MAP_RESEDA_TOWN_POKEMON_CENTER_2F = (5 | (37 << 8)),

    // gMapGroup_IndoorAmberCity
    MAP_AMBER_CITY_POKEMON_CENTER    = (0 | (38 << 8)),
    MAP_AMBER_CITY_MART              = (1 | (38 << 8)),
    MAP_AMBER_CITY_MUSEUM_1F         = (2 | (38 << 8)),
    MAP_AMBER_CITY_HOUSE1            = (3 | (38 << 8)),
    MAP_AMBER_CITY_HOUSE2            = (4 | (38 << 8)),
    MAP_AMBER_CITY_GYM               = (5 | (38 << 8)),
    MAP_AMBER_CITY_BIKE_SHOP         = (6 | (38 << 8)),
    MAP_AMBER_CITY_MUSEUM_B1         = (7 | (38 << 8)),
    MAP_AMBER_CITY_POKEMON_CENTER_2F = (8 | (38 << 8)),

    // gMapGroup_IndoorCobaltCity
    MAP_COBALT_CITY_POKEMON_CENTER        = (0 | (39 << 8)),
    MAP_COBALT_CITY_MART                  = (1 | (39 << 8)),
    MAP_COBALT_CITY_HARBOR                = (2 | (39 << 8)),
    MAP_COBALTY_CITY_DREAM_RESORT         = (3 | (39 << 8)),
    MAP_COBALT_CITY_DREAM_RESORT_2F       = (4 | (39 << 8)),
    MAP_COBALT_CITY_DREAM_RESORT_3F       = (5 | (39 << 8)),
    MAP_COBALT_CITY_DREAM_RESORT_4F       = (6 | (39 << 8)),
    MAP_COBALT_CITY_DREAM_RESORT_1F_ROOMS = (7 | (39 << 8)),
    MAP_COBALT_CITY_DREAM_RESORT_2F_ROOMS = (8 | (39 << 8)),
    MAP_COBALT_CITY_DREAM_RESORT_3F_ROOMS = (9 | (39 << 8)),
    MAP_COBALT_CITY_DREAM_RESORT_4F_ROOMS = (10 | (39 << 8)),
    MAP_COBALT_CITY_GYM                   = (11 | (39 << 8)),
    MAP_COBALT_CITY_HOUSE1                = (12 | (39 << 8)),
    MAP_COBALT_CITY_HOUSE2                = (13 | (39 << 8)),
    MAP_COBALT_CITY_HOUSE3                = (14 | (39 << 8)),
    MAP_COBALT_CITY_POKEMON_CENTER_2F     = (15 | (39 << 8)),

    // gMapGroup_IndoorRoute79
    MAP_ROUTE80_REST_STOP = (0 | (40 << 8)),

    // gMapGroup_IndoorRoute83
    MAP_ROUTE83_HYDROPLANT_1F = (0 | (41 << 8)),
    MAP_ROUTE83_HYDROPLANT_B1 = (1 | (41 << 8)),

    // gMapGroup_IndoorRoute84
    MAP_ROUTE84_HOUSE = (0 | (42 << 8)),

    // gMapGroup_IndoorRoute88
    MAP_ROUTE88_BERRY_HOUSE  = (0 | (43 << 8)),
    MAP_ROUTE88_SECRET_HOUSE = (1 | (43 << 8)),

    // gMapGroup_IsshoDungeons
    MAP_SHUCKLE_SPRING_1F                     = (0 | (44 << 8)),
    MAP_SHUCKLE_SPRING_B1F                    = (1 | (44 << 8)),
    MAP_SHUCKLE_SPRING_B2F                    = (2 | (44 << 8)),
    MAP_RESEDA_WOODS                          = (3 | (44 << 8)),
    MAP_POWER_STATION                         = (4 | (44 << 8)),
    MAP_QUARTZ_CAVE_1F                        = (5 | (44 << 8)),
    MAP_QUARTZ_CAVE_B1                        = (6 | (44 << 8)),
    MAP_QUARTZ_CAVE_B2                        = (7 | (44 << 8)),
    MAP_QUARTZ_CAVE_B3                        = (8 | (44 << 8)),
    MAP_QUARTZ_CAVE_B4                        = (9 | (44 << 8)),
    MAP_SANDSHRAF_1F                          = (10 | (44 << 8)),
    MAP_SANDSHRAF_B1                          = (11 | (44 << 8)),
    MAP_SANDSHRAF_B2                          = (12 | (44 << 8)),
    MAP_CINEROUS_TOWER_EXTERIOR               = (13 | (44 << 8)),
    MAP_CINEROUS_TOWER_1F                     = (14 | (44 << 8)),
    MAP_CINEROUS_TOWER_2F                     = (15 | (44 << 8)),
    MAP_CINEROUS_TOWER_3F                     = (16 | (44 << 8)),
    MAP_CINEROUS_TOWER_4F                     = (17 | (44 << 8)),
    MAP_CINEROUS_TOWER_5F                     = (18 | (44 << 8)),
    MAP_DREAM_RESORT_1F                       = (19 | (44 << 8)),
    MAP_DREAM_RESORT_2F                       = (20 | (44 << 8)),
    MAP_DREAM_RESORT_3F                       = (21 | (44 << 8)),
    MAP_DREAM_RESORT_4F                       = (22 | (44 << 8)),
    MAP_DREAM_RESORT_1F_ROOMS                 = (23 | (44 << 8)),
    MAP_DREAM_RESORT_2F_ROOMS                 = (24 | (44 << 8)),
    MAP_DREAM_RESORT_3F_ROOMS                 = (25 | (44 << 8)),
    MAP_DREAM_RESORT_4F_ROOMS                 = (26 | (44 << 8)),
    MAP_MERIDIA_TEMPLE_1F                     = (27 | (44 << 8)),
    MAP_AURORA_TEMPLE_1F                      = (28 | (44 << 8)),
    MAP_MEDIANOX_TEMPLE_1F                    = (29 | (44 << 8)),
    MAP_VESPER_TEMPLE_1F                      = (30 | (44 << 8)),
    MAP_MT_SHIRO_SUMMIT                       = (31 | (44 << 8)),
    MAP_MINDARO_GARDENS                       = (32 | (44 << 8)),
    MAP_MINDARO_GARDENS_MANSION_LOBBY         = (33 | (44 << 8)),
    MAP_MINDARO_GARDENS_MANSION_OFFICES       = (34 | (44 << 8)),
    MAP_MINDARO_GARDENS_MANSION_BALLROOM      = (35 | (44 << 8)),
    MAP_BROADCAST_TOWER_1F                    = (36 | (44 << 8)),
    MAP_BROADCAST_TOWER_2F                    = (37 | (44 << 8)),
    MAP_BROADCAST_TOWER_3F                    = (38 | (44 << 8)),
    MAP_BROADCAST_TOWER_4F                    = (39 | (44 << 8)),
    MAP_BROADCAST_TOWER_5F                    = (40 | (44 << 8)),
    MAP_SCARLET_WOODS_NORTH                   = (41 | (44 << 8)),
    MAP_SCARLET_WOODS_SOUTH                   = (42 | (44 << 8)),
    MAP_MT_SHIRO_EAST_CAVE                    = (43 | (44 << 8)),
    MAP_MT_SHIRO_NORTH_CAVE                   = (44 | (44 << 8)),
    MAP_MT_SHIRO_WEST_CAVE                    = (45 | (44 << 8)),
    MAP_MT_SHIRO_SOUTH_CAVE                   = (46 | (44 << 8)),
    MAP_MT_SHIRO_CENTRAL_ROOM                 = (47 | (44 << 8)),
    MAP_MT_SHIRO_UPPER_CAVE                   = (48 | (44 << 8)),
    MAP_SHAMROCK_ISLE_EXTERIOR                = (49 | (44 << 8)),
    MAP_SHAMROCK_ISLE_INTERIOR                = (50 | (44 << 8)),
    MAP_SUNKEN_ISLE_EXTERIOR                  = (51 | (44 << 8)),
    MAP_UNDERWATER_SUNKEN_ISLE_EXTERIOR       = (52 | (44 << 8)),
    MAP_SUNKEN_ISLE_INTERIOR                  = (53 | (44 << 8)),
    MAP_UNDERWATER_SUNKEN_ISLE_INTERIOR       = (54 | (44 << 8)),
    MAP_STEEL_MILL_1F                         = (55 | (44 << 8)),
    MAP_STEEL_MILL_B1                         = (56 | (44 << 8)),
    MAP_MIRAGE_PALACE_1F                      = (57 | (44 << 8)),
    MAP_MIRAGE_PALACE_2F                      = (58 | (44 << 8)),
    MAP_MIRAGE_PALACE_3F                      = (59 | (44 << 8)),
    MAP_MIRAGE_PALACE_4F                      = (60 | (44 << 8)),
    MAP_MIRAGE_PALACE_5F                      = (61 | (44 << 8)),
    MAP_MIRAGE_PALACE_ENTRANCE                = (62 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_1F_ISLAND1         = (63 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_1F_ISLAND2         = (64 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_1F_ISLAND3         = (65 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_1F_ISLAND4         = (66 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_B1_ISLAND1         = (67 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_B1_ISLAND2         = (68 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_B1_ISLAND3         = (69 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_B1_ISLAND4         = (70 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_UNDERWATER_ISLAND1 = (71 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_UNDERWATER_ISLAND2 = (72 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_UNDERWATER_ISLAND3 = (73 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_UNDERWATER_ISLAND4 = (74 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_B2                 = (75 | (44 << 8)),
    MAP_ISSHO_VICTORY_ROAD_FINAL_STAIRS       = (76 | (44 << 8)),
    MAP_MT_SHIRO_TUNNEL                       = (77 | (44 << 8)),
    MAP_POKEMON_LABORATORY_1F                 = (78 | (44 << 8)),
    MAP_POKEMON_LABORATORY_B1                 = (79 | (44 << 8)),
    MAP_DUSK_MOUNTAIN_WATERFALL_ROOM          = (80 | (44 << 8)),
    MAP_DUSK_MOUNTAIN_PIT_ROOM                = (81 | (44 << 8)),
    MAP_DUSK_MOUNTAIN_DEEP_BASEMENTS          = (82 | (44 << 8)),
    MAP_DUSK_MOUNTAIN_VOID_MAZE               = (83 | (44 << 8)),
    MAP_DUSK_MOUNTAIN_NORTH_CAVE              = (84 | (44 << 8)),
    MAP_POKEMON_LABORATORY_B2                 = (85 | (44 << 8)),
    MAP_UNDERGROUND_CITY                      = (86 | (44 << 8)),
    MAP_DUSK_MOUNTAIN_SOUTH_MAZE              = (87 | (44 << 8)),
    MAP_POKEMON_LABORATORY_B3                 = (88 | (44 << 8)),
    MAP_SANDSHRAF_TRIAL_ROOM                  = (89 | (44 << 8)),
    MAP_SHAMROCK_ISLE_SECRET_HOLLOW           = (90 | (44 << 8)),
    MAP_POKEMON_LABORATORY_PUZZLE_ROOM        = (91 | (44 << 8)),
    MAP_POWER_STATION_PUZZLE_ROOM             = (92 | (44 << 8)),

    // gMapGroup_IndoorTurquoiseCity
    MAP_TURQUOISE_CITY_POKEMON_CENTER_1F = (0 | (45 << 8)),
    MAP_TURQUOISE_CITY_MART              = (1 | (45 << 8)),
    MAP_TURQUOISE_CITY_HARBOR            = (2 | (45 << 8)),
    MAP_TURQUOISE_CITY_WAREHOUSE         = (3 | (45 << 8)),
    MAP_TURQUOISE_CITY_WAREHOUSE_B1      = (4 | (45 << 8)),
    MAP_TURQUOISE_CITY_HOUSE1            = (5 | (45 << 8)),
    MAP_TURQUOISE_CITY_HOUSE2            = (6 | (45 << 8)),
    MAP_TURQUOISE_CITY_HOUSE3            = (7 | (45 << 8)),
    MAP_TURQUOISE_CITY_HOUSE4            = (8 | (45 << 8)),
    MAP_TURQUOISE_CITY_GAME_CORNER       = (9 | (45 << 8)),
    MAP_TURQUOISE_CITY_POKEMON_CENTER_2F = (10 | (45 << 8)),

    // gMapGroup_IndoorMindaroCity
    MAP_MINDARO_CITY_POKEMON_CENTER_1F         = (0 | (46 << 8)),
    MAP_MINDARO_CITY_GYM                       = (1 | (46 << 8)),
    MAP_MINDARO_CITY_DEPARTMENT_STORE_1F       = (2 | (46 << 8)),
    MAP_MINDARO_CITY_DEPARTMENT_STORE_2F       = (3 | (46 << 8)),
    MAP_MINDARO_CITY_DEPARTMENT_STORE_3F       = (4 | (46 << 8)),
    MAP_MINDARO_CITY_DEPARTMENT_STORE_4F       = (5 | (46 << 8)),
    MAP_MINDARO_CITY_DEPARTMENT_STORE_5F       = (6 | (46 << 8)),
    MAP_MINDARO_CITY_DEPARTMENT_STORE_ROOF     = (7 | (46 << 8)),
    MAP_MINDARO_CITY_DEPARTMENT_STORE_B1       = (8 | (46 << 8)),
    MAP_MINDARO_CITY_DEPARTMENT_STORE_ELEVATOR = (9 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT1_1F                  = (10 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT2_1F                  = (11 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT3_1F                  = (12 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT1_2F                  = (13 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT2_2F                  = (14 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT3_2F                  = (15 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT1_3F                  = (16 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT2_3F                  = (17 | (46 << 8)),
    MAP_MINDARO_CITY_FLAT3_3F                  = (18 | (46 << 8)),
    MAP_MINDARO_CITY_POKEMON_CENTER_2F         = (19 | (46 << 8)),

    // gMapGroup_IndoorOffwiteTown
    MAP_OFFWITE_TOWN_CABLE_CAR_STATION = (0 | (47 << 8)),
    MAP_OFFWITE_TOWN_POKEMON_CENTER_1F = (1 | (47 << 8)),
    MAP_OFFWITE_TOWN_HOUSE1            = (2 | (47 << 8)),
    MAP_OFFWITE_TOWN_HOUSE2            = (3 | (47 << 8)),
    MAP_OFFWITE_TOWN_HOUSE3            = (4 | (47 << 8)),
    MAP_OFFWITE_TOWN_POKEMON_CENTER_2F = (5 | (47 << 8)),

    // gMapGroup_IndoorScarletTown
    MAP_SCARLET_TOWN_POKEMON_CENTER_1F = (0 | (48 << 8)),
    MAP_SCARLET_TOWN_MART              = (1 | (48 << 8)),
    MAP_SCARLET_TOWN_HOUSE1            = (2 | (48 << 8)),
    MAP_SCARLET_TOWN_HOUSE2            = (3 | (48 << 8)),
    MAP_SCARLET_TOWN_POKEMON_CENTER_2F = (4 | (48 << 8)),

    // gMapGroup_IndoorPitchblakCity
    MAP_PITCHBLAK_CITY_POKEMON_CENTER_1F            = (0 | (49 << 8)),
    MAP_PITCHBLAK_CITY_MART                         = (1 | (49 << 8)),
    MAP_PITCHBLAK_CITY_GYM                          = (2 | (49 << 8)),
    MAP_PITCHBLAK_CITY_PLAZA                        = (3 | (49 << 8)),
    MAP_PITCHBLAK_CITY_PLAZA_ROOF                   = (4 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_1F              = (5 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_2F              = (6 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_3F              = (7 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_4F              = (8 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_5F              = (9 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_6F              = (10 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_7F              = (11 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_8F              = (12 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_9F              = (13 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_10F             = (14 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_SECRET_BASEMENT = (15 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_LEFT_ELEVATOR   = (16 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_RIGHT_ELEVATOR  = (17 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_MIDDLE_ELEVATOR = (18 | (49 << 8)),
    MAP_PITCHBLAK_CITY_KENDOMA_CORP_SECRET_ELEVATOR = (19 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT1_1F                     = (20 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT1_2F                     = (21 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT2_1F                     = (22 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT2_2F                     = (23 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT3_1F                     = (24 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT3_2F                     = (25 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT4_1F                     = (26 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT4_2F                     = (27 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT5_1F                     = (28 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT5_2F                     = (29 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT6_1F                     = (30 | (49 << 8)),
    MAP_PITCHBLAK_CITY_FLAT6_2F                     = (31 | (49 << 8)),
    MAP_PITCHBLAK_CITY_POKEMON_CENTER_2F            = (32 | (49 << 8)),

    // gMapGroup_IndoorMaroonCity
    MAP_MAROON_CITY_POKEMON_CENTER_1F = (0 | (50 << 8)),
    MAP_MAROON_CITY_MART              = (1 | (50 << 8)),
    MAP_MAROON_CITY_GYM               = (2 | (50 << 8)),
    MAP_MAROON_CITY_FLAT1_1F          = (3 | (50 << 8)),
    MAP_MAROON_CITY_FLAT2_1F          = (4 | (50 << 8)),
    MAP_MAROON_CITY_FLAT1_2F          = (5 | (50 << 8)),
    MAP_MAROON_CITY_FLAT2_2F          = (6 | (50 << 8)),
    MAP_MAROON_CITY_FLAT1_3F          = (7 | (50 << 8)),
    MAP_MAROON_CITY_FLAT2_3F          = (8 | (50 << 8)),
    MAP_MAROON_CITY_POKEBALL_EMPORIUM = (9 | (50 << 8)),
    MAP_MAROON_CITY_RANGER_HQ_1F      = (10 | (50 << 8)),
    MAP_MAROON_CITY_RANGER_HQ_2F      = (11 | (50 << 8)),
    MAP_MAROON_CITY_RANGER_HQ_3F      = (12 | (50 << 8)),
    MAP_MAROON_CITY_POKEMON_CENTER_2F = (13 | (50 << 8)),

    // gMapGroup_IndoorRoute93
    MAP_ROUTE93_HOUSE1 = (0 | (51 << 8)),
    MAP_ROUTE93_HOUSE2 = (1 | (51 << 8)),

    // gMapGroup_IndoorRoute96
    MAP_ROUTE96_CABLE_CAR_STATION = (0 | (52 << 8)),

    // gMapGroup_IndoorHaewenTown
    MAP_HAEWEN_TOWN_POKEMON_CENTER_1F = (0 | (53 << 8)),
    MAP_HAEWEN_TOWN_HOUSE1            = (1 | (53 << 8)),
    MAP_HAEWEN_TOWN_HOUSE2            = (2 | (53 << 8)),
    MAP_HAEWEN_TOWN_MART              = (3 | (53 << 8)),
    MAP_HAEWEN_TOWN_GYM               = (4 | (53 << 8)),
    MAP_HAEWEN_TOWN_HOUSE3            = (5 | (53 << 8)),
    MAP_HAEWEN_TOWN_POKEMON_CENTER_2F = (6 | (53 << 8)),

    // gMapGroup_IndoorWisteriaCity
    MAP_WISTERIA_CITY_POKEMON_CENTER_1F = (0 | (54 << 8)),
    MAP_WISTERIA_CITY_MART              = (1 | (54 << 8)),
    MAP_WISTERIA_CITY_GYM               = (2 | (54 << 8)),
    MAP_WISTERIA_CITY_HOUSE1            = (3 | (54 << 8)),
    MAP_WISTERIA_CITY_HOUSE2            = (4 | (54 << 8)),
    MAP_WISTERIA_CITY_HOUSE3            = (5 | (54 << 8)),
    MAP_WISTERIA_CITY_HOUSE4            = (6 | (54 << 8)),
    MAP_WISTERIA_CITY_FLAT1_1F          = (7 | (54 << 8)),
    MAP_WISTERIA_CITY_FLAT1_2F          = (8 | (54 << 8)),
    MAP_WISTERIA_CITY_FLAT2_1F          = (9 | (54 << 8)),
    MAP_WISTERIA_CITY_FLAT2_2F          = (10 | (54 << 8)),
    MAP_WISTERIA_CITY_POKEMON_CENTER_2F = (11 | (54 << 8)),

    // gMapGroup_IndoorBurgundyTown
    MAP_BURGUNDY_TOWN_POKEMON_CENTER_1F = (0 | (55 << 8)),
    MAP_BURGUNDY_TOWN_HOUSE1            = (1 | (55 << 8)),
    MAP_BURGUNDY_TOWN_HOUSE2            = (2 | (55 << 8)),
    MAP_BURGUNDY_TOWN_HOUSE3            = (3 | (55 << 8)),
    MAP_BURGUNDY_TOWN_HOUSE4            = (4 | (55 << 8)),
    MAP_ROUTE65_SECRET_HOUSE            = (5 | (55 << 8)),
    MAP_BURGUNDY_TOWN_HOUSE5            = (6 | (55 << 8)),

    // gMapGroup_IndoorDunTown
    MAP_DUN_TOWN_POKEMON_CENTER_1F = (0 | (56 << 8)),
    MAP_DUN_TOWN_MOTEL_1F          = (1 | (56 << 8)),
    MAP_DUN_TOWN_MOTEL_2F          = (2 | (56 << 8)),
    MAP_DUN_TOWN_HOUSE1            = (3 | (56 << 8)),
    MAP_DUN_TOWN_HOUSE2            = (4 | (56 << 8)),
    MAP_DUN_TOWN_HOUSE3            = (5 | (56 << 8)),
    MAP_DUN_TOWN_POKEMON_CENTER_2F = (6 | (56 << 8)),

    // gMapGroup_IndoorRoute90
    MAP_ROUTE90_HOUSE1 = (0 | (57 << 8)),

    // gMapGroup_IndoorRoute68
    MAP_ROUTE68_HOUSE1 = (0 | (58 << 8)),

    // gMapGroup_XCosmopolis
    MAP_STATION_CITY              = (0 | (59 << 8)),
    MAP_STATION_RING              = (1 | (59 << 8)),
    MAP_STATION_CITY_BUILDING1_1F = (2 | (59 << 8)),
    MAP_STATION_CITY_BUILDING1_B1 = (3 | (59 << 8)),

    // gMapGroup_XStarfield

    // gMapGroup_XFunfair

    // gMapGroup_XPelago

    // gMapGroup_XHolt

    // gMapGroup_XGreenhouse

    // gMapGroup_XSlough

    // gMapGroup_XWaste

    // gMapGroup_XLabyrinth

    // gMapGroup_XCaldera

    // gMapGroup_XJungle

    // gMapGroup_XCloud

    // gMapGroup_XTundra

    // gMapGroup_XMere

    // gMapGroup_XRuin

    // gMapGroup_XSynestia

};

#define MAP_GROUPS_COUNT 75

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
