#ifndef GUARD_CONSTANTS_MOVES_H
#define GUARD_CONSTANTS_MOVES_H

enum __attribute__((packed)) Move
{
    MOVE_NONE = 0,
    MOVE_POUND = 1,
    MOVE_KARATE_CHOP = 2,
    MOVE_DOUBLE_SLAP = 3,
    MOVE_DOUBLESLAP = MOVE_DOUBLE_SLAP, // Pre-Gen VI name
    MOVE_COMET_PUNCH = 4,
    MOVE_MEGA_PUNCH = 5,
    MOVE_PAY_DAY = 6,
    MOVE_FIRE_PUNCH = 7,
    MOVE_ICE_PUNCH = 8,
    MOVE_THUNDER_PUNCH = 9,
    MOVE_THUNDERPUNCH = MOVE_THUNDER_PUNCH, // Pre-Gen VI name
    MOVE_SCRATCH = 10,
    MOVE_VISE_GRIP = 11,
    MOVE_VICEGRIP = MOVE_VISE_GRIP, // Pre-Gen VI name
    MOVE_VICE_GRIP = MOVE_VISE_GRIP, // Pre-Gen VIII name
    MOVE_GUILLOTINE = 12,
    MOVE_RAZOR_WIND = 13,
    MOVE_SWORDS_DANCE = 14,
    MOVE_CUT = 15,
    MOVE_GUST = 16,
    MOVE_WING_ATTACK = 17,
    MOVE_WHIRLWIND = 18,
    MOVE_FLY = 19,
    MOVE_BIND = 20,
    MOVE_SLAM = 21,
    MOVE_VINE_WHIP = 22,
    MOVE_STOMP = 23,
    MOVE_DOUBLE_KICK = 24,
    MOVE_MEGA_KICK = 25,
    MOVE_JUMP_KICK = 26,
    MOVE_ROLLING_KICK = 27,
    MOVE_SAND_ATTACK = 28,
    MOVE_HEADBUTT = 29,
    MOVE_HORN_ATTACK = 30,
    MOVE_FURY_ATTACK = 31,
    MOVE_HORN_DRILL = 32,
    MOVE_TACKLE = 33,
    MOVE_BODY_SLAM = 34,
    MOVE_WRAP = 35,
    MOVE_TAKE_DOWN = 36,
    MOVE_THRASH = 37,
    MOVE_DOUBLE_EDGE = 38,
    MOVE_TAIL_WHIP = 39,
    MOVE_POISON_STING = 40,
    MOVE_TWINEEDLE = 41,
    MOVE_PIN_MISSILE = 42,
    MOVE_LEER = 43,
    MOVE_BITE = 44,
    MOVE_GROWL = 45,
    MOVE_ROAR = 46,
    MOVE_SING = 47,
    MOVE_SUPERSONIC = 48,
    MOVE_SONIC_BOOM = 49,
    MOVE_SONICBOOM = MOVE_SONIC_BOOM, // Pre-Gen VI name
    MOVE_DISABLE = 50,
    MOVE_ACID = 51,
    MOVE_EMBER = 52,
    MOVE_FLAMETHROWER = 53,
    MOVE_MIST = 54,
    MOVE_WATER_GUN = 55,
    MOVE_HYDRO_PUMP = 56,
    MOVE_SURF = 57,
    MOVE_ICE_BEAM = 58,
    MOVE_BLIZZARD = 59,
    MOVE_PSYBEAM = 60,
    MOVE_BUBBLE_BEAM = 61,
    MOVE_BUBBLEBEAM = MOVE_BUBBLE_BEAM, // Pre-Gen VI name
    MOVE_AURORA_BEAM = 62,
    MOVE_HYPER_BEAM = 63,
    MOVE_PECK = 64,
    MOVE_DRILL_PECK = 65,
    MOVE_SUBMISSION = 66,
    MOVE_LOW_KICK = 67,
    MOVE_COUNTER = 68,
    MOVE_SEISMIC_TOSS = 69,
    MOVE_STRENGTH = 70,
    MOVE_ABSORB = 71,
    MOVE_MEGA_DRAIN = 72,
    MOVE_LEECH_SEED = 73,
    MOVE_GROWTH = 74,
    MOVE_RAZOR_LEAF = 75,
    MOVE_SOLAR_BEAM = 76,
    MOVE_SOLARBEAM = MOVE_SOLAR_BEAM, // Pre-Gen VI name
    MOVE_POISON_POWDER = 77,
    MOVE_POISONPOWDER = MOVE_POISON_POWDER, // Pre-Gen VI name
    MOVE_STUN_SPORE = 78,
    MOVE_SLEEP_POWDER = 79,
    MOVE_PETAL_DANCE = 80,
    MOVE_STRING_SHOT = 81,
    MOVE_DRAGON_RAGE = 82,
    MOVE_FIRE_SPIN = 83,
    MOVE_THUNDER_SHOCK = 84,
    MOVE_THUNDERSHOCK = MOVE_THUNDER_SHOCK, // Pre-Gen VI name
    MOVE_THUNDERBOLT = 85,
    MOVE_THUNDER_WAVE = 86,
    MOVE_THUNDER = 87,
    MOVE_ROCK_THROW = 88,
    MOVE_EARTHQUAKE = 89,
    MOVE_FISSURE = 90,
    MOVE_DIG = 91,
    MOVE_TOXIC = 92,
    MOVE_CONFUSION = 93,
    MOVE_PSYCHIC = 94,
    MOVE_HYPNOSIS = 95,
    MOVE_MEDITATE = 96,
    MOVE_AGILITY = 97,
    MOVE_QUICK_ATTACK = 98,
    MOVE_RAGE = 99,
    MOVE_TELEPORT = 100,
    MOVE_NIGHT_SHADE = 101,
    MOVE_MIMIC = 102,
    MOVE_SCREECH = 103,
    MOVE_DOUBLE_TEAM = 104,
    MOVE_RECOVER = 105,
    MOVE_HARDEN = 106,
    MOVE_MINIMIZE = 107,
    MOVE_SMOKESCREEN = 108,
    MOVE_CONFUSE_RAY = 109,
    MOVE_WITHDRAW = 110,
    MOVE_DEFENSE_CURL = 111,
    MOVE_BARRIER = 112,
    MOVE_LIGHT_SCREEN = 113,
    MOVE_HAZE = 114,
    MOVE_REFLECT = 115,
    MOVE_FOCUS_ENERGY = 116,
    MOVE_BIDE = 117,
    MOVE_METRONOME = 118,
    MOVE_MIRROR_MOVE = 119,
    MOVE_SELF_DESTRUCT = 120,
    MOVE_SELFDESTRUCT = MOVE_SELF_DESTRUCT, // Pre-Gen VI name
    MOVE_EGG_BOMB = 121,
    MOVE_LICK = 122,
    MOVE_SMOG = 123,
    MOVE_SLUDGE = 124,
    MOVE_BONE_CLUB = 125,
    MOVE_FIRE_BLAST = 126,
    MOVE_WATERFALL = 127,
    MOVE_CLAMP = 128,
    MOVE_SWIFT = 129,
    MOVE_SKULL_BASH = 130,
    MOVE_SPIKE_CANNON = 131,
    MOVE_CONSTRICT = 132,
    MOVE_AMNESIA = 133,
    MOVE_KINESIS = 134,
    MOVE_SOFT_BOILED = 135,
    MOVE_SOFTBOILED = MOVE_SOFT_BOILED, // Pre-Gen VI name
    MOVE_HIGH_JUMP_KICK = 136,
    MOVE_HI_JUMP_KICK = MOVE_HIGH_JUMP_KICK, // Pre-Gen VI name
    MOVE_GLARE = 137,
    MOVE_DREAM_EATER = 138,
    MOVE_POISON_GAS = 139,
    MOVE_BARRAGE = 140,
    MOVE_LEECH_LIFE = 141,
    MOVE_LOVELY_KISS = 142,
    MOVE_SKY_ATTACK = 143,
    MOVE_TRANSFORM = 144,
    MOVE_BUBBLE = 145,
    MOVE_DIZZY_PUNCH = 146,
    MOVE_SPORE = 147,
    MOVE_FLASH = 148,
    MOVE_PSYWAVE = 149,
    MOVE_SPLASH = 150,
    MOVE_ACID_ARMOR = 151,
    MOVE_CRABHAMMER = 152,
    MOVE_EXPLOSION = 153,
    MOVE_FURY_SWIPES = 154,
    MOVE_BONEMERANG = 155,
    MOVE_REST = 156,
    MOVE_ROCK_SLIDE = 157,
    MOVE_HYPER_FANG = 158,
    MOVE_SHARPEN = 159,
    MOVE_CONVERSION = 160,
    MOVE_TRI_ATTACK = 161,
    MOVE_SUPER_FANG = 162,
    MOVE_SLASH = 163,
    MOVE_SUBSTITUTE = 164,
    MOVE_STRUGGLE = 165,
    MOVES_COUNT_GEN1,

    // Gen 2
    MOVE_SKETCH = MOVES_COUNT_GEN1,
    MOVE_TRIPLE_KICK = 167,
    MOVE_THIEF = 168,
    MOVE_SPIDER_WEB = 169,
    MOVE_MIND_READER = 170,
    MOVE_NIGHTMARE = 171,
    MOVE_FLAME_WHEEL = 172,
    MOVE_SNORE = 173,
    MOVE_CURSE = 174,
    MOVE_FLAIL = 175,
    MOVE_CONVERSION_2 = 176,
    MOVE_AEROBLAST = 177,
    MOVE_COTTON_SPORE = 178,
    MOVE_REVERSAL = 179,
    MOVE_SPITE = 180,
    MOVE_POWDER_SNOW = 181,
    MOVE_PROTECT = 182,
    MOVE_MACH_PUNCH = 183,
    MOVE_SCARY_FACE = 184,
    MOVE_FEINT_ATTACK = 185,
    MOVE_FAINT_ATTACK = MOVE_FEINT_ATTACK, // Pre-Gen VI name
    MOVE_SWEET_KISS = 186,
    MOVE_BELLY_DRUM = 187,
    MOVE_SLUDGE_BOMB = 188,
    MOVE_MUD_SLAP = 189,
    MOVE_OCTAZOOKA = 190,
    MOVE_SPIKES = 191,
    MOVE_ZAP_CANNON = 192,
    MOVE_FORESIGHT = 193,
    MOVE_DESTINY_BOND = 194,
    MOVE_PERISH_SONG = 195,
    MOVE_ICY_WIND = 196,
    MOVE_DETECT = 197,
    MOVE_BONE_RUSH = 198,
    MOVE_LOCK_ON = 199,
    MOVE_OUTRAGE = 200,
    MOVE_SANDSTORM = 201,
    MOVE_GIGA_DRAIN = 202,
    MOVE_ENDURE = 203,
    MOVE_CHARM = 204,
    MOVE_ROLLOUT = 205,
    MOVE_FALSE_SWIPE = 206,
    MOVE_SWAGGER = 207,
    MOVE_MILK_DRINK = 208,
    MOVE_SPARK = 209,
    MOVE_FURY_CUTTER = 210,
    MOVE_STEEL_WING = 211,
    MOVE_MEAN_LOOK = 212,
    MOVE_ATTRACT = 213,
    MOVE_SLEEP_TALK = 214,
    MOVE_HEAL_BELL = 215,
    MOVE_RETURN = 216,
    MOVE_PRESENT = 217,
    MOVE_FRUSTRATION = 218,
    MOVE_SAFEGUARD = 219,
    MOVE_PAIN_SPLIT = 220,
    MOVE_SACRED_FIRE = 221,
    MOVE_MAGNITUDE = 222,
    MOVE_DYNAMIC_PUNCH = 223,
    MOVE_DYNAMICPUNCH = MOVE_DYNAMIC_PUNCH, // Pre-Gen VI name
    MOVE_MEGAHORN = 224,
    MOVE_DRAGON_BREATH = 225,
    MOVE_DRAGONBREATH = MOVE_DRAGON_BREATH, // Pre-Gen VI name
    MOVE_BATON_PASS = 226,
    MOVE_ENCORE = 227,
    MOVE_PURSUIT = 228,
    MOVE_RAPID_SPIN = 229,
    MOVE_SWEET_SCENT = 230,
    MOVE_IRON_TAIL = 231,
    MOVE_METAL_CLAW = 232,
    MOVE_VITAL_THROW = 233,
    MOVE_MORNING_SUN = 234,
    MOVE_SYNTHESIS = 235,
    MOVE_MOONLIGHT = 236,
    MOVE_HIDDEN_POWER = 237,
    MOVE_CROSS_CHOP = 238,
    MOVE_TWISTER = 239,
    MOVE_RAIN_DANCE = 240,
    MOVE_SUNNY_DAY = 241,
    MOVE_CRUNCH = 242,
    MOVE_MIRROR_COAT = 243,
    MOVE_PSYCH_UP = 244,
    MOVE_EXTREME_SPEED = 245,
    MOVE_EXTREMESPEED = MOVE_EXTREME_SPEED, // Pre-Gen VI name
    MOVE_ANCIENT_POWER = 246,
    MOVE_ANCIENTPOWER = MOVE_ANCIENT_POWER, // Pre-Gen VI name
    MOVE_SHADOW_BALL = 247,
    MOVE_FUTURE_SIGHT = 248,
    MOVE_ROCK_SMASH = 249,
    MOVE_WHIRLPOOL = 250,
    MOVE_BEAT_UP = 251,
    MOVES_COUNT_GEN2,

    // Gen 3
    MOVE_FAKE_OUT = MOVES_COUNT_GEN2,
    MOVE_UPROAR = 253,
    MOVE_STOCKPILE = 254,
    MOVE_SPIT_UP = 255,
    MOVE_SWALLOW = 256,
    MOVE_HEAT_WAVE = 257,
    MOVE_HAIL = 258,
    MOVE_TORMENT = 259,
    MOVE_FLATTER = 260,
    MOVE_WILL_O_WISP = 261,
    MOVE_MEMENTO = 262,
    MOVE_FACADE = 263,
    MOVE_FOCUS_PUNCH = 264,
    MOVE_SMELLING_SALTS = 265,
    MOVE_SMELLINGSALT = MOVE_SMELLING_SALTS, // Pre-Gen VI name
    MOVE_FOLLOW_ME = 266,
    MOVE_NATURE_POWER = 267,
    MOVE_CHARGE = 268,
    MOVE_TAUNT = 269,
    MOVE_HELPING_HAND = 270,
    MOVE_TRICK = 271,
    MOVE_ROLE_PLAY = 272,
    MOVE_WISH = 273,
    MOVE_ASSIST = 274,
    MOVE_INGRAIN = 275,
    MOVE_SUPERPOWER = 276,
    MOVE_MAGIC_COAT = 277,
    MOVE_RECYCLE = 278,
    MOVE_REVENGE = 279,
    MOVE_BRICK_BREAK = 280,
    MOVE_YAWN = 281,
    MOVE_KNOCK_OFF = 282,
    MOVE_ENDEAVOR = 283,
    MOVE_ERUPTION = 284,
    MOVE_SKILL_SWAP = 285,
    MOVE_IMPRISON = 286,
    MOVE_REFRESH = 287,
    MOVE_GRUDGE = 288,
    MOVE_SNATCH = 289,
    MOVE_SECRET_POWER = 290,
    MOVE_DIVE = 291,
    MOVE_ARM_THRUST = 292,
    MOVE_CAMOUFLAGE = 293,
    MOVE_TAIL_GLOW = 294,
    MOVE_LUSTER_PURGE = 295,
    MOVE_MIST_BALL = 296,
    MOVE_FEATHER_DANCE = 297,
    MOVE_FEATHERDANCE = MOVE_FEATHER_DANCE, // Pre-Gen VI name
    MOVE_TEETER_DANCE = 298,
    MOVE_BLAZE_KICK = 299,
    MOVE_MUD_SPORT = 300,
    MOVE_ICE_BALL = 301,
    MOVE_NEEDLE_ARM = 302,
    MOVE_SLACK_OFF = 303,
    MOVE_HYPER_VOICE = 304,
    MOVE_POISON_FANG = 305,
    MOVE_CRUSH_CLAW = 306,
    MOVE_BLAST_BURN = 307,
    MOVE_HYDRO_CANNON = 308,
    MOVE_METEOR_MASH = 309,
    MOVE_ASTONISH = 310,
    MOVE_WEATHER_BALL = 311,
    MOVE_AROMATHERAPY = 312,
    MOVE_FAKE_TEARS = 313,
    MOVE_AIR_CUTTER = 314,
    MOVE_OVERHEAT = 315,
    MOVE_ODOR_SLEUTH = 316,
    MOVE_ROCK_TOMB = 317,
    MOVE_SILVER_WIND = 318,
    MOVE_METAL_SOUND = 319,
    MOVE_GRASS_WHISTLE = 320,
    MOVE_GRASSWHISTLE = MOVE_GRASS_WHISTLE, // Pre-Gen VI name
    MOVE_TICKLE = 321,
    MOVE_COSMIC_POWER = 322,
    MOVE_WATER_SPOUT = 323,
    MOVE_SIGNAL_BEAM = 324,
    MOVE_SHADOW_PUNCH = 325,
    MOVE_EXTRASENSORY = 326,
    MOVE_SKY_UPPERCUT = 327,
    MOVE_SAND_TOMB = 328,
    MOVE_SHEER_COLD = 329,
    MOVE_MUDDY_WATER = 330,
    MOVE_BULLET_SEED = 331,
    MOVE_AERIAL_ACE = 332,
    MOVE_ICICLE_SPEAR = 333,
    MOVE_IRON_DEFENSE = 334,
    MOVE_BLOCK = 335,
    MOVE_HOWL = 336,
    MOVE_DRAGON_CLAW = 337,
    MOVE_FRENZY_PLANT = 338,
    MOVE_BULK_UP = 339,
    MOVE_BOUNCE = 340,
    MOVE_MUD_SHOT = 341,
    MOVE_POISON_TAIL = 342,
    MOVE_COVET = 343,
    MOVE_VOLT_TACKLE = 344,
    MOVE_MAGICAL_LEAF = 345,
    MOVE_WATER_SPORT = 346,
    MOVE_CALM_MIND = 347,
    MOVE_LEAF_BLADE = 348,
    MOVE_DRAGON_DANCE = 349,
    MOVE_ROCK_BLAST = 350,
    MOVE_SHOCK_WAVE = 351,
    MOVE_WATER_PULSE = 352,
    MOVE_DOOM_DESIRE = 353,
    MOVE_PSYCHO_BOOST = 354,
    MOVES_COUNT_GEN3,

    // Gen 4
    MOVE_ROOST = MOVES_COUNT_GEN3,
    MOVE_GRAVITY = 356,
    MOVE_MIRACLE_EYE = 357,
    MOVE_WAKE_UP_SLAP = 358,
    MOVE_HAMMER_ARM = 359,
    MOVE_GYRO_BALL = 360,
    MOVE_HEALING_WISH = 361,
    MOVE_BRINE = 362,
    MOVE_NATURAL_GIFT = 363,
    MOVE_FEINT = 364,
    MOVE_PLUCK = 365,
    MOVE_TAILWIND = 366,
    MOVE_ACUPRESSURE = 367,
    MOVE_METAL_BURST = 368,
    MOVE_U_TURN = 369,
    MOVE_CLOSE_COMBAT = 370,
    MOVE_PAYBACK = 371,
    MOVE_ASSURANCE = 372,
    MOVE_EMBARGO = 373,
    MOVE_FLING = 374,
    MOVE_PSYCHO_SHIFT = 375,
    MOVE_TRUMP_CARD = 376,
    MOVE_HEAL_BLOCK = 377,
    MOVE_WRING_OUT = 378,
    MOVE_POWER_TRICK = 379,
    MOVE_GASTRO_ACID = 380,
    MOVE_LUCKY_CHANT = 381,
    MOVE_ME_FIRST = 382,
    MOVE_COPYCAT = 383,
    MOVE_POWER_SWAP = 384,
    MOVE_GUARD_SWAP = 385,
    MOVE_PUNISHMENT = 386,
    MOVE_LAST_RESORT = 387,
    MOVE_WORRY_SEED = 388,
    MOVE_SUCKER_PUNCH = 389,
    MOVE_TOXIC_SPIKES = 390,
    MOVE_HEART_SWAP = 391,
    MOVE_AQUA_RING = 392,
    MOVE_MAGNET_RISE = 393,
    MOVE_FLARE_BLITZ = 394,
    MOVE_FORCE_PALM = 395,
    MOVE_AURA_SPHERE = 396,
    MOVE_ROCK_POLISH = 397,
    MOVE_POISON_JAB = 398,
    MOVE_DARK_PULSE = 399,
    MOVE_NIGHT_SLASH = 400,
    MOVE_AQUA_TAIL = 401,
    MOVE_SEED_BOMB = 402,
    MOVE_AIR_SLASH = 403,
    MOVE_X_SCISSOR = 404,
    MOVE_BUG_BUZZ = 405,
    MOVE_DRAGON_PULSE = 406,
    MOVE_DRAGON_RUSH = 407,
    MOVE_POWER_GEM = 408,
    MOVE_DRAIN_PUNCH = 409,
    MOVE_VACUUM_WAVE = 410,
    MOVE_FOCUS_BLAST = 411,
    MOVE_ENERGY_BALL = 412,
    MOVE_BRAVE_BIRD = 413,
    MOVE_EARTH_POWER = 414,
    MOVE_SWITCHEROO = 415,
    MOVE_GIGA_IMPACT = 416,
    MOVE_NASTY_PLOT = 417,
    MOVE_BULLET_PUNCH = 418,
    MOVE_AVALANCHE = 419,
    MOVE_ICE_SHARD = 420,
    MOVE_SHADOW_CLAW = 421,
    MOVE_THUNDER_FANG = 422,
    MOVE_ICE_FANG = 423,
    MOVE_FIRE_FANG = 424,
    MOVE_SHADOW_SNEAK = 425,
    MOVE_MUD_BOMB = 426,
    MOVE_PSYCHO_CUT = 427,
    MOVE_ZEN_HEADBUTT = 428,
    MOVE_MIRROR_SHOT = 429,
    MOVE_FLASH_CANNON = 430,
    MOVE_ROCK_CLIMB = 431,
    MOVE_DEFOG = 432,
    MOVE_TRICK_ROOM = 433,
    MOVE_DRACO_METEOR = 434,
    MOVE_DISCHARGE = 435,
    MOVE_LAVA_PLUME = 436,
    MOVE_LEAF_STORM = 437,
    MOVE_POWER_WHIP = 438,
    MOVE_ROCK_WRECKER = 439,
    MOVE_CROSS_POISON = 440,
    MOVE_GUNK_SHOT = 441,
    MOVE_IRON_HEAD = 442,
    MOVE_MAGNET_BOMB = 443,
    MOVE_STONE_EDGE = 444,
    MOVE_CAPTIVATE = 445,
    MOVE_STEALTH_ROCK = 446,
    MOVE_GRASS_KNOT = 447,
    MOVE_CHATTER = 448,
    MOVE_JUDGMENT = 449,
    MOVE_BUG_BITE = 450,
    MOVE_CHARGE_BEAM = 451,
    MOVE_WOOD_HAMMER = 452,
    MOVE_AQUA_JET = 453,
    MOVE_ATTACK_ORDER = 454,
    MOVE_DEFEND_ORDER = 455,
    MOVE_HEAL_ORDER = 456,
    MOVE_HEAD_SMASH = 457,
    MOVE_DOUBLE_HIT = 458,
    MOVE_ROAR_OF_TIME = 459,
    MOVE_SPACIAL_REND = 460,
    MOVE_LUNAR_DANCE = 461,
    MOVE_CRUSH_GRIP = 462,
    MOVE_MAGMA_STORM = 463,
    MOVE_DARK_VOID = 464,
    MOVE_SEED_FLARE = 465,
    MOVE_OMINOUS_WIND = 466,
    MOVE_SHADOW_FORCE = 467,
    MOVES_COUNT_GEN4,

    // Gen 5
    MOVE_HONE_CLAWS = MOVES_COUNT_GEN4,
    MOVE_WIDE_GUARD = 469,
    MOVE_GUARD_SPLIT = 470,
    MOVE_POWER_SPLIT = 471,
    MOVE_WONDER_ROOM = 472,
    MOVE_PSYSHOCK = 473,
    MOVE_VENOSHOCK = 474,
    MOVE_AUTOTOMIZE = 475,
    MOVE_RAGE_POWDER = 476,
    MOVE_TELEKINESIS = 477,
    MOVE_MAGIC_ROOM = 478,
    MOVE_SMACK_DOWN = 479,
    MOVE_STORM_THROW = 480,
    MOVE_FLAME_BURST = 481,
    MOVE_SLUDGE_WAVE = 482,
    MOVE_QUIVER_DANCE = 483,
    MOVE_HEAVY_SLAM = 484,
    MOVE_SYNCHRONOISE = 485,
    MOVE_ELECTRO_BALL = 486,
    MOVE_SOAK = 487,
    MOVE_FLAME_CHARGE = 488,
    MOVE_COIL = 489,
    MOVE_LOW_SWEEP = 490,
    MOVE_ACID_SPRAY = 491,
    MOVE_FOUL_PLAY = 492,
    MOVE_SIMPLE_BEAM = 493,
    MOVE_ENTRAINMENT = 494,
    MOVE_AFTER_YOU = 495,
    MOVE_ROUND = 496,
    MOVE_ECHOED_VOICE = 497,
    MOVE_CHIP_AWAY = 498,
    MOVE_CLEAR_SMOG = 499,
    MOVE_STORED_POWER = 500,
    MOVE_QUICK_GUARD = 501,
    MOVE_ALLY_SWITCH = 502,
    MOVE_SCALD = 503,
    MOVE_SHELL_SMASH = 504,
    MOVE_HEAL_PULSE = 505,
    MOVE_HEX = 506,
    MOVE_SKY_DROP = 507,
    MOVE_SHIFT_GEAR = 508,
    MOVE_CIRCLE_THROW = 509,
    MOVE_INCINERATE = 510,
    MOVE_QUASH = 511,
    MOVE_ACROBATICS = 512,
    MOVE_REFLECT_TYPE = 513,
    MOVE_RETALIATE = 514,
    MOVE_FINAL_GAMBIT = 515,
    MOVE_BESTOW = 516,
    MOVE_INFERNO = 517,
    MOVE_WATER_PLEDGE = 518,
    MOVE_FIRE_PLEDGE = 519,
    MOVE_GRASS_PLEDGE = 520,
    MOVE_VOLT_SWITCH = 521,
    MOVE_STRUGGLE_BUG = 522,
    MOVE_BULLDOZE = 523,
    MOVE_FROST_BREATH = 524,
    MOVE_DRAGON_TAIL = 525,
    MOVE_WORK_UP = 526,
    MOVE_ELECTROWEB = 527,
    MOVE_WILD_CHARGE = 528,
    MOVE_DRILL_RUN = 529,
    MOVE_DUAL_CHOP = 530,
    MOVE_HEART_STAMP = 531,
    MOVE_HORN_LEECH = 532,
    MOVE_SACRED_SWORD = 533,
    MOVE_RAZOR_SHELL = 534,
    MOVE_HEAT_CRASH = 535,
    MOVE_LEAF_TORNADO = 536,
    MOVE_STEAMROLLER = 537,
    MOVE_COTTON_GUARD = 538,
    MOVE_NIGHT_DAZE = 539,
    MOVE_PSYSTRIKE = 540,
    MOVE_TAIL_SLAP = 541,
    MOVE_HURRICANE = 542,
    MOVE_HEAD_CHARGE = 543,
    MOVE_GEAR_GRIND = 544,
    MOVE_SEARING_SHOT = 545,
    MOVE_TECHNO_BLAST = 546,
    MOVE_RELIC_SONG = 547,
    MOVE_SECRET_SWORD = 548,
    MOVE_GLACIATE = 549,
    MOVE_BOLT_STRIKE = 550,
    MOVE_BLUE_FLARE = 551,
    MOVE_FIERY_DANCE = 552,
    MOVE_FREEZE_SHOCK = 553,
    MOVE_ICE_BURN = 554,
    MOVE_SNARL = 555,
    MOVE_ICICLE_CRASH = 556,
    MOVE_V_CREATE = 557,
    MOVE_FUSION_FLARE = 558,
    MOVE_FUSION_BOLT = 559,
    MOVES_COUNT_GEN5,

    // Gen 6
    MOVE_FLYING_PRESS = MOVES_COUNT_GEN5,
    MOVE_MAT_BLOCK = 561,
    MOVE_BELCH = 562,
    MOVE_ROTOTILLER = 563,
    MOVE_STICKY_WEB = 564,
    MOVE_FELL_STINGER = 565,
    MOVE_PHANTOM_FORCE = 566,
    MOVE_TRICK_OR_TREAT = 567,
    MOVE_NOBLE_ROAR = 568,
    MOVE_ION_DELUGE = 569,
    MOVE_PARABOLIC_CHARGE = 570,
    MOVE_FORESTS_CURSE = 571,
    MOVE_PETAL_BLIZZARD = 572,
    MOVE_FREEZE_DRY = 573,
    MOVE_DISARMING_VOICE = 574,
    MOVE_PARTING_SHOT = 575,
    MOVE_TOPSY_TURVY = 576,
    MOVE_DRAINING_KISS = 577,
    MOVE_CRAFTY_SHIELD = 578,
    MOVE_FLOWER_SHIELD = 579,
    MOVE_GRASSY_TERRAIN = 580,
    MOVE_MISTY_TERRAIN = 581,
    MOVE_ELECTRIFY = 582,
    MOVE_PLAY_ROUGH = 583,
    MOVE_FAIRY_WIND = 584,
    MOVE_MOONBLAST = 585,
    MOVE_BOOMBURST = 586,
    MOVE_FAIRY_LOCK = 587,
    MOVE_KINGS_SHIELD = 588,
    MOVE_PLAY_NICE = 589,
    MOVE_CONFIDE = 590,
    MOVE_DIAMOND_STORM = 591,
    MOVE_STEAM_ERUPTION = 592,
    MOVE_HYPERSPACE_HOLE = 593,
    MOVE_WATER_SHURIKEN = 594,
    MOVE_MYSTICAL_FIRE = 595,
    MOVE_SPIKY_SHIELD = 596,
    MOVE_AROMATIC_MIST = 597,
    MOVE_EERIE_IMPULSE = 598,
    MOVE_VENOM_DRENCH = 599,
    MOVE_POWDER = 600,
    MOVE_GEOMANCY = 601,
    MOVE_MAGNETIC_FLUX = 602,
    MOVE_HAPPY_HOUR = 603,
    MOVE_ELECTRIC_TERRAIN = 604,
    MOVE_DAZZLING_GLEAM = 605,
    MOVE_CELEBRATE = 606,
    MOVE_HOLD_HANDS = 607,
    MOVE_BABY_DOLL_EYES = 608,
    MOVE_NUZZLE = 609,
    MOVE_HOLD_BACK = 610,
    MOVE_INFESTATION = 611,
    MOVE_POWER_UP_PUNCH = 612,
    MOVE_OBLIVION_WING = 613,
    MOVE_THOUSAND_ARROWS = 614,
    MOVE_THOUSAND_WAVES = 615,
    MOVE_LANDS_WRATH = 616,
    MOVE_LIGHT_OF_RUIN = 617,
    // ORAS Moves
    MOVE_ORIGIN_PULSE = 618,
    MOVE_PRECIPICE_BLADES = 619,
    MOVE_DRAGON_ASCENT = 620,
    MOVE_HYPERSPACE_FURY = 621,
    MOVES_COUNT_GEN6,

    // Gen 7
    MOVE_SHORE_UP = MOVES_COUNT_GEN6,
    MOVE_FIRST_IMPRESSION = 623,
    MOVE_BANEFUL_BUNKER = 624,
    MOVE_SPIRIT_SHACKLE = 625,
    MOVE_DARKEST_LARIAT = 626,
    MOVE_SPARKLING_ARIA = 627,
    MOVE_ICE_HAMMER = 628,
    MOVE_FLORAL_HEALING = 629,
    MOVE_HIGH_HORSEPOWER = 630,
    MOVE_STRENGTH_SAP = 631,
    MOVE_SOLAR_BLADE = 632,
    MOVE_LEAFAGE = 633,
    MOVE_SPOTLIGHT = 634,
    MOVE_TOXIC_THREAD = 635,
    MOVE_LASER_FOCUS = 636,
    MOVE_GEAR_UP = 637,
    MOVE_THROAT_CHOP = 638,
    MOVE_POLLEN_PUFF = 639,
    MOVE_ANCHOR_SHOT = 640,
    MOVE_PSYCHIC_TERRAIN = 641,
    MOVE_LUNGE = 642,
    MOVE_FIRE_LASH = 643,
    MOVE_POWER_TRIP = 644,
    MOVE_BURN_UP = 645,
    MOVE_SPEED_SWAP = 646,
    MOVE_SMART_STRIKE = 647,
    MOVE_PURIFY = 648,
    MOVE_REVELATION_DANCE = 649,
    MOVE_CORE_ENFORCER = 650,
    MOVE_TROP_KICK = 651,
    MOVE_INSTRUCT = 652,
    MOVE_BEAK_BLAST = 653,
    MOVE_CLANGING_SCALES = 654,
    MOVE_DRAGON_HAMMER = 655,
    MOVE_BRUTAL_SWING = 656,
    MOVE_AURORA_VEIL = 657,
    MOVE_SHELL_TRAP = 658,
    MOVE_FLEUR_CANNON = 659,
    MOVE_PSYCHIC_FANGS = 660,
    MOVE_STOMPING_TANTRUM = 661,
    MOVE_SHADOW_BONE = 662,
    MOVE_ACCELEROCK = 663,
    MOVE_LIQUIDATION = 664,
    MOVE_PRISMATIC_LASER = 665,
    MOVE_SPECTRAL_THIEF = 666,
    MOVE_SUNSTEEL_STRIKE = 667,
    MOVE_MOONGEIST_BEAM = 668,
    MOVE_TEARFUL_LOOK = 669,
    MOVE_ZING_ZAP = 670,
    MOVE_NATURES_MADNESS = 671,
    MOVE_MULTI_ATTACK = 672,
    // USUM Moves
    MOVE_MIND_BLOWN = 673,
    MOVE_PLASMA_FISTS = 674,
    MOVE_PHOTON_GEYSER = 675,
    // LGPE Moves
    MOVE_ZIPPY_ZAP = 676,
    MOVE_SPLISHY_SPLASH = 677,
    MOVE_FLOATY_FALL = 678,
    MOVE_PIKA_PAPOW = 679,
    MOVE_BOUNCY_BUBBLE = 680,
    MOVE_BUZZY_BUZZ = 681,
    MOVE_SIZZLY_SLIDE = 682,
    MOVE_GLITZY_GLOW = 683,
    MOVE_BADDY_BAD = 684,
    MOVE_SAPPY_SEED = 685,
    MOVE_FREEZY_FROST = 686,
    MOVE_SPARKLY_SWIRL = 687,
    MOVE_VEEVEE_VOLLEY = 688,
    MOVE_DOUBLE_IRON_BASH = 689,
    MOVES_COUNT_GEN7,

    // Gen 8
    MOVE_DYNAMAX_CANNON = MOVES_COUNT_GEN7,
    MOVE_SNIPE_SHOT = 691,
    MOVE_JAW_LOCK = 692,
    MOVE_STUFF_CHEEKS = 693,
    MOVE_NO_RETREAT = 694,
    MOVE_TAR_SHOT = 695,
    MOVE_MAGIC_POWDER = 696,
    MOVE_DRAGON_DARTS = 697,
    MOVE_TEATIME = 698,
    MOVE_OCTOLOCK = 699,
    MOVE_BOLT_BEAK = 700,
    MOVE_FISHIOUS_REND = 701,
    MOVE_COURT_CHANGE = 702,
    MOVE_CLANGOROUS_SOUL = 703,
    MOVE_BODY_PRESS = 704,
    MOVE_DECORATE = 705,
    MOVE_DRUM_BEATING = 706,
    MOVE_SNAP_TRAP = 707,
    MOVE_PYRO_BALL = 708,
    MOVE_BEHEMOTH_BLADE = 709,
    MOVE_BEHEMOTH_BASH = 710,
    MOVE_AURA_WHEEL = 711,
    MOVE_BREAKING_SWIPE = 712,
    MOVE_BRANCH_POKE = 713,
    MOVE_OVERDRIVE = 714,
    MOVE_APPLE_ACID = 715,
    MOVE_GRAV_APPLE = 716,
    MOVE_SPIRIT_BREAK = 717,
    MOVE_STRANGE_STEAM = 718,
    MOVE_LIFE_DEW = 719,
    MOVE_OBSTRUCT = 720,
    MOVE_FALSE_SURRENDER = 721,
    MOVE_METEOR_ASSAULT = 722,
    MOVE_ETERNABEAM = 723,
    MOVE_STEEL_BEAM = 724,
    // Isle of Armor Moves
    MOVE_EXPANDING_FORCE = 725,
    MOVE_STEEL_ROLLER = 726,
    MOVE_SCALE_SHOT = 727,
    MOVE_METEOR_BEAM = 728,
    MOVE_SHELL_SIDE_ARM = 729,
    MOVE_MISTY_EXPLOSION = 730,
    MOVE_GRASSY_GLIDE = 731,
    MOVE_RISING_VOLTAGE = 732,
    MOVE_TERRAIN_PULSE = 733,
    MOVE_SKITTER_SMACK = 734,
    MOVE_BURNING_JEALOUSY = 735,
    MOVE_LASH_OUT = 736,
    MOVE_POLTERGEIST = 737,
    MOVE_CORROSIVE_GAS = 738,
    MOVE_COACHING = 739,
    MOVE_FLIP_TURN = 740,
    MOVE_TRIPLE_AXEL = 741,
    MOVE_DUAL_WINGBEAT = 742,
    MOVE_SCORCHING_SANDS = 743,
    MOVE_JUNGLE_HEALING = 744,
    MOVE_WICKED_BLOW = 745,
    MOVE_SURGING_STRIKES = 746,
    // Crown Tundra Moves
    MOVE_THUNDER_CAGE = 747,
    MOVE_DRAGON_ENERGY = 748,
    MOVE_FREEZING_GLARE = 749,
    MOVE_FIERY_WRATH = 750,
    MOVE_THUNDEROUS_KICK = 751,
    MOVE_GLACIAL_LANCE = 752,
    MOVE_ASTRAL_BARRAGE = 753,
    MOVE_EERIE_SPELL = 754,
    // Legends: Arceus Moves
    MOVE_DIRE_CLAW = 755,
    MOVE_PSYSHIELD_BASH = 756,
    MOVE_POWER_SHIFT = 757,
    MOVE_STONE_AXE = 758,
    MOVE_SPRINGTIDE_STORM = 759,
    MOVE_MYSTICAL_POWER = 760,
    MOVE_RAGING_FURY = 761,
    MOVE_WAVE_CRASH = 762,
    MOVE_CHLOROBLAST = 763,
    MOVE_MOUNTAIN_GALE = 764,
    MOVE_VICTORY_DANCE = 765,
    MOVE_HEADLONG_RUSH = 766,
    MOVE_BARB_BARRAGE = 767,
    MOVE_ESPER_WING = 768,
    MOVE_BITTER_MALICE = 769,
    MOVE_SHELTER = 770,
    MOVE_TRIPLE_ARROWS = 771,
    MOVE_INFERNAL_PARADE = 772,
    MOVE_CEASELESS_EDGE = 773,
    MOVE_BLEAKWIND_STORM = 774,
    MOVE_WILDBOLT_STORM = 775,
    MOVE_SANDSEAR_STORM = 776,
    MOVE_LUNAR_BLESSING = 777,
    MOVE_TAKE_HEART = 778,
    MOVES_COUNT_GEN8,

    // Gen 9
    MOVE_TERA_BLAST = MOVES_COUNT_GEN8,
    MOVE_SILK_TRAP = 780,
    MOVE_AXE_KICK = 781,
    MOVE_LAST_RESPECTS = 782,
    MOVE_LUMINA_CRASH = 783,
    MOVE_ORDER_UP = 784,
    MOVE_JET_PUNCH = 785,
    MOVE_SPICY_EXTRACT = 786,
    MOVE_SPIN_OUT = 787,
    MOVE_POPULATION_BOMB = 788,
    MOVE_ICE_SPINNER = 789,
    MOVE_GLAIVE_RUSH = 790,
    MOVE_REVIVAL_BLESSING = 791,
    MOVE_SALT_CURE = 792,
    MOVE_TRIPLE_DIVE = 793,
    MOVE_MORTAL_SPIN = 794,
    MOVE_DOODLE = 795,
    MOVE_FILLET_AWAY = 796,
    MOVE_KOWTOW_CLEAVE = 797,
    MOVE_FLOWER_TRICK = 798,
    MOVE_TORCH_SONG = 799,
    MOVE_AQUA_STEP = 800,
    MOVE_RAGING_BULL = 801,
    MOVE_MAKE_IT_RAIN = 802,
    MOVE_RUINATION = 803,
    MOVE_COLLISION_COURSE = 804,
    MOVE_ELECTRO_DRIFT = 805,
    MOVE_SHED_TAIL = 806,
    MOVE_CHILLY_RECEPTION = 807,
    MOVE_TIDY_UP = 808,
    MOVE_SNOWSCAPE = 809,
    MOVE_POUNCE = 810,
    MOVE_TRAILBLAZE = 811,
    MOVE_CHILLING_WATER = 812,
    MOVE_HYPER_DRILL = 813,
    MOVE_TWIN_BEAM = 814,
    MOVE_RAGE_FIST = 815,
    MOVE_ARMOR_CANNON = 816,
    MOVE_BITTER_BLADE = 817,
    MOVE_DOUBLE_SHOCK = 818,
    MOVE_GIGATON_HAMMER = 819,
    MOVE_COMEUPPANCE = 820,
    MOVE_AQUA_CUTTER = 821,
    MOVE_BLAZING_TORQUE = 822,
    MOVE_WICKED_TORQUE = 823,
    MOVE_NOXIOUS_TORQUE = 824,
    MOVE_COMBAT_TORQUE = 825,
    MOVE_MAGICAL_TORQUE = 826,
    MOVE_PSYBLADE = 827,
    MOVE_HYDRO_STEAM = 828,
    // The Teal Mask Moves
    MOVE_BLOOD_MOON = 829,
    MOVE_MATCHA_GOTCHA = 830,
    MOVE_SYRUP_BOMB = 831,
    MOVE_IVY_CUDGEL = 832,
    // The Indigo Disk Moves
    MOVE_ELECTRO_SHOT = 833,
    MOVE_TERA_STARSTORM = 834,
    MOVE_FICKLE_BEAM = 835,
    MOVE_BURNING_BULWARK = 836,
    MOVE_THUNDERCLAP = 837,
    MOVE_MIGHTY_CLEAVE = 838,
    MOVE_TACHYON_CUTTER = 839,
    MOVE_HARD_PRESS = 840,
    MOVE_DRAGON_CHEER = 841,
    MOVE_ALLURING_VOICE = 842,
    MOVE_TEMPER_FLARE = 843,
    MOVE_SUPERCELL_SLAM = 844,
    MOVE_PSYCHIC_NOISE = 845,
    MOVE_UPPER_HAND = 846,
    MOVE_MALIGNANT_CHAIN = 847,
    MOVES_COUNT_GEN9,

    MOVES_COUNT_GF = MOVES_COUNT_GEN9,

// Tourmaline moves
    MOVE_ABRASE             = (MOVES_COUNT_GF + 0),
    MOVE_UV_BURST           = (MOVES_COUNT_GF + 1),
    MOVE_ACID_RAIN          = (MOVES_COUNT_GF + 2),
    MOVE_FULL_MOON          = (MOVES_COUNT_GF + 3),
    MOVE_SHORT_CIRCUIT      = (MOVES_COUNT_GF + 4),
    MOVE_SPIT_FIRE          = (MOVES_COUNT_GF + 5),
    MOVE_PRESCIENCE         = (MOVES_COUNT_GF + 6),
    MOVE_SHADOW_HAND        = (MOVES_COUNT_GF + 7),
    MOVE_SONIC_PULSE        = (MOVES_COUNT_GF + 8),
    MOVE_DOPPLER_CHARGE     = (MOVES_COUNT_GF + 9),
    MOVE_CACOPHONY          = (MOVES_COUNT_GF + 10),
    MOVE_WHITE_NOISE        = (MOVES_COUNT_GF + 11),
    MOVE_SHIELD_STRIKE      = (MOVES_COUNT_GF + 12),
    MOVE_SIREN_SONG         = (MOVES_COUNT_GF + 13),
    MOVE_REBOUND_ARMOR      = (MOVES_COUNT_GF + 14),
    MOVE_ARCANE_FORCE       = (MOVES_COUNT_GF + 15),
    MOVE_THAW               = (MOVES_COUNT_GF + 16),
    MOVE_BLUE_NOISE         = (MOVES_COUNT_GF + 17),
    MOVE_PANIC_ATTACK       = (MOVES_COUNT_GF + 18),
    MOVE_DARKNESS_DREAM     = (MOVES_COUNT_GF + 19),
    MOVE_FIEND_FIRE         = (MOVES_COUNT_GF + 20),
    MOVE_SONAR_WAVE         = (MOVES_COUNT_GF + 21),
    MOVE_PETRIFY            = (MOVES_COUNT_GF + 22),
    MOVE_ROTOTILL           = (MOVES_COUNT_GF + 23),
    MOVE_BLIGHT             = (MOVES_COUNT_GF + 24),
    MOVE_POLLENSPRAY        = (MOVES_COUNT_GF + 25),
    MOVE_PALEO_WAVE         = (MOVES_COUNT_GF + 26),
    MOVE_MANTRA             = (MOVES_COUNT_GF + 27),
    MOVE_OXIDIZE            = (MOVES_COUNT_GF + 28),
    MOVE_DISSONANT_PULSE    = (MOVES_COUNT_GF + 29),
    MOVE_SONIC_BURST        = (MOVES_COUNT_GF + 30),
    MOVE_AFTERSHOCK         = (MOVES_COUNT_GF + 31),
    MOVE_BEREND             = (MOVES_COUNT_GF + 32),
    MOVE_BILE_JUICE         = (MOVES_COUNT_GF + 33),
    MOVE_BILE_BREATH        = (MOVES_COUNT_GF + 34),
    MOVE_BILE_WIND          = (MOVES_COUNT_GF + 35),
    MOVE_TOXIC_BREATH       = (MOVES_COUNT_GF + 36),
    MOVE_TOXIC_WIND         = (MOVES_COUNT_GF + 37),
    MOVE_WITHER_BREATH      = (MOVES_COUNT_GF + 38),
    MOVE_WITHER_WIND        = (MOVES_COUNT_GF + 39),
    MOVE_DUST_DEVIL         = (MOVES_COUNT_GF + 40),
    MOVE_POWDERPUFF_PUNCH   = (MOVES_COUNT_GF + 41),
    MOVE_HARMONIZE          = (MOVES_COUNT_GF + 42),
    MOVE_DRAGON_DREAM       = (MOVES_COUNT_GF + 43),
    MOVE_MEGAHERTZ_FIST     = (MOVES_COUNT_GF + 44),
    MOVE_ILL_WILL           = (MOVES_COUNT_GF + 45),
    MOVE_PSYCHOSIS          = (MOVES_COUNT_GF + 46),
    MOVE_SHRIEK             = (MOVES_COUNT_GF + 47),
    MOVE_PITCH_BURST        = (MOVES_COUNT_GF + 48),
    MOVE_SHADOW_SNITHE      = (MOVES_COUNT_GF + 49),
    MOVE_VIBRATE            = (MOVES_COUNT_GF + 50),
    MOVE_WITHER             = (MOVES_COUNT_GF + 51),
    MOVE_CRYSTALIZE         = (MOVES_COUNT_GF + 52),
    MOVE_PHRENO_ATTACK      = (MOVES_COUNT_GF + 53),
    MOVE_SOMA_ATTACK        = (MOVES_COUNT_GF + 54),
    MOVE_MAELSTROM          = (MOVES_COUNT_GF + 55),
    MOVE_METAMORPHOSE       = (MOVES_COUNT_GF + 56),
    MOVE_AETHER_BEAM        = (MOVES_COUNT_GF + 57),
    MOVE_MACH_WAVE          = (MOVES_COUNT_GF + 58),
    MOVE_RESOUND            = (MOVES_COUNT_GF + 59),
    MOVE_HIGH_NOTE          = (MOVES_COUNT_GF + 60),
    MOVE_FAIRY_DUST         = (MOVES_COUNT_GF + 61),
    MOVE_FORCE_OF_WILL      = (MOVES_COUNT_GF + 62),
    MOVE_TEMPEST            = (MOVES_COUNT_GF + 63),
    MOVE_PHASE_SHIFT        = (MOVES_COUNT_GF + 64),
    MOVE_SAND_SPRAY         = (MOVES_COUNT_GF + 65),
    MOVE_ICE_SKATE          = (MOVES_COUNT_GF + 66),
    MOVE_WILD_FRENZY        = (MOVES_COUNT_GF + 67),
    MOVE_EAGLE_EYE          = (MOVES_COUNT_GF + 68),
    MOVE_ECHO_PULSE         = (MOVES_COUNT_GF + 69),
    MOVE_SALT_SPRAY         = (MOVES_COUNT_GF + 70),
    MOVE_WINDSTORM          = (MOVES_COUNT_GF + 71),
    MOVE_PRESSURE_WASHER    = (MOVES_COUNT_GF + 72),
    MOVE_GAMMA_DECAY        = (MOVES_COUNT_GF + 73),
    MOVE_SCOURGE_STINGER    = (MOVES_COUNT_GF + 74),
    MOVE_DRONE_WAVE         = (MOVES_COUNT_GF + 75),
    MOVE_ATTUNE             = (MOVES_COUNT_GF + 76),
    MOVE_OVERCLOCK          = (MOVES_COUNT_GF + 77),
    MOVE_MACH_FORCE         = (MOVES_COUNT_GF + 78),
    MOVE_THRENODY           = (MOVES_COUNT_GF + 79),
    MOVE_CHITINIZE          = (MOVES_COUNT_GF + 80),
    MOVE_SINGULARITY        = (MOVES_COUNT_GF + 81),
    MOVE_MIND_BREAK         = (MOVES_COUNT_GF + 82),
	MOVE_KALEIDO_TONGUE     = (MOVES_COUNT_GF + 83),

	MOVES_COUNT_TOURMALINE = (MOVES_COUNT_GF + 84),
	
	MOVES_COUNT = MOVES_COUNT_TOURMALINE,
	
    // Z Moves
    FIRST_Z_MOVE = MOVES_COUNT,
    MOVE_BREAKNECK_BLITZ = FIRST_Z_MOVE,
    MOVE_ALL_OUT_PUMMELING,
    MOVE_SUPERSONIC_SKYSTRIKE,
    MOVE_ACID_DOWNPOUR,
    MOVE_TECTONIC_RAGE,
    MOVE_CONTINENTAL_CRUSH,
    MOVE_SAVAGE_SPIN_OUT,
    MOVE_NEVER_ENDING_NIGHTMARE,
    MOVE_CORKSCREW_CRASH,
    MOVE_INFERNO_OVERDRIVE,
    MOVE_HYDRO_VORTEX,
    MOVE_BLOOM_DOOM,
    MOVE_GIGAVOLT_HAVOC,
    MOVE_SHATTERED_PSYCHE,
    MOVE_SUBZERO_SLAMMER,
    MOVE_DEVASTATING_DRAKE,
    MOVE_BLACK_HOLE_ECLIPSE,
    MOVE_TWINKLE_TACKLE,
    // Signature Z Moves
    MOVE_CATASTROPIKA,
    MOVE_10000000_VOLT_THUNDERBOLT,
    MOVE_10_000_000_VOLT_THUNDERBOLT = MOVE_10000000_VOLT_THUNDERBOLT,
    MOVE_STOKED_SPARKSURFER,
    MOVE_EXTREME_EVOBOOST,
    MOVE_PULVERIZING_PANCAKE,
    MOVE_GENESIS_SUPERNOVA,
    MOVE_SINISTER_ARROW_RAID,
    MOVE_MALICIOUS_MOONSAULT,
    MOVE_OCEANIC_OPERETTA,
    MOVE_SPLINTERED_STORMSHARDS,
    MOVE_LETS_SNUGGLE_FOREVER,
    MOVE_CLANGOROUS_SOULBLAZE,
    MOVE_GUARDIAN_OF_ALOLA,
    MOVE_SEARING_SUNRAZE_SMASH,
    MOVE_MENACING_MOONRAZE_MAELSTROM,
    MOVE_LIGHT_THAT_BURNS_THE_SKY,
    MOVE_SOUL_STEALING_7_STAR_STRIKE,
    LAST_Z_MOVE = MOVE_SOUL_STEALING_7_STAR_STRIKE,
    MOVES_COUNT_Z,

    // Max Moves
    FIRST_MAX_MOVE = MOVES_COUNT_Z,
    MOVE_MAX_GUARD = FIRST_MAX_MOVE,
    MOVE_MAX_STRIKE,
    MOVE_MAX_KNUCKLE,
    MOVE_MAX_AIRSTREAM,
    MOVE_MAX_OOZE,
    MOVE_MAX_QUAKE,
    MOVE_MAX_ROCKFALL,
    MOVE_MAX_FLUTTERBY,
    MOVE_MAX_PHANTASM,
    MOVE_MAX_STEELSPIKE,
    MOVE_MAX_FLARE,
    MOVE_MAX_GEYSER,
    MOVE_MAX_OVERGROWTH,
    MOVE_MAX_LIGHTNING,
    MOVE_MAX_MINDSTORM,
    MOVE_MAX_HAILSTORM,
    MOVE_MAX_WYRMWIND,
    MOVE_MAX_DARKNESS,
    MOVE_MAX_STARFALL,
    // Gigantamax Moves
    MOVE_G_MAX_VINE_LASH,
    MOVE_G_MAX_WILDFIRE,
    MOVE_G_MAX_CANNONADE,
    MOVE_G_MAX_BEFUDDLE,
    MOVE_G_MAX_VOLT_CRASH,
    MOVE_G_MAX_GOLD_RUSH,
    MOVE_G_MAX_CHI_STRIKE,
    MOVE_G_MAX_TERROR,
    MOVE_G_MAX_FOAM_BURST,
    MOVE_G_MAX_RESONANCE,
    MOVE_G_MAX_CUDDLE,
    MOVE_G_MAX_REPLENISH,
    MOVE_G_MAX_MALODOR,
    MOVE_G_MAX_MELTDOWN,
    MOVE_G_MAX_DRUM_SOLO,
    MOVE_G_MAX_FIREBALL,
    MOVE_G_MAX_HYDROSNIPE,
    MOVE_G_MAX_WIND_RAGE,
    MOVE_G_MAX_GRAVITAS,
    MOVE_G_MAX_STONESURGE,
    MOVE_G_MAX_VOLCALITH,
    MOVE_G_MAX_TARTNESS,
    MOVE_G_MAX_SWEETNESS,
    MOVE_G_MAX_SANDBLAST,
    MOVE_G_MAX_STUN_SHOCK,
    MOVE_G_MAX_CENTIFERNO,
    MOVE_G_MAX_SMITE,
    MOVE_G_MAX_SNOOZE,
    MOVE_G_MAX_FINALE,
    MOVE_G_MAX_STEELSURGE,
    MOVE_G_MAX_DEPLETION,
    MOVE_G_MAX_ONE_BLOW,
    MOVE_G_MAX_RAPID_FLOW,
    LAST_MAX_MOVE = MOVE_G_MAX_RAPID_FLOW,
    MOVES_COUNT_DYNAMAX,
    MOVES_COUNT_ALL = MOVES_COUNT_DYNAMAX,
};

#define MOVE_DEFAULT     0x3FFF // Used when creating a mon to be replaced by a level-up move (needs to be less than that 0x4000 because of VarGet)
#define MOVE_UNAVAILABLE 0xFFFF // Used for checks for moves affected by Disable, Mimic, etc.

/*
#define MOVES_COUNT_GEN7 690

// Gen 8 moves.
#define MOVE_DYNAMAX_CANNON 690
#define MOVE_SNIPE_SHOT 691
#define MOVE_JAW_LOCK 692
#define MOVE_STUFF_CHEEKS 693
#define MOVE_NO_RETREAT 694
#define MOVE_TAR_SHOT 695
#define MOVE_MAGIC_POWDER 696
#define MOVE_DRAGON_DARTS 697
#define MOVE_TEATIME 698
#define MOVE_OCTOLOCK 699
#define MOVE_BOLT_BEAK 700
#define MOVE_FISHIOUS_REND 701
#define MOVE_COURT_CHANGE 702
#define MOVE_CLANGOROUS_SOUL 703
#define MOVE_BODY_PRESS 704
#define MOVE_DECORATE 705
#define MOVE_DRUM_BEATING 706
#define MOVE_SNAP_TRAP 707
#define MOVE_PYRO_BALL 708
#define MOVE_BEHEMOTH_BLADE 709
#define MOVE_BEHEMOTH_BASH 710
#define MOVE_AURA_WHEEL 711
#define MOVE_BREAKING_SWIPE 712
#define MOVE_BRANCH_POKE 713
#define MOVE_OVERDRIVE 714
#define MOVE_APPLE_ACID 715
#define MOVE_GRAV_APPLE 716
#define MOVE_SPIRIT_BREAK 717
#define MOVE_STRANGE_STEAM 718
#define MOVE_LIFE_DEW 719
#define MOVE_OBSTRUCT 720
#define MOVE_FALSE_SURRENDER 721
#define MOVE_METEOR_ASSAULT 722
#define MOVE_ETERNABEAM 723
#define MOVE_STEEL_BEAM 724
// Isle of Armor Moves
#define MOVE_EXPANDING_FORCE 725
#define MOVE_STEEL_ROLLER 726
#define MOVE_SCALE_SHOT 727
#define MOVE_METEOR_BEAM 728
#define MOVE_SHELL_SIDE_ARM 729
#define MOVE_MISTY_EXPLOSION 730
#define MOVE_GRASSY_GLIDE 731
#define MOVE_RISING_VOLTAGE 732
#define MOVE_TERRAIN_PULSE 733
#define MOVE_SKITTER_SMACK 734
#define MOVE_BURNING_JEALOUSY 735
#define MOVE_LASH_OUT 736
#define MOVE_POLTERGEIST 737
#define MOVE_CORROSIVE_GAS 738
#define MOVE_COACHING 739
#define MOVE_FLIP_TURN 740
#define MOVE_TRIPLE_AXEL 741
#define MOVE_DUAL_WINGBEAT 742
#define MOVE_SCORCHING_SANDS 743
#define MOVE_JUNGLE_HEALING 744
#define MOVE_WICKED_BLOW 745
#define MOVE_SURGING_STRIKES 746
// Crown Tundra Moves
#define MOVE_THUNDER_CAGE 747
#define MOVE_DRAGON_ENERGY 748
#define MOVE_FREEZING_GLARE 749
#define MOVE_FIERY_WRATH 750
#define MOVE_THUNDEROUS_KICK 751
#define MOVE_GLACIAL_LANCE 752
#define MOVE_ASTRAL_BARRAGE 753
#define MOVE_EERIE_SPELL 754
// Legends: Arceus Moves
#define MOVE_DIRE_CLAW 755
#define MOVE_PSYSHIELD_BASH 756
#define MOVE_POWER_SHIFT 757
#define MOVE_STONE_AXE 758
#define MOVE_SPRINGTIDE_STORM 759
#define MOVE_MYSTICAL_POWER 760
#define MOVE_RAGING_FURY 761
#define MOVE_WAVE_CRASH 762
#define MOVE_CHLOROBLAST 763
#define MOVE_MOUNTAIN_GALE 764
#define MOVE_VICTORY_DANCE 765
#define MOVE_HEADLONG_RUSH 766
#define MOVE_BARB_BARRAGE 767
#define MOVE_ESPER_WING 768
#define MOVE_BITTER_MALICE 769
#define MOVE_SHELTER 770
#define MOVE_TRIPLE_ARROWS 771
#define MOVE_INFERNAL_PARADE 772
#define MOVE_CEASELESS_EDGE 773
#define MOVE_BLEAKWIND_STORM 774
#define MOVE_WILDBOLT_STORM 775
#define MOVE_SANDSEAR_STORM 776
#define MOVE_LUNAR_BLESSING 777
#define MOVE_TAKE_HEART 778

#define MOVES_COUNT_GEN8 779

// Gen 9 moves.
#define MOVE_TERA_BLAST 779
#define MOVE_SILK_TRAP 780
#define MOVE_AXE_KICK 781
#define MOVE_LAST_RESPECTS 782
#define MOVE_LUMINA_CRASH 783
#define MOVE_ORDER_UP 784
#define MOVE_JET_PUNCH 785
#define MOVE_SPICY_EXTRACT 786
#define MOVE_SPIN_OUT 787
#define MOVE_POPULATION_BOMB 788
#define MOVE_ICE_SPINNER 789
#define MOVE_GLAIVE_RUSH 790
#define MOVE_REVIVAL_BLESSING 791
#define MOVE_SALT_CURE 792
#define MOVE_TRIPLE_DIVE 793
#define MOVE_MORTAL_SPIN 794
#define MOVE_DOODLE 795
#define MOVE_FILLET_AWAY 796
#define MOVE_KOWTOW_CLEAVE 797
#define MOVE_FLOWER_TRICK 798
#define MOVE_TORCH_SONG 799
#define MOVE_AQUA_STEP 800
#define MOVE_RAGING_BULL 801
#define MOVE_MAKE_IT_RAIN 802
#define MOVE_RUINATION 803
#define MOVE_COLLISION_COURSE 804
#define MOVE_ELECTRO_DRIFT 805
#define MOVE_SHED_TAIL 806
#define MOVE_CHILLY_RECEPTION 807
#define MOVE_TIDY_UP 808
#define MOVE_SNOWSCAPE 809
#define MOVE_POUNCE 810
#define MOVE_TRAILBLAZE 811
#define MOVE_CHILLING_WATER 812
#define MOVE_HYPER_DRILL 813
#define MOVE_TWIN_BEAM 814
#define MOVE_RAGE_FIST 815
#define MOVE_ARMOR_CANNON 816
#define MOVE_BITTER_BLADE 817
#define MOVE_DOUBLE_SHOCK 818
#define MOVE_GIGATON_HAMMER 819
#define MOVE_COMEUPPANCE 820
#define MOVE_AQUA_CUTTER 821
#define MOVE_BLAZING_TORQUE 822
#define MOVE_WICKED_TORQUE 823
#define MOVE_NOXIOUS_TORQUE 824
#define MOVE_COMBAT_TORQUE 825
#define MOVE_MAGICAL_TORQUE 826
#define MOVE_PSYBLADE 827
#define MOVE_HYDRO_STEAM 828
// The Teal Mask Moves
#define MOVE_BLOOD_MOON 829
#define MOVE_MATCHA_GOTCHA 830
#define MOVE_SYRUP_BOMB 831
#define MOVE_IVY_CUDGEL 832
// The Indigo Disk Moves
#define MOVE_ELECTRO_SHOT 833
#define MOVE_TERA_STARSTORM 834
#define MOVE_FICKLE_BEAM 835
#define MOVE_BURNING_BULWARK 836
#define MOVE_THUNDERCLAP 837
#define MOVE_MIGHTY_CLEAVE 838
#define MOVE_TACHYON_CUTTER 839
#define MOVE_HARD_PRESS 840
#define MOVE_DRAGON_CHEER 841
#define MOVE_ALLURING_VOICE 842
#define MOVE_TEMPER_FLARE 843
#define MOVE_SUPERCELL_SLAM 844
#define MOVE_PSYCHIC_NOISE 845
#define MOVE_UPPER_HAND 846
#define MOVE_MALIGNANT_CHAIN 847

#define MOVES_COUNT_GEN9 848

// New moves
#define MOVE_ABRASE 849
#define MOVE_UV_BURST 850
#define MOVE_ACID_RAIN 851
#define MOVE_FULL_MOON 852
#define MOVE_SHORT_CIRCUIT 853
#define MOVE_SPIT_FIRE 854
#define MOVE_PRESCIENCE 855
#define MOVE_SHADOW_HAND 856
#define MOVE_SONIC_PULSE 857
#define MOVE_DOPPLER_CHARGE 858
#define MOVE_CACOPHONY 859
#define MOVE_WHITE_NOISE 860
#define MOVE_SHIELD_STRIKE 861
#define MOVE_SIREN_SONG 862
#define MOVE_REBOUND_ARMOR 863
#define MOVE_ARCANE_FORCE 864
#define MOVE_THAW 865
#define MOVE_BLUE_NOISE 866
#define MOVE_PANIC_ATTACK 867
#define MOVE_DARKNESS_DREAM 868
#define MOVE_FIEND_FIRE 869
#define MOVE_SONAR_WAVE 870
#define MOVE_PETRIFY 871
#define MOVE_ROTOTILL 872
#define MOVE_BLIGHT 873
#define MOVE_POLLENSPRAY 874
#define MOVE_PALEO_WAVE 875
#define MOVE_MANTRA 876
#define MOVE_OXIDIZE 877
#define MOVE_DISSONANT_PULSE 878
#define MOVE_SONIC_BURST 879
#define MOVE_AFTERSHOCK 880
#define MOVE_BEREND 881
#define MOVE_BILE_JUICE 882
#define MOVE_BILE_BREATH 883
#define MOVE_BILE_WIND 884
#define MOVE_TOXIC_BREATH 885
#define MOVE_TOXIC_WIND 886
#define MOVE_WITHER_BREATH 887
#define MOVE_WITHER_WIND 888
#define MOVE_DUST_DEVIL 889
#define MOVE_POWDERPUFF_PUNCH 890
#define MOVE_HARMONIZE 891
#define MOVE_DRAGON_DREAM 892
#define MOVE_MEGAHERTZ_FIST 893
#define MOVE_ILL_WILL 894
#define MOVE_PSYCHOSIS 895
#define MOVE_SHRIEK 896
#define MOVE_PITCH_BURST 897
#define MOVE_SHADOW_SNITHE 898
#define MOVE_VIBRATE 899
#define MOVE_WITHER 900
#define MOVE_CRYSTALIZE 901
#define MOVE_PHRENO_ATTACK 902
#define MOVE_SOMA_ATTACK 903
#define MOVE_MAELSTROM 904
#define MOVE_METAMORPHOSE 905
#define MOVE_AETHER_BEAM 906
#define MOVE_MACH_WAVE 907
#define MOVE_RESOUND 908
#define MOVE_HIGH_NOTE 909
#define MOVE_FAIRY_DUST 910
#define MOVE_FORCE_OF_WILL 911
#define MOVE_TEMPEST 912
#define MOVE_PHASE_SHIFT 913
#define MOVE_SAND_SPRAY 914
#define MOVE_ICE_SKATE 915
#define MOVE_WILD_FRENZY 916
#define MOVE_BURNING_BULWARK 917
#define MOVE_EAGLE_EYE 918
#define MOVE_ECHO_PULSE 919
#define MOVE_SALT_CANNON 920
#define MOVE_WINDSTORM 921
#define MOVE_PRESSURE_WASHER 922
#define MOVE_GAMMA_DECAY 923
#define MOVE_SCOURGE_STINGER 924
#define MOVE_DRONE_WAVE 925
#define MOVE_ATTUNE 926
#define MOVE_OVERCLOCK 927
#define MOVE_MACH_FORCE 928
#define MOVE_THRENODY 929
#define MOVE_CHITINIZE 930
#define MOVE_SINGULARITY 931
#define MOVE_MIND_BREAK 932
#define MOVE_KALEIDO_TONGUE 933

#define MOVES_COUNT_TOURMALINE 934


#define MOVES_COUNT         MOVES_COUNT_TOURMALINE

// Z Moves
#define MOVE_BREAKNECK_BLITZ (MOVES_COUNT + 0)
#define MOVE_ALL_OUT_PUMMELING (MOVES_COUNT + 1)
#define MOVE_SUPERSONIC_SKYSTRIKE (MOVES_COUNT + 2)
#define MOVE_ACID_DOWNPOUR (MOVES_COUNT + 3)
#define MOVE_TECTONIC_RAGE (MOVES_COUNT + 4)
#define MOVE_CONTINENTAL_CRUSH (MOVES_COUNT + 5)
#define MOVE_SAVAGE_SPIN_OUT (MOVES_COUNT + 6)
#define MOVE_NEVER_ENDING_NIGHTMARE (MOVES_COUNT + 7)
#define MOVE_CORKSCREW_CRASH (MOVES_COUNT + 8)
#define MOVE_INFERNO_OVERDRIVE (MOVES_COUNT + 9)
#define MOVE_HYDRO_VORTEX (MOVES_COUNT + 10)
#define MOVE_BLOOM_DOOM (MOVES_COUNT + 11)
#define MOVE_GIGAVOLT_HAVOC (MOVES_COUNT + 12)
#define MOVE_SHATTERED_PSYCHE (MOVES_COUNT + 13)
#define MOVE_SUBZERO_SLAMMER (MOVES_COUNT + 14)
#define MOVE_DEVASTATING_DRAKE (MOVES_COUNT + 15)
#define MOVE_BLACK_HOLE_ECLIPSE (MOVES_COUNT + 16)
#define MOVE_TWINKLE_TACKLE (MOVES_COUNT + 17)

// Signature Z Moves
#define MOVE_CATASTROPIKA (MOVES_COUNT + 18)
#define MOVE_10000000_VOLT_THUNDERBOLT (MOVES_COUNT + 19)
#define MOVE_10_000_000_VOLT_THUNDERBOLT MOVE_10000000_VOLT_THUNDERBOLT
#define MOVE_STOKED_SPARKSURFER (MOVES_COUNT + 20)
#define MOVE_EXTREME_EVOBOOST (MOVES_COUNT + 21)
#define MOVE_PULVERIZING_PANCAKE (MOVES_COUNT + 22)
#define MOVE_GENESIS_SUPERNOVA (MOVES_COUNT + 23)
#define MOVE_SINISTER_ARROW_RAID (MOVES_COUNT + 24)
#define MOVE_MALICIOUS_MOONSAULT (MOVES_COUNT + 25)
#define MOVE_OCEANIC_OPERETTA (MOVES_COUNT + 26)
#define MOVE_SPLINTERED_STORMSHARDS (MOVES_COUNT + 27)
#define MOVE_LETS_SNUGGLE_FOREVER (MOVES_COUNT + 28)
#define MOVE_CLANGOROUS_SOULBLAZE (MOVES_COUNT + 29)
#define MOVE_GUARDIAN_OF_ALOLA (MOVES_COUNT + 30)
#define MOVE_SEARING_SUNRAZE_SMASH (MOVES_COUNT + 31)
#define MOVE_MENACING_MOONRAZE_MAELSTROM (MOVES_COUNT + 32)
#define MOVE_LIGHT_THAT_BURNS_THE_SKY (MOVES_COUNT + 33)
#define MOVE_SOUL_STEALING_7_STAR_STRIKE (MOVES_COUNT + 34)

#define FIRST_Z_MOVE        MOVE_BREAKNECK_BLITZ
#define LAST_Z_MOVE         MOVE_SOUL_STEALING_7_STAR_STRIKE

#define MOVES_COUNT_Z       (LAST_Z_MOVE + 1)

//Max Moves
#define MOVE_MAX_GUARD          (FIRST_MAX_MOVE + 0)
#define MOVE_MAX_STRIKE         (FIRST_MAX_MOVE + 1)
#define MOVE_MAX_KNUCKLE        (FIRST_MAX_MOVE + 2)
#define MOVE_MAX_AIRSTREAM      (FIRST_MAX_MOVE + 3)
#define MOVE_MAX_OOZE           (FIRST_MAX_MOVE + 4)
#define MOVE_MAX_QUAKE          (FIRST_MAX_MOVE + 5)
#define MOVE_MAX_ROCKFALL       (FIRST_MAX_MOVE + 6)
#define MOVE_MAX_FLUTTERBY      (FIRST_MAX_MOVE + 7)
#define MOVE_MAX_PHANTASM       (FIRST_MAX_MOVE + 8)
#define MOVE_MAX_STEELSPIKE     (FIRST_MAX_MOVE + 9)
#define MOVE_MAX_FLARE          (FIRST_MAX_MOVE + 10)
#define MOVE_MAX_GEYSER         (FIRST_MAX_MOVE + 11)
#define MOVE_MAX_OVERGROWTH     (FIRST_MAX_MOVE + 12)
#define MOVE_MAX_LIGHTNING      (FIRST_MAX_MOVE + 13)
#define MOVE_MAX_MINDSTORM      (FIRST_MAX_MOVE + 14)
#define MOVE_MAX_HAILSTORM      (FIRST_MAX_MOVE + 15)
#define MOVE_MAX_WYRMWIND       (FIRST_MAX_MOVE + 16)
#define MOVE_MAX_DARKNESS       (FIRST_MAX_MOVE + 17)
#define MOVE_MAX_STARFALL       (FIRST_MAX_MOVE + 18)
// Gigantamax Moves
#define MOVE_G_MAX_VINE_LASH    (FIRST_MAX_MOVE + 19)
#define MOVE_G_MAX_WILDFIRE     (FIRST_MAX_MOVE + 20)
#define MOVE_G_MAX_CANNONADE    (FIRST_MAX_MOVE + 21)
#define MOVE_G_MAX_BEFUDDLE     (FIRST_MAX_MOVE + 22)
#define MOVE_G_MAX_VOLT_CRASH   (FIRST_MAX_MOVE + 23)
#define MOVE_G_MAX_GOLD_RUSH    (FIRST_MAX_MOVE + 24)
#define MOVE_G_MAX_CHI_STRIKE   (FIRST_MAX_MOVE + 25)
#define MOVE_G_MAX_TERROR       (FIRST_MAX_MOVE + 26)
#define MOVE_G_MAX_FOAM_BURST   (FIRST_MAX_MOVE + 27)
#define MOVE_G_MAX_RESONANCE    (FIRST_MAX_MOVE + 28)
#define MOVE_G_MAX_CUDDLE       (FIRST_MAX_MOVE + 29)
#define MOVE_G_MAX_REPLENISH    (FIRST_MAX_MOVE + 30)
#define MOVE_G_MAX_MALODOR      (FIRST_MAX_MOVE + 31)
#define MOVE_G_MAX_MELTDOWN     (FIRST_MAX_MOVE + 32)
#define MOVE_G_MAX_DRUM_SOLO    (FIRST_MAX_MOVE + 33)
#define MOVE_G_MAX_FIREBALL     (FIRST_MAX_MOVE + 34)
#define MOVE_G_MAX_HYDROSNIPE   (FIRST_MAX_MOVE + 35)
#define MOVE_G_MAX_WIND_RAGE    (FIRST_MAX_MOVE + 36)
#define MOVE_G_MAX_GRAVITAS     (FIRST_MAX_MOVE + 37)
#define MOVE_G_MAX_STONESURGE   (FIRST_MAX_MOVE + 38)
#define MOVE_G_MAX_VOLCALITH    (FIRST_MAX_MOVE + 39)
#define MOVE_G_MAX_TARTNESS     (FIRST_MAX_MOVE + 40)
#define MOVE_G_MAX_SWEETNESS    (FIRST_MAX_MOVE + 41)
#define MOVE_G_MAX_SANDBLAST    (FIRST_MAX_MOVE + 42)
#define MOVE_G_MAX_STUN_SHOCK   (FIRST_MAX_MOVE + 43)
#define MOVE_G_MAX_CENTIFERNO   (FIRST_MAX_MOVE + 44)
#define MOVE_G_MAX_SMITE        (FIRST_MAX_MOVE + 45)
#define MOVE_G_MAX_SNOOZE       (FIRST_MAX_MOVE + 46)
#define MOVE_G_MAX_FINALE       (FIRST_MAX_MOVE + 47)
#define MOVE_G_MAX_STEELSURGE   (FIRST_MAX_MOVE + 48)
#define MOVE_G_MAX_DEPLETION    (FIRST_MAX_MOVE + 49)
#define MOVE_G_MAX_ONE_BLOW     (FIRST_MAX_MOVE + 50)
#define MOVE_G_MAX_RAPID_FLOW   (FIRST_MAX_MOVE + 51)

#define FIRST_MAX_MOVE        MOVES_COUNT_Z
#define LAST_MAX_MOVE         MOVE_G_MAX_RAPID_FLOW

#define MOVES_COUNT_DYNAMAX       (LAST_MAX_MOVE + 1)

#define MOVES_COUNT_ALL         MOVES_COUNT_DYNAMAX

// Used for checks for moves affected by Disable, Mimic, etc.
#define MOVE_UNAVAILABLE 0xFFFF
*/

#endif  // GUARD_CONSTANTS_MOVES_H
