#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#include "constants/opponents_frlg.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE_1                   9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_GRUNT_WEATHER_INST_2         18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_MATT                         30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_ROSE_2                       40
#define TRAINER_ROSE_3                       41
#define TRAINER_ROSE_4                       42
#define TRAINER_ROSE_5                       43
#define TRAINER_DUSTY_1                      44
#define TRAINER_CHIP                         45
#define TRAINER_FOSTER                       46
#define TRAINER_DUSTY_2                      47
#define TRAINER_DUSTY_3                      48
#define TRAINER_DUSTY_4                      49
#define TRAINER_DUSTY_5                      50
#define TRAINER_GABBY_AND_TY_1               51
#define TRAINER_GABBY_AND_TY_2               52
#define TRAINER_GABBY_AND_TY_3               53
#define TRAINER_GABBY_AND_TY_4               54
#define TRAINER_GABBY_AND_TY_5               55
#define TRAINER_GABBY_AND_TY_6               56
#define TRAINER_LOLA_1                       57
#define TRAINER_AUSTINA                      58
#define TRAINER_GWEN                         59
#define TRAINER_LOLA_2                       60
#define TRAINER_LOLA_3                       61
#define TRAINER_LOLA_4                       62
#define TRAINER_LOLA_5                       63
#define TRAINER_RICKY_1                      64
#define TRAINER_SIMON                        65
#define TRAINER_CHARLIE                      66
#define TRAINER_RICKY_2                      67
#define TRAINER_RICKY_3                      68
#define TRAINER_RICKY_4                      69
#define TRAINER_RICKY_5                      70
#define TRAINER_RANDALL                      71
#define TRAINER_PARKER                       72
#define TRAINER_GEORGE                       73
#define TRAINER_BERKE                        74
#define TRAINER_BRAXTON                      75
#define TRAINER_VINCENT                      76
#define TRAINER_LEROY                        77
#define TRAINER_WILTON_1                     78
#define TRAINER_EDGAR                        79
#define TRAINER_ALBERT                       80
#define TRAINER_SAMUEL                       81
#define TRAINER_VITO                         82
#define TRAINER_OWEN                         83
#define TRAINER_WILTON_2                     84
#define TRAINER_WILTON_3                     85
#define TRAINER_WILTON_4                     86
#define TRAINER_WILTON_5                     87
#define TRAINER_WARREN                       88
#define TRAINER_MARY                         89
#define TRAINER_ALEXIA                       90
#define TRAINER_JODY                         91
#define TRAINER_WENDY                        92
#define TRAINER_KEIRA                        93
#define TRAINER_BROOKE_1                     94
#define TRAINER_JENNIFER                     95
#define TRAINER_HOPE                         96
#define TRAINER_SHANNON                      97
#define TRAINER_MICHELLE                     98
#define TRAINER_CAROLINE                     99
#define TRAINER_JULIE                       100
#define TRAINER_BROOKE_2                    101
#define TRAINER_BROOKE_3                    102
#define TRAINER_BROOKE_4                    103
#define TRAINER_BROOKE_5                    104
#define TRAINER_PATRICIA                    105
#define TRAINER_KINDRA                      106
#define TRAINER_TAMMY                       107
#define TRAINER_VALERIE_1                   108
#define TRAINER_TASHA                       109
#define TRAINER_VALERIE_2                   110
#define TRAINER_VALERIE_3                   111
#define TRAINER_VALERIE_4                   112
#define TRAINER_VALERIE_5                   113
#define TRAINER_CINDY_1                     114
#define TRAINER_DAPHNE                      115
#define TRAINER_GRUNT_SPACE_CENTER_2        116
#define TRAINER_CINDY_2                     117
#define TRAINER_BRIANNA                     118
#define TRAINER_NAOMI                       119
#define TRAINER_CINDY_3                     120
#define TRAINER_CINDY_4                     121
#define TRAINER_CINDY_5                     122
#define TRAINER_CINDY_6                     123
#define TRAINER_MELISSA                     124
#define TRAINER_SHEILA                      125
#define TRAINER_SHIRLEY                     126
#define TRAINER_JESSICA_1                   127
#define TRAINER_CONNIE                      128
#define TRAINER_BRIDGET                     129
#define TRAINER_OLIVIA                      130
#define TRAINER_TIFFANY                     131
#define TRAINER_JESSICA_2                   132
#define TRAINER_JESSICA_3                   133
#define TRAINER_JESSICA_4                   134
#define TRAINER_JESSICA_5                   135
#define TRAINER_WINSTON_1                   136
#define TRAINER_MOLLIE                      137
#define TRAINER_GARRET                      138
#define TRAINER_WINSTON_2                   139
#define TRAINER_WINSTON_3                   140
#define TRAINER_WINSTON_4                   141
#define TRAINER_WINSTON_5                   142
#define TRAINER_STEVE_1                     143
#define TRAINER_THALIA_1                    144
#define TRAINER_MARK                        145
#define TRAINER_GRUNT_MT_CHIMNEY_1          146
#define TRAINER_STEVE_2                     147
#define TRAINER_STEVE_3                     148
#define TRAINER_STEVE_4                     149
#define TRAINER_STEVE_5                     150
#define TRAINER_LUIS                        151
#define TRAINER_DOMINIK                     152
#define TRAINER_DOUGLAS                     153
#define TRAINER_DARRIN                      154
#define TRAINER_TONY_1                      155
#define TRAINER_JEROME                      156
#define TRAINER_MATTHEW                     157
#define TRAINER_DAVID                       158
#define TRAINER_SPENCER                     159
#define TRAINER_ROLAND                      160
#define TRAINER_NOLEN                       161
#define TRAINER_STAN                        162
#define TRAINER_BARRY                       163
#define TRAINER_DEAN                        164
#define TRAINER_RODNEY                      165
#define TRAINER_RICHARD                     166
#define TRAINER_HERMAN                      167
#define TRAINER_SANTIAGO                    168
#define TRAINER_GILBERT                     169
#define TRAINER_FRANKLIN                    170
#define TRAINER_KEVIN                       171
#define TRAINER_JACK                        172
#define TRAINER_DUDLEY                      173
#define TRAINER_CHAD                        174
#define TRAINER_TONY_2                      175
#define TRAINER_TONY_3                      176
#define TRAINER_TONY_4                      177
#define TRAINER_TONY_5                      178
#define TRAINER_TAKAO                       179
#define TRAINER_HITOSHI                     180
#define TRAINER_KIYO                        181
#define TRAINER_KOICHI                      182
#define TRAINER_NOB_1                       183
#define TRAINER_NOB_2                       184
#define TRAINER_NOB_3                       185
#define TRAINER_NOB_4                       186
#define TRAINER_NOB_5                       187
#define TRAINER_YUJI                        188
#define TRAINER_DAISUKE                     189
#define TRAINER_ATSUSHI                     190
#define TRAINER_KIRK                        191
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        192
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        193
#define TRAINER_SHAWN                       194
#define TRAINER_FERNANDO_1                  195
#define TRAINER_DALTON_1                    196
#define TRAINER_DALTON_2                    197
#define TRAINER_DALTON_3                    198
#define TRAINER_DALTON_4                    199
#define TRAINER_DALTON_5                    200
#define TRAINER_COLE                        201
#define TRAINER_JEFF                        202
#define TRAINER_AXLE                        203
#define TRAINER_JACE                        204
#define TRAINER_KEEGAN                      205
#define TRAINER_BERNIE_1                    206
#define TRAINER_BERNIE_2                    207
#define TRAINER_BERNIE_3                    208
#define TRAINER_BERNIE_4                    209
#define TRAINER_BERNIE_5                    210
#define TRAINER_DREW                        211
#define TRAINER_BEAU                        212
#define TRAINER_LARRY                       213
#define TRAINER_SHANE                       214
#define TRAINER_JUSTIN                      215
#define TRAINER_ETHAN_1                     216
#define TRAINER_AUTUMN                      217
#define TRAINER_TRAVIS                      218
#define TRAINER_ETHAN_2                     219
#define TRAINER_ETHAN_3                     220
#define TRAINER_ETHAN_4                     221
#define TRAINER_ETHAN_5                     222
#define TRAINER_BRENT                       223
#define TRAINER_DONALD                      224
#define TRAINER_TAYLOR                      225
#define TRAINER_JEFFREY_1                   226
#define TRAINER_DEREK                       227
#define TRAINER_JEFFREY_2                   228
#define TRAINER_JEFFREY_3                   229
#define TRAINER_JEFFREY_4                   230
#define TRAINER_JEFFREY_5                   231
#define TRAINER_EDWARD                      232
#define TRAINER_PRESTON                     233
#define TRAINER_VIRGIL                      234
#define TRAINER_BLAKE                       235
#define TRAINER_WILLIAM                     236
#define TRAINER_JOSHUA                      237
#define TRAINER_CAMERON_1                   238
#define TRAINER_CAMERON_2                   239
#define TRAINER_CAMERON_3                   240
#define TRAINER_CAMERON_4                   241
#define TRAINER_CAMERON_5                   242
#define TRAINER_JACLYN                      243
#define TRAINER_HANNAH                      244
#define TRAINER_SAMANTHA                    245
#define TRAINER_MAURA                       246
#define TRAINER_KAYLA                       247
#define TRAINER_ALEXIS                      248
#define TRAINER_JACKI_1                     249
#define TRAINER_JACKI_2                     250
#define TRAINER_JACKI_3                     251
#define TRAINER_JACKI_4                     252
#define TRAINER_JACKI_5                     253
#define TRAINER_WALTER_1                    254
#define TRAINER_MICAH                       255
#define TRAINER_THOMAS                      256
#define TRAINER_WALTER_2                    257
#define TRAINER_WALTER_3                    258
#define TRAINER_WALTER_4                    259
#define TRAINER_WALTER_5                    260
#define TRAINER_SIDNEY                      261
#define TRAINER_PHOEBE                      262
#define TRAINER_GLACIA                      263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE_1                   265
#define TRAINER_BRAWLY_1                    266
#define TRAINER_WATTSON_1                   267
#define TRAINER_FLANNERY_1                  268
#define TRAINER_NORMAN_1                    269
#define TRAINER_WINONA_1                    270
#define TRAINER_TATE_AND_LIZA_1             271
#define TRAINER_JUAN_1                      272
#define TRAINER_JERRY_1                     273
#define TRAINER_TED                         274
#define TRAINER_PAUL                        275
#define TRAINER_JERRY_2                     276
#define TRAINER_JERRY_3                     277
#define TRAINER_JERRY_4                     278
#define TRAINER_JERRY_5                     279
#define TRAINER_KAREN_1                     280
#define TRAINER_GEORGIA                     281
#define TRAINER_KAREN_2                     282
#define TRAINER_KAREN_3                     283
#define TRAINER_KAREN_4                     284
#define TRAINER_KAREN_5                     285
#define TRAINER_KATE_AND_JOY                286
#define TRAINER_ANNA_AND_MEG_1              287
#define TRAINER_ANNA_AND_MEG_2              288
#define TRAINER_ANNA_AND_MEG_3              289
#define TRAINER_ANNA_AND_MEG_4              290
#define TRAINER_ANNA_AND_MEG_5              291
#define TRAINER_VICTOR                      292
#define TRAINER_MIGUEL_1                    293
#define TRAINER_COLTON                      294
#define TRAINER_MIGUEL_2                    295
#define TRAINER_MIGUEL_3                    296
#define TRAINER_MIGUEL_4                    297
#define TRAINER_MIGUEL_5                    298
#define TRAINER_VICTORIA                    299
#define TRAINER_VANESSA                     300
#define TRAINER_BETHANY                     301
#define TRAINER_ISABEL_1                    302
#define TRAINER_ISABEL_2                    303
#define TRAINER_ISABEL_3                    304
#define TRAINER_ISABEL_4                    305
#define TRAINER_ISABEL_5                    306
#define TRAINER_TIMOTHY_1                   307
#define TRAINER_TIMOTHY_2                   308
#define TRAINER_TIMOTHY_3                   309
#define TRAINER_TIMOTHY_4                   310
#define TRAINER_TIMOTHY_5                   311
#define TRAINER_VICKY                       312
#define TRAINER_SHELBY_1                    313
#define TRAINER_SHELBY_2                    314
#define TRAINER_SHELBY_3                    315
#define TRAINER_SHELBY_4                    316
#define TRAINER_SHELBY_5                    317
#define TRAINER_CALVIN_1                    318
#define TRAINER_BILLY                       319
#define TRAINER_JOSH                        320
#define TRAINER_TOMMY                       321
#define TRAINER_JOEY                        322
#define TRAINER_BEN                         323
#define TRAINER_QUINCY                      324
#define TRAINER_KATELYNN                    325
#define TRAINER_JAYLEN                      326
#define TRAINER_DILLON                      327
#define TRAINER_CALVIN_2                    328
#define TRAINER_CALVIN_3                    329
#define TRAINER_CALVIN_4                    330
#define TRAINER_CALVIN_5                    331
#define TRAINER_EDDIE                       332
#define TRAINER_ALLEN                       333
#define TRAINER_TIMMY                       334
#define TRAINER_WALLACE                     335
#define TRAINER_ANDREW                      336
#define TRAINER_IVAN                        337
#define TRAINER_CLAUDE                      338
#define TRAINER_ELLIOT_1                    339
#define TRAINER_NED                         340
#define TRAINER_DALE                        341
#define TRAINER_NOLAN                       342
#define TRAINER_BARNY                       343
#define TRAINER_WADE                        344
#define TRAINER_CARTER                      345
#define TRAINER_ELLIOT_2                    346
#define TRAINER_ELLIOT_3                    347
#define TRAINER_ELLIOT_4                    348
#define TRAINER_ELLIOT_5                    349
#define TRAINER_RONALD                      350
#define TRAINER_JACOB                       351
#define TRAINER_ANTHONY                     352
#define TRAINER_BENJAMIN_1                  353
#define TRAINER_BENJAMIN_2                  354
#define TRAINER_BENJAMIN_3                  355
#define TRAINER_BENJAMIN_4                  356
#define TRAINER_BENJAMIN_5                  357
#define TRAINER_ABIGAIL_1                   358
#define TRAINER_JASMINE                     359
#define TRAINER_ABIGAIL_2                   360
#define TRAINER_ABIGAIL_3                   361
#define TRAINER_ABIGAIL_4                   362
#define TRAINER_ABIGAIL_5                   363
#define TRAINER_DYLAN_1                     364
#define TRAINER_DYLAN_2                     365
#define TRAINER_DYLAN_3                     366
#define TRAINER_DYLAN_4                     367
#define TRAINER_DYLAN_5                     368
#define TRAINER_MARIA_1                     369
#define TRAINER_MARIA_2                     370
#define TRAINER_MARIA_3                     371
#define TRAINER_MARIA_4                     372
#define TRAINER_MARIA_5                     373
#define TRAINER_CAMDEN                      374
#define TRAINER_DEMETRIUS                   375
#define TRAINER_ISAIAH_1                    376
#define TRAINER_PABLO_1                     377
#define TRAINER_CHASE                       378
#define TRAINER_ISAIAH_2                    379
#define TRAINER_ISAIAH_3                    380
#define TRAINER_ISAIAH_4                    381
#define TRAINER_ISAIAH_5                    382
#define TRAINER_ISOBEL                      383
#define TRAINER_DONNY                       384
#define TRAINER_TALIA                       385
#define TRAINER_KATELYN_1                   386
#define TRAINER_ALLISON                     387
#define TRAINER_KATELYN_2                   388
#define TRAINER_KATELYN_3                   389
#define TRAINER_KATELYN_4                   390
#define TRAINER_KATELYN_5                   391
#define TRAINER_NICOLAS_1                   392
#define TRAINER_NICOLAS_2                   393
#define TRAINER_NICOLAS_3                   394
#define TRAINER_NICOLAS_4                   395
#define TRAINER_NICOLAS_5                   396
#define TRAINER_AARON                       397
#define TRAINER_PERRY                       398
#define TRAINER_HUGH                        399
#define TRAINER_PHIL                        400
#define TRAINER_JARED                       401
#define TRAINER_HUMBERTO                    402
#define TRAINER_PRESLEY                     403
#define TRAINER_EDWARDO                     404
#define TRAINER_COLIN                       405
#define TRAINER_ROBERT_1                    406
#define TRAINER_BENNY                       407
#define TRAINER_CHESTER                     408
#define TRAINER_ROBERT_2                    409
#define TRAINER_ROBERT_3                    410
#define TRAINER_ROBERT_4                    411
#define TRAINER_ROBERT_5                    412
#define TRAINER_ALEX                        413
#define TRAINER_BECK                        414
#define TRAINER_YASU                        415
#define TRAINER_TAKASHI                     416
#define TRAINER_DIANNE                      417
#define TRAINER_JANI                        418
#define TRAINER_LAO_1                       419
#define TRAINER_LUNG                        420
#define TRAINER_LAO_2                       421
#define TRAINER_LAO_3                       422
#define TRAINER_LAO_4                       423
#define TRAINER_LAO_5                       424
#define TRAINER_JOCELYN                     425
#define TRAINER_LAURA                       426
#define TRAINER_CYNDY_1                     427
#define TRAINER_CORA                        428
#define TRAINER_PAULA                       429
#define TRAINER_CYNDY_2                     430
#define TRAINER_CYNDY_3                     431
#define TRAINER_CYNDY_4                     432
#define TRAINER_CYNDY_5                     433
#define TRAINER_MADELINE_1                  434
#define TRAINER_CLARISSA                    435
#define TRAINER_ANGELICA                    436
#define TRAINER_MADELINE_2                  437
#define TRAINER_MADELINE_3                  438
#define TRAINER_MADELINE_4                  439
#define TRAINER_MADELINE_5                  440
#define TRAINER_BEVERLY                     441
#define TRAINER_IMANI                       442
#define TRAINER_KYLA                        443
#define TRAINER_DENISE                      444
#define TRAINER_BETH                        445
#define TRAINER_TARA                        446
#define TRAINER_MISSY                       447
#define TRAINER_ALICE                       448
#define TRAINER_JENNY_1                     449
#define TRAINER_GRACE                       450
#define TRAINER_TANYA                       451
#define TRAINER_SHARON                      452
#define TRAINER_NIKKI                       453
#define TRAINER_BRENDA                      454
#define TRAINER_KATIE                       455
#define TRAINER_SUSIE                       456
#define TRAINER_KARA                        457
#define TRAINER_DANA                        458
#define TRAINER_SIENNA                      459
#define TRAINER_DEBRA                       460
#define TRAINER_LINDA                       461
#define TRAINER_KAYLEE                      462
#define TRAINER_LAUREL                      463
#define TRAINER_CARLEE                      464
#define TRAINER_JENNY_2                     465
#define TRAINER_JENNY_3                     466
#define TRAINER_JENNY_4                     467
#define TRAINER_JENNY_5                     468
#define TRAINER_HEIDI                       469
#define TRAINER_BECKY                       470
#define TRAINER_CAROL                       471
#define TRAINER_NANCY                       472
#define TRAINER_MARTHA                      473
#define TRAINER_DIANA_1                     474
#define TRAINER_CEDRIC                      475
#define TRAINER_IRENE                       476
#define TRAINER_DIANA_2                     477
#define TRAINER_DIANA_3                     478
#define TRAINER_DIANA_4                     479
#define TRAINER_DIANA_5                     480
#define TRAINER_AMY_AND_LIV_1               481
#define TRAINER_AMY_AND_LIV_2               482
#define TRAINER_GINA_AND_MIA_1              483
#define TRAINER_MIU_AND_YUKI                484
#define TRAINER_AMY_AND_LIV_3               485
#define TRAINER_GINA_AND_MIA_2              486
#define TRAINER_AMY_AND_LIV_4               487
#define TRAINER_AMY_AND_LIV_5               488
#define TRAINER_AMY_AND_LIV_6               489
#define TRAINER_HUEY                        490
#define TRAINER_EDMOND                      491
#define TRAINER_ERNEST_1                    492
#define TRAINER_DWAYNE                      493
#define TRAINER_PHILLIP                     494
#define TRAINER_LEONARD                     495
#define TRAINER_DUNCAN                      496
#define TRAINER_ERNEST_2                    497
#define TRAINER_ERNEST_3                    498
#define TRAINER_ERNEST_4                    499
#define TRAINER_ERNEST_5                    500
#define TRAINER_ELI                         501
#define TRAINER_ANNIKA                      502
#define TRAINER_JAZMYN                      503
#define TRAINER_JONAS                       504
#define TRAINER_KAYLEY                      505
#define TRAINER_AURON                       506
#define TRAINER_KELVIN                      507
#define TRAINER_MARLEY                      508
#define TRAINER_REYNA                       509
#define TRAINER_HUDSON                      510
#define TRAINER_CONOR                       511
#define TRAINER_EDWIN_1                     512
#define TRAINER_HECTOR                      513
#define TRAINER_TABITHA_MOSSDEEP            514
#define TRAINER_EDWIN_2                     515
#define TRAINER_EDWIN_3                     516
#define TRAINER_EDWIN_4                     517
#define TRAINER_EDWIN_5                     518
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   523
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   528
#define TRAINER_MAY_ROUTE_103_MUDKIP        529
#define TRAINER_MAY_ROUTE_110_MUDKIP        530
#define TRAINER_MAY_ROUTE_119_MUDKIP        531
#define TRAINER_MAY_ROUTE_103_TREECKO       532
#define TRAINER_MAY_ROUTE_110_TREECKO       533
#define TRAINER_MAY_ROUTE_119_TREECKO       534
#define TRAINER_MAY_ROUTE_103_TORCHIC       535
#define TRAINER_MAY_ROUTE_110_TORCHIC       536
#define TRAINER_MAY_ROUTE_119_TORCHIC       537
#define TRAINER_ISAAC_1                     538
#define TRAINER_DAVIS                       539
#define TRAINER_MITCHELL                    540
#define TRAINER_ISAAC_2                     541
#define TRAINER_ISAAC_3                     542
#define TRAINER_ISAAC_4                     543
#define TRAINER_ISAAC_5                     544
#define TRAINER_LYDIA_1                     545
#define TRAINER_HALLE                       546
#define TRAINER_GARRISON                    547
#define TRAINER_LYDIA_2                     548
#define TRAINER_LYDIA_3                     549
#define TRAINER_LYDIA_4                     550
#define TRAINER_LYDIA_5                     551
#define TRAINER_JACKSON_1                   552
#define TRAINER_LORENZO                     553
#define TRAINER_SEBASTIAN                   554
#define TRAINER_JACKSON_2                   555
#define TRAINER_JACKSON_3                   556
#define TRAINER_JACKSON_4                   557
#define TRAINER_JACKSON_5                   558
#define TRAINER_CATHERINE_1                 559
#define TRAINER_JENNA                       560
#define TRAINER_SOPHIA                      561
#define TRAINER_CATHERINE_2                 562
#define TRAINER_CATHERINE_3                 563
#define TRAINER_CATHERINE_4                 564
#define TRAINER_CATHERINE_5                 565
#define TRAINER_JULIO                       566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_GRUNT_UNUSED                568
#define TRAINER_GRUNT_MT_PYRE_4             569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_MARC                        571
#define TRAINER_BRENDEN                     572
#define TRAINER_LILITH                      573
#define TRAINER_CRISTIAN                    574
#define TRAINER_SYLVIA                      575
#define TRAINER_LEONARDO                    576
#define TRAINER_ATHENA                      577
#define TRAINER_HARRISON                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_CLARENCE                    580
#define TRAINER_TERRY                       581
#define TRAINER_NATE                        582
#define TRAINER_KATHLEEN                    583
#define TRAINER_CLIFFORD                    584
#define TRAINER_NICHOLAS                    585
#define TRAINER_GRUNT_SPACE_CENTER_3        586
#define TRAINER_GRUNT_SPACE_CENTER_4        587
#define TRAINER_GRUNT_SPACE_CENTER_5        588
#define TRAINER_GRUNT_SPACE_CENTER_6        589
#define TRAINER_GRUNT_SPACE_CENTER_7        590
#define TRAINER_MACEY                       591
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     593
#define TRAINER_PAXTON                      594
#define TRAINER_ISABELLA                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_TABITHA_MT_CHIMNEY          597
#define TRAINER_JONATHAN                    598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    599
#define TRAINER_MAY_RUSTBORO_MUDKIP         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_TIANA                       603
#define TRAINER_HALEY_1                     604
#define TRAINER_JANICE                      605
#define TRAINER_VIVI                        606
#define TRAINER_HALEY_2                     607
#define TRAINER_HALEY_3                     608
#define TRAINER_HALEY_4                     609
#define TRAINER_HALEY_5                     610
#define TRAINER_SALLY                       611
#define TRAINER_ROBIN                       612
#define TRAINER_ANDREA                      613
#define TRAINER_CRISSY                      614
#define TRAINER_RICK                        615
#define TRAINER_LYLE                        616
#define TRAINER_JOSE                        617
#define TRAINER_DOUG                        618
#define TRAINER_GREG                        619
#define TRAINER_KENT                        620
#define TRAINER_JAMES_1                     621
#define TRAINER_JAMES_2                     622
#define TRAINER_JAMES_3                     623
#define TRAINER_JAMES_4                     624
#define TRAINER_JAMES_5                     625
#define TRAINER_BRICE                       626
#define TRAINER_TRENT_1                     627
#define TRAINER_LENNY                       628
#define TRAINER_LUCAS_1                     629
#define TRAINER_ALAN                        630
#define TRAINER_CLARK                       631
#define TRAINER_ERIC                        632
#define TRAINER_LUCAS_2                     633
#define TRAINER_MIKE_1                      634
#define TRAINER_MIKE_2                      635
#define TRAINER_TRENT_2                     636
#define TRAINER_TRENT_3                     637
#define TRAINER_TRENT_4                     638
#define TRAINER_TRENT_5                     639
#define TRAINER_DEZ_AND_LUKE                640
#define TRAINER_LEA_AND_JED                 641
#define TRAINER_KIRA_AND_DAN_1              642
#define TRAINER_KIRA_AND_DAN_2              643
#define TRAINER_KIRA_AND_DAN_3              644
#define TRAINER_KIRA_AND_DAN_4              645
#define TRAINER_KIRA_AND_DAN_5              646
#define TRAINER_JOHANNA                     647
#define TRAINER_GERALD                      648
#define TRAINER_VIVIAN                      649
#define TRAINER_DANIELLE                    650
#define TRAINER_HIDEO                       651
#define TRAINER_KEIGO                       652
#define TRAINER_RILEY                       653
#define TRAINER_FLINT                       654
#define TRAINER_ASHLEY                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_VR_3                  658
#define TRAINER_WALLY_VR_4                  659
#define TRAINER_WALLY_VR_5                  660
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     661
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    662
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    663
#define TRAINER_MAY_LILYCOVE_MUDKIP         664
#define TRAINER_MAY_LILYCOVE_TREECKO        665
#define TRAINER_MAY_LILYCOVE_TORCHIC        666
#define TRAINER_JONAH                       667
#define TRAINER_HENRY                       668
#define TRAINER_ROGER                       669
#define TRAINER_ALEXA                       670
#define TRAINER_RUBEN                       671
#define TRAINER_KOJI_1                      672
#define TRAINER_WAYNE                       673
#define TRAINER_AIDAN                       674
#define TRAINER_REED                        675
#define TRAINER_TISHA                       676
#define TRAINER_TORI_AND_TIA                677
#define TRAINER_KIM_AND_IRIS                678
#define TRAINER_TYRA_AND_IVY                679
#define TRAINER_MEL_AND_PAUL                680
#define TRAINER_JOHN_AND_JAY_1              681
#define TRAINER_JOHN_AND_JAY_2              682
#define TRAINER_JOHN_AND_JAY_3              683
#define TRAINER_JOHN_AND_JAY_4              684
#define TRAINER_JOHN_AND_JAY_5              685
#define TRAINER_RELI_AND_IAN                686
#define TRAINER_LILA_AND_ROY_1              687
#define TRAINER_LILA_AND_ROY_2              688
#define TRAINER_LILA_AND_ROY_3              689
#define TRAINER_LILA_AND_ROY_4              690
#define TRAINER_LILA_AND_ROY_5              691
#define TRAINER_LISA_AND_RAY                692
#define TRAINER_CHRIS                       693
#define TRAINER_DAWSON                      694
#define TRAINER_SARAH                       695
#define TRAINER_DARIAN                      696
#define TRAINER_HAILEY                      697
#define TRAINER_CHANDLER                    698
#define TRAINER_KALEB                       699
#define TRAINER_JOSEPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_MARCOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_LAWRENCE                    710
#define TRAINER_WYATT                       711
#define TRAINER_ANGELINA                    712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_DEANDRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_TABITHA_MAGMA_HIDEOUT       732
#define TRAINER_DARCY                       733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_ANDRES_1                    737
#define TRAINER_JOSUE                       738
#define TRAINER_CAMRON                      739
#define TRAINER_CORY_1                      740
#define TRAINER_CAROLINA                    741
#define TRAINER_ELIJAH                      742
#define TRAINER_CELIA                       743
#define TRAINER_BRYAN                       744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_MARLENE                     752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_MELINA                      755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RACHEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN_1                   767
#define TRAINER_MAY_RUSTBORO_TREECKO        768
#define TRAINER_MAY_RUSTBORO_TORCHIC        769
#define TRAINER_ROXANNE_2                   770
#define TRAINER_ROXANNE_3                   771
#define TRAINER_ROXANNE_4                   772
#define TRAINER_ROXANNE_5                   773
#define TRAINER_BRAWLY_2                    774
#define TRAINER_BRAWLY_3                    775
#define TRAINER_BRAWLY_4                    776
#define TRAINER_BRAWLY_5                    777
#define TRAINER_WATTSON_2                   778
#define TRAINER_WATTSON_3                   779
#define TRAINER_WATTSON_4                   780
#define TRAINER_WATTSON_5                   781
#define TRAINER_FLANNERY_2                  782
#define TRAINER_FLANNERY_3                  783
#define TRAINER_FLANNERY_4                  784
#define TRAINER_FLANNERY_5                  785
#define TRAINER_NORMAN_2                    786
#define TRAINER_NORMAN_3                    787
#define TRAINER_NORMAN_4                    788
#define TRAINER_NORMAN_5                    789
#define TRAINER_WINONA_2                    790
#define TRAINER_WINONA_3                    791
#define TRAINER_WINONA_4                    792
#define TRAINER_WINONA_5                    793
#define TRAINER_TATE_AND_LIZA_2             794
#define TRAINER_TATE_AND_LIZA_3             795
#define TRAINER_TATE_AND_LIZA_4             796
#define TRAINER_TATE_AND_LIZA_5             797
#define TRAINER_JUAN_2                      798
#define TRAINER_JUAN_3                      799
#define TRAINER_JUAN_4                      800
#define TRAINER_JUAN_5                      801
#define TRAINER_ANGELO                      802
#define TRAINER_DARIUS                      803
#define TRAINER_STEVEN                      804
#define TRAINER_ANABEL                      805
#define TRAINER_TUCKER                      806
#define TRAINER_SPENSER                     807
#define TRAINER_GRETA                       808
#define TRAINER_NOLAND                      809
#define TRAINER_LUCY                        810
#define TRAINER_BRANDON                     811
#define TRAINER_ANDRES_2                    812
#define TRAINER_ANDRES_3                    813
#define TRAINER_ANDRES_4                    814
#define TRAINER_ANDRES_5                    815
#define TRAINER_CORY_2                      816
#define TRAINER_CORY_3                      817
#define TRAINER_CORY_4                      818
#define TRAINER_CORY_5                      819
#define TRAINER_PABLO_2                     820
#define TRAINER_PABLO_3                     821
#define TRAINER_PABLO_4                     822
#define TRAINER_PABLO_5                     823
#define TRAINER_KOJI_2                      824
#define TRAINER_KOJI_3                      825
#define TRAINER_KOJI_4                      826
#define TRAINER_KOJI_5                      827
#define TRAINER_CRISTIN_2                   828
#define TRAINER_CRISTIN_3                   829
#define TRAINER_CRISTIN_4                   830
#define TRAINER_CRISTIN_5                   831
#define TRAINER_FERNANDO_2                  832
#define TRAINER_FERNANDO_3                  833
#define TRAINER_FERNANDO_4                  834
#define TRAINER_FERNANDO_5                  835
#define TRAINER_SAWYER_2                    836
#define TRAINER_SAWYER_3                    837
#define TRAINER_SAWYER_4                    838
#define TRAINER_SAWYER_5                    839
#define TRAINER_GABRIELLE_2                 840
#define TRAINER_GABRIELLE_3                 841
#define TRAINER_GABRIELLE_4                 842
#define TRAINER_GABRIELLE_5                 843
#define TRAINER_THALIA_2                    844
#define TRAINER_THALIA_3                    845
#define TRAINER_THALIA_4                    846
#define TRAINER_THALIA_5                    847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// New trainers
#define TRAINER_JACE_UMBER_TOWN_CHESPIN     855
#define TRAINER_JACE_UMBER_TOWN_TEPIG       856
#define TRAINER_JACE_UMBER_TOWN_POPPLIO     857
#define TRAINER_KENNY                       858
#define TRAINER_JANE                        859
#define TRAINER_DENZEL                      860
#define TRAINER_RAYNER_ROUTE_79             861
#define TRAINER_CAITLYN                     862
#define TRAINER_PEDRO                       863

#define TRAINER_VIOLET_CINEROUS_TOWN_CHESPIN     864
#define TRAINER_VIOLET_CINEROUS_TOWN_TEPIG     865
#define TRAINER_VIOLET_CINEROUS_TOWN_POPPLIO     866
#define TRAINER_VERN_CINEROUS_TOWN_CHESPIN     867
#define TRAINER_VERN_CINEROUS_TOWN_TEPIG     868
#define TRAINER_VERN_CINEROUS_TOWN_POPPLIO     869

#define TRAINER_JACE_AMBER_CITY_CHESPIN     870
#define TRAINER_JACE_AMBER_CITY_TEPIG     871
#define TRAINER_JACE_AMBER_CITY_POPPLIO     872
#define TRAINER_JACE_ROUTE_83_CHESPIN     873
#define TRAINER_JACE_ROUTE_83_TEPIG     874
#define TRAINER_JACE_ROUTE_83_POPPLIO     875

#define TRAINER_RAYNER_QUARTZ_CAVE     876

#define TRAINER_OLIVER     877
#define TRAINER_LOGAN     878
#define TRAINER_GORDIE     879
#define TRAINER_AUSTIN     880
#define TRAINER_IRWIN     881
#define TRAINER_GRUNT_RESEDA_WOODS     882
#define TRAINER_TIM     883
#define TRAINER_ERIK     884
#define TRAINER_ARTHUR_1     885
#define TRAINER_MAYA_AND_JOY     886
#define TRAINER_GRUNT_ROUTE_84     887
#define TRAINER_QUENTIN     888
#define TRAINER_TODD     889
#define TRAINER_MASON     890
#define TRAINER_KIERSTEN     891
#define TRAINER_ANGUS     892
#define TRAINER_GRUNT_POWER_STATION_1     893
#define TRAINER_GRUNT_POWER_STATION_2     894
#define TRAINER_HIRAM     895
#define TRAINER_CHAIM     896
#define TRAINER_TYSON     897
#define TRAINER_OLYMPIA     898
#define TRAINER_LIAM     899
#define TRAINER_MADDY     900
#define TRAINER_DANIEL     901
#define TRAINER_CLETUS     902
#define TRAINER_AVERY     903
#define TRAINER_GAVIN     904
#define TRAINER_JOSIAH     905
#define TRAINER_BEAUFORD     906
#define TRAINER_TARAH_1     907
#define TRAINER_BREE     908
#define TRAINER_BROOK     909
#define TRAINER_NICK     910
#define TRAINER_SUMMER     911
#define TRAINER_HOGAN     912
#define TRAINER_MEGAN     913
#define TRAINER_SETH     914
#define TRAINER_VINCE     915
#define TRAINER_RUTHERFORD     916
#define TRAINER_NIGEL     917
#define TRAINER_GUS     918
#define TRAINER_FELIKS     919
#define TRAINER_SARA_AND_MIA     920
#define TRAINER_GINNY     921
#define TRAINER_SEAN     922
#define TRAINER_CECIL     923
#define TRAINER_AXEL     924
#define TRAINER_NEIL     925
#define TRAINER_BRUCE     926
#define TRAINER_PATRIC     927
#define TRAINER_CHLOE     928
#define TRAINER_WENDEL     929
#define TRAINER_EGBERT     930
#define TRAINER_AURORA     931
#define TRAINER_DAHLIA     932
#define TRAINER_REILLY     933
#define TRAINER_EOIN     934
#define TRAINER_AMOS     935
#define TRAINER_LAYTON     936
#define TRAINER_MARINA     937
#define TRAINER_BRITTANY     938
#define TRAINER_LEE     939
#define TRAINER_DELMUS     940
#define TRAINER_GEDDY     941
#define TRAINER_STORMY     942
#define TRAINER_PETUNIA     943
#define TRAINER_LIV_AND_TAY     944
#define TRAINER_ALISTER     945
#define TRAINER_STELLA     946
#define TRAINER_WILBUR     947
#define TRAINER_ORVILLE     948
#define TRAINER_HENDRICK     949
#define TRAINER_CELINE     950
#define TRAINER_JEAN     951
#define TRAINER_ELAINE     952
#define TRAINER_TRISHA     953
#define TRAINER_COREY     954
#define TRAINER_OSCAR     955
#define TRAINER_MIMI     956
#define TRAINER_YOLANDA     957
#define TRAINER_EUGENE     958
#define TRAINER_GRIFFIN     959
#define TRAINER_EMILY     960
#define TRAINER_LLUVIA     961
#define TRAINER_HEATHER     962
#define TRAINER_MYRTLE_1     963
#define TRAINER_MANUEL     964

#define TRAINER_GRUNT_TURQUOISE_CITY_1     965
#define TRAINER_GRUNT_TURQUOISE_CITY_2     966
#define TRAINER_GRUNT_TURQUOISE_CITY_3     967
#define TRAINER_GRUNT_TURQUOISE_CITY_4     968
#define TRAINER_GRUNT_TURQUOISE_CITY_5     969
#define TRAINER_GRUNT_TURQUOISE_CITY_6     970
#define TRAINER_ZARTOSHT_1                 971

#define TRAINER_CHARLENE     972
#define TRAINER_THOMPSON     973
#define TRAINER_MINERVA     974
#define TRAINER_ENIS     975
#define TRAINER_LLEWELYN     976
#define TRAINER_HARLEY     977
#define TRAINER_SUE     978
#define TRAINER_GIDEON     979
#define TRAINER_JIM     980
#define TRAINER_POLLY     981
#define TRAINER_GORDON     982
#define TRAINER_WILSON     983
#define TRAINER_TREVOR     984
#define TRAINER_KRIS     985

#define TRAINER_FREYA     986
#define TRAINER_BJORN     987
#define TRAINER_HELGA     988
#define TRAINER_STEN     989
#define TRAINER_BERA     990
#define TRAINER_EINAR     991
#define TRAINER_EIRA_1     992

#define TRAINER_GISELLE     993
#define TRAINER_BRETT     994
#define TRAINER_CODY     995
#define TRAINER_TUDY     996
#define TRAINER_MICK     997
#define TRAINER_KYLE     998

#define TRAINER_HOLMES     999
#define TRAINER_CHELSEA     1000
#define TRAINER_AMANDA     1001
#define TRAINER_JEROMIE     1002
#define TRAINER_PIERRE     1003
#define TRAINER_CECILIA     1004
#define TRAINER_BEATRICE     1005
#define TRAINER_MONTGOMERY     1006

#define TRAINER_LUANNE     1007
#define TRAINER_JO     1008
#define TRAINER_BURT     1009
#define TRAINER_NOAH     1010
#define TRAINER_DEIDRE     1011
#define TRAINER_YEAGER     1012
#define TRAINER_SOUSUKE     1013
#define TRAINER_EIICHIRO     1014

#define TRAINER_YELENA     1015
#define TRAINER_MACY     1016
#define TRAINER_KAISUKE     1017
#define TRAINER_HAYAO     1018
#define TRAINER_YOSHI     1019
#define TRAINER_PERCIVAL     1020

#define TRAINER_DAVE     1021
#define TRAINER_BLAYNE     1022
#define TRAINER_PEYTON     1023
#define TRAINER_BIFF     1024
#define TRAINER_EUNICE     1025
#define TRAINER_GORO     1026
#define TRAINER_REESE     1027
#define TRAINER_NEDRY     1028

#define TRAINER_HYMIE     1029
#define TRAINER_MOISHE     1030

#define TRAINER_KURT     1031
#define TRAINER_TYRONE     1032
#define TRAINER_DEAARON     1033
#define TRAINER_BENITO     1034
#define TRAINER_JENNY     1035
#define TRAINER_MALCOLM     1036
#define TRAINER_CADE_1     1037

#define TRAINER_GRUNT_KENDOMA_CORP_1      1038
#define TRAINER_GRUNT_KENDOMA_CORP_2      1039
#define TRAINER_GRUNT_KENDOMA_CORP_3      1040
#define TRAINER_GRUNT_KENDOMA_CORP_4      1041
#define TRAINER_GRUNT_KENDOMA_CORP_5      1042
#define TRAINER_GRUNT_KENDOMA_CORP_6      1043
#define TRAINER_GRUNT_KENDOMA_CORP_7      1044
#define TRAINER_GRUNT_KENDOMA_CORP_8      1045
#define TRAINER_GRUNT_KENDOMA_CORP_9      1046
#define TRAINER_GRUNT_KENDOMA_CORP_10     1047
#define TRAINER_GRUNT_1_ROUTE_90          1048
#define TRAINER_GRUNT_2_ROUTE_90          1049
#define TRAINER_NEDA_1                    1050

#define TRAINER_BARBARA                    1051

#define TRAINER_CLYDE     1052
#define TRAINER_CONNOR    1053
#define TRAINER_MORGAN    1054
#define TRAINER_CASSEY    1055
#define TRAINER_CRYSTAL    1056
#define TRAINER_HOLLY    1057
#define TRAINER_SLADE    1058
#define TRAINER_MARCUS    1059
#define TRAINER_CORBIN    1060
#define TRAINER_DUSTIN    1061
#define TRAINER_STACY    1062
#define TRAINER_ZELDA    1063
#define TRAINER_GERTRUDE    1064
#define TRAINER_BERNICE    1065
#define TRAINER_RAMIE    1066
#define TRAINER_WESLEY  1067
#define TRAINER_JOEL    1068
#define TRAINER_AGNIS   1069
#define TRAINER_KEITH   1070
#define TRAINER_BLOSSOM   1071
#define TRAINER_HEATH   1072
#define TRAINER_AMBROSE 1073
#define TRAINER_RANDY 1074
#define TRAINER_KAZUKI 1075
#define TRAINER_NOBUO 1076

#define TRAINER_JURGEN    1077
#define TRAINER_ARNOLD    1078
#define TRAINER_BERTHOLD    1079
#define TRAINER_KARL    1080
#define TRAINER_ASHTON    1081
#define TRAINER_LALO    1082
#define TRAINER_JEB    1083
#define TRAINER_NIKOLAUS_1 1084

#define TRAINER_HANS    1085
#define TRAINER_BERNARD    1086
#define TRAINER_KLAUS    1087
#define TRAINER_OTTO    1088

#define TRAINER_ASPEN 1089
#define TRAINER_EARL 1090
#define TRAINER_TYLER 1091
#define TRAINER_INGRID 1092
#define TRAINER_JAN 1093

#define TRAINER_GODARD 1094
#define TRAINER_GODWIN 1095
#define TRAINER_GODFREY 1096
#define TRAINER_OSBORN 1097
#define TRAINER_OSWALD 1098
#define TRAINER_ISHMAEL 1099

#define TRAINER_FRODE 1100
#define TRAINER_GUNDA 1101
#define TRAINER_BENEDICT 1102

#define TRAINER_VIOLET_MINDARO_GARDENS_CHESPIN     1103
#define TRAINER_VIOLET_MINDARO_GARDENS_TEPIG     1104
#define TRAINER_VIOLET_MINDARO_GARDENS_POPPLIO     1105
#define TRAINER_VERN_MINDARO_GARDENS_CHESPIN     1106
#define TRAINER_VERN_MINDARO_GARDENS_TEPIG     1107
#define TRAINER_VERN_MINDARO_GARDENS_POPPLIO     1108

#define TRAINER_EDD     1109
#define TRAINER_MO      1110
#define TRAINER_DUKE    1111

#define TRAINER_BOB    1112
#define TRAINER_IZZI    1113
#define TRAINER_NEVEN    1114
#define TRAINER_HABIBAH    1115

#define TRAINER_BRAD    1116
#define TRAINER_COURTNEY    1117
#define TRAINER_THEO    1118
#define TRAINER_GUNTHER    1119
#define TRAINER_VELMA    1120
#define TRAINER_DUVAL    1121
#define TRAINER_DALLAS    1122
#define TRAINER_SUSAN    1123

#define TRAINER_ZEKE    1124
#define TRAINER_ZIGGY    1125
#define TRAINER_BUTCH    1126
#define TRAINER_CHEVY    1127
#define TRAINER_ALFRED    1128
#define TRAINER_WERNER    1129
#define TRAINER_DARWIN    1130
#define TRAINER_ERIN    1131
#define TRAINER_ADDERLY_1    1132

#define TRAINER_DESMOND    1133
#define TRAINER_DUNSTAN    1134
#define TRAINER_ANDERS    1135
#define TRAINER_RAVEN    1136
#define TRAINER_WREN    1137
#define TRAINER_BRANDY    1138
#define TRAINER_MILLIE    1139

#define TRAINER_SIGERIC    1140
#define TRAINER_THRYTH    1141
#define TRAINER_HYGELAC    1142
#define TRAINER_HAERETH    1143
#define TRAINER_EARENDEL    1144
#define TRAINER_EAWYNN    1145
#define TRAINER_DOMFRITH    1146
#define TRAINER_RICBERT    1147
#define TRAINER_ETHEL_1    1148

#define TRAINER_SIGMUND    1149
#define TRAINER_RYDEN   1150
#define TRAINER_SWAIN   1151
#define TRAINER_TRISTAN   1152
#define TRAINER_RALPH   1153
#define TRAINER_BAILEY   1154
#define TRAINER_CADMON   1155
#define TRAINER_AUDREY   1156
#define TRAINER_ARLEY   1157
#define TRAINER_KIMBERLY   1158
#define TRAINER_BONNIE   1159

#define TRAINER_SEWARD    1160
#define TRAINER_AVA_AND_BART    1161
#define TRAINER_ZOE_AND_ROSS    1162
#define TRAINER_RHIANNON    1163
#define TRAINER_MOIRA    1164
#define TRAINER_DEIRDRE    1165
#define TRAINER_FINN    1166

#define TRAINER_MALACHI    1167
#define TRAINER_KILLIAN    1168
#define TRAINER_ASHMUND    1169
#define TRAINER_JOAQUIN    1170
#define TRAINER_GALE    1171
#define TRAINER_NEVILLE    1172
#define TRAINER_CHETT    1173
#define TRAINER_HOWARD    1174
#define TRAINER_FRANCINE    1175
#define TRAINER_APOLLO    1176
#define TRAINER_MURIEL    1177
#define TRAINER_EUSTACE    1178
#define TRAINER_RODDY    1179
#define TRAINER_SEAMUS    1180
#define TRAINER_CASCA    1181
#define TRAINER_BETTY    1182
#define TRAINER_VERONICA    1183
#define TRAINER_FLYNN    1184
#define TRAINER_CORAL    1185
#define TRAINER_LEARY    1186
#define TRAINER_BROMM    1187
#define TRAINER_SHANKS    1188
#define TRAINER_JAKE    1189
#define TRAINER_KELLY    1190
#define TRAINER_CASPER    1191
#define TRAINER_ADRIAN    1192
#define TRAINER_XENA    1193
#define TRAINER_CERISE    1194
#define TRAINER_EDITH    1195
#define TRAINER_SASHA    1196
#define TRAINER_CURT    1197
#define TRAINER_KANE    1198
#define TRAINER_GLENN    1199
#define TRAINER_WILMA    1200
#define TRAINER_TANNER    1201
#define TRAINER_JUDITH    1202
#define TRAINER_LESTER    1203
#define TRAINER_LANDON    1204
#define TRAINER_OLGA    1205
#define TRAINER_WOODY    1206
#define TRAINER_BUZZ    1207
#define TRAINER_EOGHAN    1208
#define TRAINER_YVONNE    1209
#define TRAINER_FAYE    1210
#define TRAINER_FLOYD    1211
#define TRAINER_COOPER    1212
#define TRAINER_ZED    1213
#define TRAINER_YURI    1214
#define TRAINER_XAVIER    1215
#define TRAINER_ALPHONSE    1216
#define TRAINER_LUNA    1217
#define TRAINER_CIRCE    1218
#define TRAINER_LIONEL    1219
#define TRAINER_QUILLEN    1220
#define TRAINER_ARCHER    1221
#define TRAINER_HARRIET    1222
#define TRAINER_SELWYN    1223
#define TRAINER_WILLOW    1224

#define TRAINER_LISIA_0     1225
#define TRAINER_IAN_0       1226
#define TRAINER_SIDNEY_0    1227
#define TRAINER_PETRA_0     1228
#define TRAINER_NORMAN_0    1229

#define TRAINER_KENNETH    1230
#define TRAINER_NATALIE    1231

#define TRAINER_JACE_MAROON_CITY_CHESPIN     1232
#define TRAINER_JACE_MAROON_CITY_TEPIG       1233
#define TRAINER_JACE_MAROON_CITY_POPPLIO     1234
#define TRAINER_JACE_ROUTE_100_CHESPIN       1235
#define TRAINER_JACE_ROUTE_100_TEPIG         1236
#define TRAINER_JACE_ROUTE_100_POPPLIO       1237

#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_1      1238
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_2      1239
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_3      1240
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_4      1241
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_5      1242
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_6      1243
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_7      1244
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_8      1245
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_9      1246
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_10     1247
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_11     1248
#define TRAINER_GRUNT_XANTHOS_UNDERGROUND_12     1249

#define TRAINER_AZAMI_1                        1250
#define TRAINER_RAYNER_POKEMON_LABORATORY      1251

#define TRAINER_LLOYD    1252
#define TRAINER_DIANE    1253
#define TRAINER_CRUZ     1254
#define TRAINER_MARISSA  1255
#define TRAINER_DEWEY    1256

#define TRAINER_GRIMMOD  1257
#define TRAINER_GRIMRIC  1258
#define TRAINER_GRIMWALD 1259

#define TRAINER_POKEMON_LABORATORY_ENTITY    1260

#define TRAINER_VIOLET_DUN_TOWN_CHESPIN   1261
#define TRAINER_VIOLET_DUN_TOWN_TEPIG     1262
#define TRAINER_VIOLET_DUN_TOWN_POPPLIO   1263
#define TRAINER_VERN_DUN_TOWN_CHESPIN     1264
#define TRAINER_VERN_DUN_TOWN_TEPIG       1265
#define TRAINER_VERN_DUN_TOWN_POPPLIO     1266

#define TRAINER_KINOE        1267
#define TRAINER_KINOTO       1268
#define TRAINER_HINOE        1269
#define TRAINER_HINOTO       1270
#define TRAINER_TSUCHINOE    1271
#define TRAINER_TSUCHINOTO   1272
#define TRAINER_KANOE        1273
#define TRAINER_KANOTO       1274
#define TRAINER_MIZUNOE      1275
#define TRAINER_MIZUNOTO     1276

#define TRAINER_ZOLTAN_1     1277
#define TRAINER_ZOLTAN_2     1278

#define TRAINER_KENICHI_1       1279
#define TRAINER_KENICHI_2       1280
#define TRAINER_KENICHI_3       1281
#define TRAINER_GEORGETTE_1     1282
#define TRAINER_GEORGETTE_2     1283
#define TRAINER_GEORGETTE_3     1284
#define TRAINER_GARFIELD_1      1285
#define TRAINER_GARFIELD_2      1286
#define TRAINER_GARFIELD_3      1287

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_EMERALD     1288 //965//855
#define MAX_TRAINERS_COUNT_EMERALD 1312 //965//864

#if IS_FRLG
#define TRAINERS_COUNT                      TRAINERS_COUNT_FRLG
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_FRLG
#else
#define TRAINERS_COUNT                      TRAINERS_COUNT_EMERALD
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_EMERALD
#endif


#endif  // GUARD_CONSTANTS_OPPONENTS_H
