#ifndef GUARD_SLIDING_PUZZLES_CONSTANTS_H
#define GUARD_SLIDING_PUZZLES_CONSTANTS_H

#define SLIDING_PUZZLE_KABUTO      0
#define SLIDING_PUZZLE_OMANYTE     1
#define SLIDING_PUZZLE_AERODACTYL  2
#define SLIDING_PUZZLE_HO_OH       3
#define SLIDING_PUZZLE_ANORITH     4
#define SLIDING_PUZZLE_LILEEP      5
#define SLIDING_PUZZLE_RELICANTH   6
#define SLIDING_PUZZLE_CARRACOSTA  7
#define SLIDING_PUZZLE_ARCHEOPS    8
#define SLIDING_PUZZLE_SIGILYPH    9
#define SLIDING_PUZZLE_SOLVED      10

#define SLIDING_PUZZLE_COUNT       11

#endif // GUARD_SLIDING_PUZZLES_CONSTANTS_H
