#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT      12
#define WATER_WILD_COUNT     5
#define ROCK_WILD_COUNT      5
#define FISH_WILD_COUNT      10
#define HIDDEN_WILD_COUNT    3
#define CUT_WILD_COUNT       5
#define THAW_WILD_COUNT      5
#define HEADBUTT_WILD_COUNT  4

#define NUM_ALTERING_CAVE_TABLES 9

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
