ScarletTown_House1_MapScripts::
	.byte 0

ScarletTown_House1_EventScript_Girl::
	msgbox ScarletTown_House1_Text_Daddy, MSGBOX_NPC
	end

ScarletTown_House1_Text_Daddy:
	.string "Daddy's coming home soon!$"

ScarletTown_House1_EventScript_Woman::
	msgbox ScarletTown_House1_Text_Lumberjacks, MSGBOX_NPC
	end

ScarletTown_House1_Text_Lumberjacks:
	.string "My husband is a lumberjack.\p"
	.string "It's not all about cutting down trees,\n"
	.string "you know.\p"
	.string "They maintain the forest and\n"
	.string "help conserve wild POKéMON.$"
