Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed HAZEL's PC.$"

gText_AccessedBillsPC::
	.string "Accessed BILL's PC.$"

gText_PCWithFee::
	.string "It costs ¥300 to use the PC.\n"
	.string "Will you pay?$"

gText_PCCantPay:
	.string "You don't have enough money!$"
