CinerousTown_House1_MapScripts::
	.byte 0

CinerousTown_House1_EventScript_Woman::
	msgbox CinerousTown_House1_Text_CinerousTower, MSGBOX_NPC
	end

CinerousTown_House1_EventScript_LittleGirl::
	msgbox CinerousTown_House1_Text_LegendaryPokemon, MSGBOX_NPC
	end

CinerousTown_House1_Text_CinerousTower:
	.string "CINEROUS TOWER used to be a famous\n"
	.string "historical monument.\p"
	.string "Until one day it was suddenly destroyed\n"
	.string "in a great fire.$"

CinerousTown_House1_Text_LegendaryPokemon:
	.string "Listen! Me and my brother stayed out\n"
	.string "late last night and saw a POKéMON\l"
	.string "fly out of the tower!\p"
	.string "My brother said it was a legendary\n"
	.string "POKéMON.\p"
	.string "But I think he made that up.$"
