PitchblakCity_KendomaCorp_8F_MapScripts::
	.byte 0

PitchblakCity_KendomaCorp_8F_EventScript_Scientist::
	msgbox PitchblakCity_KendomaCorp_8F_Text_TrickyThingAboutCloning, MSGBOX_NPC
	end

PitchblakCity_KendomaCorp_8F_Text_TrickyThingAboutCloning:
	.string "Cloning POKéMON can be a tricky process.\p"
	.string "It's easier to work on POKéMON from the\n"
	.string "mineral and amorphous egg groups.$"

