PitchblakCity_KendomaCorp_2F_MapScripts::
	.byte 0

PitchblakCity_KendomaCorp_2F_EventScript_Worker::
	msgbox PitchblakCity_KendomaCorp_2F_Text_HostileTakeover, MSGBOX_NPC
	end

PitchblakCity_KendomaCorp_2F_Text_HostileTakeover:
	.string "A hostile takeover?\n"
	.string "What's going on out there?$"

PitchblakCity_KendomaCorp_2F_EventScript_Worker2::
	msgbox PitchblakCity_KendomaCorp_2F_Text_Hiding, MSGBOX_NPC
	end

PitchblakCity_KendomaCorp_2F_Text_Hiding:
	.string "Hey! Close the door or they'll find me!$"


