PitchblakCity_KendomaCorp_3F_MapScripts::
	.byte 0

PitchblakCity_KendomaCorp_3F_EventScript_Man::
	msgbox PitchblakCity_KendomaCorp_3F_Text_WhatsGoingOn, MSGBOX_NPC
	end

PitchblakCity_KendomaCorp_3F_Text_WhatsGoingOn:
	.string "Gyah! What's going on?\p"
	.string "I don't know anything,\n"
	.string "I just work here.$"

PitchblakCity_KendomaCorp_3F_EventScript_Woman::
	msgbox PitchblakCity_KendomaCorp_3F_Text_Confused, MSGBOX_NPC
	end

PitchblakCity_KendomaCorp_3F_Text_Confused:
	.string "TEAM GENESIS is here?!\p"
	.string "W-what could they want with us?!$"

