Route74_MapScripts::
	.byte 0

Route74_EventScript_Rhiannon::
	trainerbattle_single TRAINER_RHIANNON, Route74_Text_RhiannonIntro, Route74_Text_RhiannonDefeated
	msgbox Route74_Text_RhiannonPostBattle, MSGBOX_AUTOCLOSE
	end

Route74_EventScript_Betty::
	trainerbattle_single TRAINER_BETTY, Route74_Text_BettyIntro, Route74_Text_BettyDefeated
	msgbox Route74_Text_BettyPostBattle, MSGBOX_AUTOCLOSE
	end

Route74_EventScript_Raven::
	trainerbattle_single TRAINER_RAVEN, Route74_Text_RavenIntro, Route74_Text_RavenDefeated
	msgbox Route74_Text_RavenPostBattle, MSGBOX_AUTOCLOSE
	end

Route74_EventScript_Crystal::
	trainerbattle_single TRAINER_CRYSTAL, Route74_Text_CrystalIntro, Route74_Text_CrystalDefeated
	msgbox Route74_Text_CrystalPostBattle, MSGBOX_AUTOCLOSE
	end

Route74_EventScript_Bromm::
	trainerbattle_single TRAINER_BROMM, Route74_Text_BrommIntro, Route74_Text_BrommDefeated
	msgbox Route74_Text_BrommPostBattle, MSGBOX_AUTOCLOSE
	end

Route74_EventScript_Seward::
	trainerbattle_single TRAINER_SEWARD, Route74_Text_SewardIntro, Route74_Text_SewardDefeated
	msgbox Route74_Text_SewardPostBattle, MSGBOX_AUTOCLOSE
	end

Route74_EventScript_Dunstan::
	trainerbattle_single TRAINER_DUNSTAN, Route74_Text_DunstanIntro, Route74_Text_DunstanDefeated
	msgbox Route74_Text_DunstanPostBattle, MSGBOX_AUTOCLOSE
	end

Route74_EventScript_Francine::
	trainerbattle_single TRAINER_FRANCINE, Route74_Text_FrancineIntro, Route74_Text_FrancineDefeated
	msgbox Route74_Text_FrancinePostBattle, MSGBOX_AUTOCLOSE
	end






