StationCity_Building1_B1_MapScripts::
	.byte 0








StationCity_Building1_B1_Text_NewWormholes:
	.string "We've detected three new Ultra Wormholes\n"
	.string "around the HOENN region.\p"
	.string "They're in...$"

StationCity_Building1_B1_Text_Tier1Worlds:
	.string "ROUTE 109, PETALBURG WOODS,\n"
	.string "and DEWFORD MEADOW.$"

StationCity_Building1_B1_Text_Tier2Worlds:
	.string "ROUTE 110, ROUTE 111,\n"
	.string "and METEOR FALLS.$"

StationCity_Building1_B1_Text_Tier3Worlds:
	.string "MT. CHIMNEY, ROUTE 119,\n"
	.string "and MT. PYRE.$"

StationCity_Building1_B1_Text_Tier4Worlds:
	.string "SHOAL CAVE, ROUTE 132,\n"
	.string "and OLD VICTORY ROAD.$"




