MindaroCity_Flat1_2F_MapScripts::
	.byte 0


MindaroCity_Flat1_2F_EventScript_Weirdo::
	msgbox MindaroCity_Flat1_2F_Text_Superorganisms, MSGBOX_NPC
	end

MindaroCity_Flat1_2F_Text_Superorganisms:
	.string "When you think about it, a city\n"
	.string "is like an organism.\p"
	.string "Its cells are the citizens who work\n"
	.string "together to make it function.\p"
	.string "I wonder if cities can have\n"
	.string "minds of their own.$"

