Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@ NEW ITEMS @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

ShuckleSpring_EventScript_ItemSlimyRock::
	finditem ITEM_SLIMY_ROCK
	end

ShuckleSpring_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

ShuckleSpring_EventScript_ItemTM21::
	finditem ITEM_TM21
	end

Route82_EventScript_ItemPokeball::
	finditem ITEM_POKE_BALL
	end

XanthosCity_EventScript_ItemTM54::
	finditem ITEM_TM54
	end

Route83_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ResedaWoods_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

ResedaWoods_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

ResedaWoods_EventScript_ItemAntibiotics::
	finditem ITEM_ANTIBIOTICS
	end

ResedaWoods_EventScript_ItemTM53::
	finditem ITEM_TM53
	end

Route84_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route84_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end






PowerStation_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PowerStation_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

PowerStation_EventScript_ItemTM24::
	finditem ITEM_TM24
	end

PowerStation_EventScript_ItemDazeHeal::
	finditem ITEM_DAZE_HEAL
	end

PowerStation_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

PowerStation_EventScript_ItemMagnet::
	finditem ITEM_MAGNET
	end






Route85_EventScript_ItemTM39::
	finditem ITEM_TM39
	end

Route85_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route86_EventScript_ItemRazorFang::
	finditem ITEM_RAZOR_FANG
	end

Route87_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

Route87_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Sandshraf_EventScript_ItemSmoothRock::
	finditem ITEM_SMOOTH_ROCK
	end

Route88_EventScript_ItemTM80::
	finditem ITEM_TM80
	end

Route88_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

CinerousTower_EventScript_ItemCharcoal::
	finditem ITEM_CHARCOAL
	end

CinerousTower_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

CinerousTower_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

CinerousTower_EventScript_ItemFlameOrb::
	finditem ITEM_FLAME_ORB
	end

CinerousTower_EventScript_ItemTM61::
	finditem ITEM_TM61
	end

QuartzCave_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

QuartzCave_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

QuartzCave_EventScript_ItemTM69::
	finditem ITEM_TM69
	end

Route79_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

Route79_EventScript_ItemAwakening::
	finditem ITEM_AWAKENING
	end

Route79_EventScript_ItemRockyHelmet::
	finditem ITEM_ROCKY_HELMET
	end

Route78_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

Route78_EventScript_ItemIron::
	finditem ITEM_IRON
	end

DreamResort_EventScript_ItemDuskBall::
	finditem ITEM_DUSK_BALL
	end

DreamResort_EventScript_ItemSmokeBall::
	finditem ITEM_SMOKE_BALL
	end

DreamResort_EventScript_ItemStimulant::
	finditem ITEM_STIMULANT
	end

DreamResort_EventScript_ItemSpellTag::
	finditem ITEM_SPELL_TAG
	end

Route79_EventScript_ItemTM18::
	finditem ITEM_TM18
	end






Route94_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end



Route93_EventScript_ItemTM40::
	finditem ITEM_TM40
	end

Route93_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route93_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end



Route95_EventScript_ItemHeartScale::
	finditem ITEM_HEART_SCALE
	end

Route95_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route95_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end



Route96_EventScript_ItemShinyStone::
	finditem ITEM_SHINY_STONE
	end



Route98_EventScript_ItemTM11::
	finditem ITEM_TM11
	end



MindaroGardens_EventScript_ItemSunStone::
	finditem ITEM_SUN_STONE
	end

MindaroGardens_EventScript_ItemOvalStone::
	finditem ITEM_OVAL_STONE
	end

MindaroGardens_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

MindaroGardens_EventScript_ItemSilverPowder::
	finditem ITEM_SILVER_POWDER
	end



Route97_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route97_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

Route97_EventScript_ItemIceStone::
	finditem ITEM_ICE_STONE
	end



Route92_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end



Route90_EventScript_ItemTM95::
	finditem ITEM_TM95
	end

Route90_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end



BroadcastTower_EventScript_ItemAmplifier::
	finditem ITEM_AMPLIFIER
	end

BroadcastTower_EventScript_ItemPearlString::
	finditem ITEM_PEARL_STRING
	end

BroadcastTower_EventScript_ItemTM49::
	finditem ITEM_TM49
	end

BroadcastTower_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

BroadcastTower_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end



KendomaCorp_EventScript_ItemUpgrade::
	finditem ITEM_UPGRADE
	end

KendomaCorp_EventScript_ItemRareCandy1::
	finditem ITEM_RARE_CANDY
	end

KendomaCorp_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

KendomaCorp_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

KendomaCorp_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

KendomaCorp_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

KendomaCorp_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

KendomaCorp_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

KendomaCorp_EventScript_ItemSCard::
	finditem ITEM_CLEARANCE_S_CARD
	end

KendomaCorp_EventScript_ItemACard::
	finditem ITEM_CLEARANCE_A_CARD
	end

KendomaCorp_EventScript_ItemBCard::
	finditem ITEM_CLEARANCE_B_CARD
	end

KendomaCorp_EventScript_ItemRareCandy2::
	finditem ITEM_RARE_CANDY
	end




ScarletWoods_EventScript_ItemTM58::
	finditem ITEM_TM58
	end

ScarletWoods_EventScript_ItemDuskStone::
	finditem ITEM_DUSK_STONE
	end

ScarletWoods_EventScript_ItemHeartScale::
	finditem ITEM_HEART_SCALE
	end

ScarletWoods_EventScript_ItemTM89::
	finditem ITEM_TM89
	end

ScarletWoods_EventScript_ItemPitchRock::
	finditem ITEM_PITCH_ROCK
	end




MtShiro_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

MtShiro_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

MtShiro_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

MtShiro_EventScript_ItemIcyRock::
	finditem ITEM_ICY_ROCK
	end

MtShiro_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

MtShiro_EventScript_ItemIceStone::
	finditem ITEM_ICE_STONE
	end

MtShiro_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

MtShiro_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtShiro_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

MtShiro_EventScript_ItemTM79::
	finditem ITEM_TM79
	end

MtShiro_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

MtShiro_EventScript_ItemRareBone::
	finditem ITEM_RARE_BONE
	end



@@@@@@ Added in v0.3 @@@@@

MtShiro_EventScript_ItemIciclePlate::
	finditem ITEM_ICICLE_PLATE
	end

MtShiro_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MtShiro_EventScript_ItemDawnStone::
	finditem ITEM_DAWN_STONE
	end

MtShiro_EventScript_ItemHeavyBall::
	finditem ITEM_HEAVY_BALL
	end

MtShiro_EventScript_ItemTM13::
	finditem ITEM_TM13
	end

MtShiro_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

MtShiro_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtShiro_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

MtShiro_EventScript_ItemChoiceSpecs::
	finditem ITEM_CHOICE_SPECS
	end

MtShiro_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

MtShiro_EventScript_ItemRingTarget::
	finditem ITEM_RING_TARGET
	end




Route69_EventScript_ItemEjectButton::
	finditem ITEM_EJECT_BUTTON
	end



ShuckleSpring_EventScript_ItemBigMushroom::
	finditem ITEM_BIG_MUSHROOM
	end



QuartzCave_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

QuartzCave_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

QuartzCave_EventScript_ItemDuskBall::
	finditem ITEM_DUSK_BALL
	end



Route80_EventScript_ItemTM29::
	finditem ITEM_TM29
	end



Route81_EventScript_ItemDawnStone::
	finditem ITEM_DAWN_STONE
	end



Route82_EventScript_ItemSunStone::
	finditem ITEM_SUN_STONE
	end



XanthosCity_EventScript_ItemPearl::
	finditem ITEM_PEARL
	end



Route89_EventScript_ItemHeartScale::
	finditem ITEM_HEART_SCALE
	end



Route92_EventScript_ItemMiracleSeed::
	finditem ITEM_MIRACLE_SEED
	end

Route92_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end



Route90_EventScript_ItemTM51::
	finditem ITEM_TM51
	end



ShamrockIsle_Interior_EventScript_ItemTM81::
	finditem ITEM_TM81
	end

ShamrockIsle_Interior_EventScript_ItemMentalHerb::
	finditem ITEM_MENTAL_HERB
	end

ShamrockIsle_Interior_EventScript_ItemPowerHerb::
	finditem ITEM_POWER_HERB
	end

ShamrockIsle_Interior_EventScript_ItemWhiteHerb::
	finditem ITEM_WHITE_HERB
	end

ShamrockIsle_Interior_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

ShamrockIsle_Interior_EventScript_ItemShedShell::
	finditem ITEM_SHED_SHELL
	end

ShamrockIsle_Interior_EventScript_ItemAntibiotics::
	finditem ITEM_ANTIBIOTICS
	end

ShamrockIsle_Interior_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

ShamrockIsle_Interior_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

ShamrockIsle_Interior_EventScript_ItemMeadowPlate::
	finditem ITEM_MEADOW_PLATE
	end





Route76_EventScript_ItemHeartScale::
	finditem ITEM_HEART_SCALE
	end

Route76_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end



Route75_EventScript_ItemExpertBelt::
	finditem ITEM_EXPERT_BELT
	end

Route75_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end



Route74_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route74_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end



Route73_EventScript_ItemHeartScale::
	finditem ITEM_HEART_SCALE
	end

Route73_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end



SunkenIsle_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

SunkenIsle_Exterior_EventScript_ItemDampRock::
	finditem ITEM_DAMP_ROCK
	end



SunkenIsle_Interior_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

SunkenIsle_Interior_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

SunkenIsle_Interior_EventScript_ItemBigRoot::
	finditem ITEM_BIG_ROOT
	end

SunkenIsle_Interior_EventScript_ItemQuickBall::
	finditem ITEM_QUICK_BALL
	end

SunkenIsle_Interior_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

SunkenIsle_Interior_EventScript_ItemShellBell::
	finditem ITEM_SHELL_BELL
	end

SunkenIsle_Interior_EventScript_ItemXSpecialAttack::
	finditem ITEM_X_SP_ATK
	end

SunkenIsle_Interior_EventScript_ItemHeartScale::
	finditem ITEM_HEART_SCALE
	end



Route71_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

Route71_EventScript_ItemZephyrStone::
	finditem ITEM_ZEPHYR_STONE
	end



Route70_EventScript_ItemTM84::
	finditem ITEM_TM84
	end

Route70_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route70_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

Route70_EventScript_ItemHeatRock::
	finditem ITEM_HEAT_ROCK
	end

Route70_EventScript_ItemDragonFang::
	finditem ITEM_DRAGON_FANG
	end

Route70_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

Route70_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

Route70_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route70_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route70_EventScript_ItemDuskBall::
	finditem ITEM_DUSK_BALL
	end



Sandshraf_EventScript_ItemXenoresin::
	finditem ITEM_XENORESIN
	end

Sandshraf_EventScript_ItemRareBone::
	finditem ITEM_RARE_BONE
	end

Sandshraf_EventScript_ItemTM35::
	finditem ITEM_TM35
	end

Sandshraf_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Sandshraf_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Sandshraf_EventScript_ItemLaggingTail::
	finditem ITEM_LAGGING_TAIL
	end

Sandshraf_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Sandshraf_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Sandshraf_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Sandshraf_EventScript_ItemSoftSand::
	finditem ITEM_SOFT_SAND
	end

Sandshraf_EventScript_ItemHeavyDutyBoots::
	finditem ITEM_HEAVY_DUTY_BOOTS
	end

Sandshraf_EventScript_ItemChoiceScarf::
	finditem ITEM_CHOICE_SCARF
	end

Sandshraf_EventScript_ItemEarthPlate::
	finditem ITEM_EARTH_PLATE
	end



MiragePalace_EventScript_ItemRelicCopper::
	finditem ITEM_RELIC_COPPER
	end

MiragePalace_EventScript_ItemRelicSilver::
	finditem ITEM_RELIC_SILVER
	end

MiragePalace_EventScript_ItemRelicGold::
	finditem ITEM_RELIC_GOLD
	end

MiragePalace_EventScript_ItemRelicVase::
	finditem ITEM_RELIC_VASE
	end

MiragePalace_EventScript_ItemRelicStatue::
	finditem ITEM_RELIC_STATUE
	end

MiragePalace_EventScript_ItemRelicCrown::
	finditem ITEM_RELIC_CROWN
	end



SteelMill_EventScript_ItemTM91::
	finditem ITEM_TM91
	end

SteelMill_EventScript_ItemElectirizer::
	finditem ITEM_ELECTIRIZER
	end

SteelMill_EventScript_ItemMagmarizer::
	finditem ITEM_MAGMARIZER
	end

SteelMill_EventScript_ItemHeavyBall::
	finditem ITEM_HEAVY_BALL
	end

SteelMill_EventScript_ItemIron::
	finditem ITEM_IRON
	end

SteelMill_EventScript_ItemXDefense::
	finditem ITEM_X_DEFENSE
	end

SteelMill_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

SteelMill_EventScript_ItemMetalCoat::
	finditem ITEM_METAL_COAT
	end

SteelMill_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

SteelMill_EventScript_ItemVCard::
	finditem ITEM_V_CARD
	end



Route68_EventScript_ItemXSpecialDefense::
	finditem ITEM_X_SP_DEF
	end

Route68_EventScript_ItemProtectivePads::
	finditem ITEM_PROTECTIVE_PADS
	end

Route68_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route68_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route68_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route68_EventScript_ItemShinyStone::
	finditem ITEM_SHINY_STONE
	end

Route68_EventScript_ItemMuscleBand::
	finditem ITEM_MUSCLE_BAND
	end

Route68_EventScript_ItemSafetyGoggles::
	finditem ITEM_SAFETY_GOGGLES
	end



Route67_EventScript_ItemZephyrStone::
	finditem ITEM_ZEPHYR_STONE
	end



WisteriaCity_EventScript_ItemZoomLens::
	finditem ITEM_ZOOM_LENS
	end



Route66_EventScript_ItemTM66::
	finditem ITEM_TM66
	end

Route66_EventScript_ItemDuskStone::
	finditem ITEM_DUSK_STONE
	end

Route66_EventScript_ItemDuskBall::
	finditem ITEM_DUSK_BALL
	end

Route66_EventScript_ItemFocusSash::
	finditem ITEM_FOCUS_SASH
	end

Route66_EventScript_ItemReaperCloth::
	finditem ITEM_REAPER_CLOTH
	end



DuskMountain_EventScript_ItemTM65::
	finditem ITEM_TM65
	end

DuskMountain_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

DuskMountain_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

DuskMountain_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

DuskMountain_EventScript_ItemDuskBall::
	finditem ITEM_DUSK_BALL
	end

DuskMountain_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

DuskMountain_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

DuskMountain_EventScript_ItemBigNugget::
	finditem ITEM_BIG_NUGGET
	end

DuskMountain_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

DuskMountain_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

DuskMountain_EventScript_ItemTM92::
	finditem ITEM_TM92
	end

DuskMountain_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end



PokemonLaboratory_EventScript_ItemDreamBall1::
	finditem ITEM_DREAM_BALL, 6
	end

PokemonLaboratory_EventScript_ItemDreamBall2::
	finditem ITEM_DREAM_BALL, 6
	end

PokemonLaboratory_EventScript_ItemDreamBall3::
	finditem ITEM_DREAM_BALL, 6
	end

PokemonLaboratory_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

PokemonLaboratory_EventScript_ItemGuardSpec::
	finditem ITEM_GUARD_SPEC
	end

PokemonLaboratory_EventScript_ItemTM06::
	finditem ITEM_TM06
	end



Route99_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end



IsshoVictoryRoad_EventScript_ItemWiseGlasses::
	finditem ITEM_WISE_GLASSES
	end

IsshoVictoryRoad_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

IsshoVictoryRoad_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

IsshoVictoryRoad_EventScript_ItemChoiceBand::
	finditem ITEM_CHOICE_BAND
	end

IsshoVictoryRoad_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

IsshoVictoryRoad_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

IsshoVictoryRoad_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

IsshoVictoryRoad_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

IsshoVictoryRoad_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

IsshoVictoryRoad_EventScript_ItemDawnStone::
	finditem ITEM_DAWN_STONE
	end

IsshoVictoryRoad_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

IsshoVictoryRoad_EventScript_ItemTM93::
	finditem ITEM_TM93
	end

IsshoVictoryRoad_EventScript_ItemTM52::
	finditem ITEM_TM52
	end

IsshoVictoryRoad_EventScript_ItemDreamBall::
	finditem ITEM_DREAM_BALL
	end

IsshoVictoryRoad_EventScript_ItemQuickBall::
	finditem ITEM_QUICK_BALL
	end

IsshoVictoryRoad_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

IsshoVictoryRoad_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end



UndergroundCity_EventScript_ItemTM41::
	finditem ITEM_TM41
	end

UndergroundCity_EventScript_ItemTM64::
	finditem ITEM_TM64
	end

UndergroundCity_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

UndergroundCity_EventScript_ItemTwistedSpoon::
	finditem ITEM_TWISTED_SPOON
	end

UndergroundCity_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

UndergroundCity_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

UndergroundCity_EventScript_ItemDawnStone::
	finditem ITEM_DAWN_STONE
	end

UndergroundCity_EventScript_ItemDreamBall::
	finditem ITEM_DREAM_BALL, 6
	end

UndergroundCity_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

UndergroundCity_EventScript_ItemToxicOrb::
	finditem ITEM_TOXIC_ORB
	end

UndergroundCity_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

UndergroundCity_EventScript_ItemDubiousDisc::
	finditem ITEM_DUBIOUS_DISC
	end





