EventScript_NeedCardKeyS::
	msgbox Text_ItNeedsCardKeyS, MSGBOX_DEFAULT
	releaseall
	end

EventScript_NeedCardKeyA::
	msgbox Text_ItNeedsCardKeyA, MSGBOX_DEFAULT
	releaseall
	end

EventScript_NeedCardKeyB::
	msgbox Text_ItNeedsCardKeyB, MSGBOX_DEFAULT
	releaseall
	end

EventScript_DoorUnlocked::
	msgbox Text_TheDoorIsOpen, MSGBOX_DEFAULT
	releaseall
	end






EventScript_Open2FDoorB1::
	setmetatile 8, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 9, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 10, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 8, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 9, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 10, 15, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open2FDoorB2::
	setmetatile 22, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 23, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 24, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 22, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 23, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 24, 6, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open3FDoorB1::
	setmetatile 2, 8, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 3, 8, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 2, 9, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 3, 9, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open3FDoorB2::
	setmetatile 18, 10, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 19, 10, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 20, 10, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 18, 11, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 19, 11, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 20, 11, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open3FDoorB3::
	setmetatile 34, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 35, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 34, 16, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 35, 16, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open4FDoorB1::
	setmetatile 32, 4, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 33, 4, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 32, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 33, 5, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open6FDoorB1::
	setmetatile 18, 13, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 19, 13, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 20, 13, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 18, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 19, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 20, 14, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open7FDoorB1::
	setmetatile 19, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 20, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 21, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 19, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 20, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 21, 15, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open7FDoorB2::
	setmetatile 34, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 35, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 34, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 35, 15, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open8FDoorB1::
	setmetatile 1, 13, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 2, 13, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 3, 13, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 1, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 2, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 3, 14, METATILE_KendomaCorp_WhiteFloor, 0
	return











EventScript_Open4FDoorA1::
	setmetatile 22, 4, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 23, 4, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 22, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 23, 5, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open5FDoorA1::
	setmetatile 2, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 3, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 4, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 2, 7, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 3, 7, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 4, 7, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open6FDoorA1::
	setmetatile 30, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 31, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 30, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 31, 6, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open7FDoorA1::
	setmetatile 2, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 3, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 4, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 2, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 3, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 4, 6, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open7FDoorA2::
	setmetatile 29, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 30, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 29, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 30, 15, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open8FDoorA1::
	setmetatile 18, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 19, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 18, 16, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 19, 16, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open9FDoorA1::
	setmetatile 20, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 21, 5, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 20, 6, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 21, 6, METATILE_KendomaCorp_WhiteFloor, 0
	return

EventScript_Open9FDoorA2::
	setmetatile 17, 13, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 18, 13, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 17, 14, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 18, 14, METATILE_KendomaCorp_WhiteFloor, 0
	return






EventScript_Open10FDoorS::
	setmetatile 32, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 33, 15, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 32, 16, METATILE_KendomaCorp_WhiteFloor, 0
	setmetatile 33, 16, METATILE_KendomaCorp_WhiteFloor, 0
	return












KendomaCorp_2F_EventScript_DoorB1::
	lockall
	setvar VAR_TEMP_1, 1
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorB
	end

KendomaCorp_2F_EventScript_DoorB2::
	lockall
	setvar VAR_TEMP_1, 2
	goto_if_set FLAG_TEMP_11, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_11
	goto EventScript_UnlockDoorB
	end

KendomaCorp_3F_EventScript_DoorB1::
	lockall
	setvar VAR_TEMP_1, 3
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorB
	end

KendomaCorp_3F_EventScript_DoorB2::
	lockall
	setvar VAR_TEMP_1, 4
	goto_if_set FLAG_TEMP_11, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_11
	goto EventScript_UnlockDoorB
	end

KendomaCorp_3F_EventScript_DoorB3::
	lockall
	setvar VAR_TEMP_1, 5
	goto_if_set FLAG_TEMP_12, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_12
	goto EventScript_UnlockDoorB
	end

KendomaCorp_4F_EventScript_DoorB1::
	lockall
	setvar VAR_TEMP_1, 6
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorB
	end

KendomaCorp_6F_EventScript_DoorB1::
	lockall
	setvar VAR_TEMP_1, 7
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorB
	end

KendomaCorp_7F_EventScript_DoorB1::
	lockall
	setvar VAR_TEMP_1, 8
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorB
	end

KendomaCorp_7F_EventScript_DoorB2::
	lockall
	setvar VAR_TEMP_1, 9
	goto_if_set FLAG_TEMP_11, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_11
	goto EventScript_UnlockDoorB
	end

KendomaCorp_8F_EventScript_DoorB1::
	lockall
	setvar VAR_TEMP_1, 10
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_B_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyB
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorB
	end











KendomaCorp_4F_EventScript_DoorA1::
	lockall
	setvar VAR_TEMP_1, 1
	goto_if_set FLAG_TEMP_11, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_A_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyA
	setflag FLAG_TEMP_11
	goto EventScript_UnlockDoorA
	end

KendomaCorp_5F_EventScript_DoorA1::
	lockall
	setvar VAR_TEMP_1, 2
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_A_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyA
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorA
	end

KendomaCorp_6F_EventScript_DoorA1::
	lockall
	setvar VAR_TEMP_1, 3
	goto_if_set FLAG_TEMP_11, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_A_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyA
	setflag FLAG_TEMP_11
	goto EventScript_UnlockDoorA
	end

KendomaCorp_7F_EventScript_DoorA1::
	lockall
	setvar VAR_TEMP_1, 4
	goto_if_set FLAG_TEMP_12, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_A_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyA
	setflag FLAG_TEMP_12
	goto EventScript_UnlockDoorA
	end

KendomaCorp_7F_EventScript_DoorA2::
	lockall
	setvar VAR_TEMP_1, 5
	goto_if_set FLAG_TEMP_13, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_A_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyA
	setflag FLAG_TEMP_13
	goto EventScript_UnlockDoorA
	end

KendomaCorp_8F_EventScript_DoorA1::
	lockall
	setvar VAR_TEMP_1, 6
	goto_if_set FLAG_TEMP_11, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_A_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyA
	setflag FLAG_TEMP_11
	goto EventScript_UnlockDoorA
	end

KendomaCorp_9F_EventScript_DoorA1::
	lockall
	setvar VAR_TEMP_1, 7
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_A_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyA
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorA
	end

KendomaCorp_9F_EventScript_DoorA2::
	lockall
	setvar VAR_TEMP_1, 8
	goto_if_set FLAG_TEMP_11, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_A_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyA
	setflag FLAG_TEMP_11
	goto EventScript_UnlockDoorA
	end






KendomaCorp_10F_EventScript_DoorS::
	lockall
	@setvar VAR_TEMP_1, 20
	@setvar VAR_0x8004, FLAG_SILPH_11F_DOOR
	goto_if_set FLAG_TEMP_10, EventScript_DoorUnlocked
	checkitem ITEM_CLEARANCE_S_CARD
	goto_if_eq VAR_RESULT, FALSE, EventScript_NeedCardKeyS
	setflag FLAG_TEMP_10
	goto EventScript_UnlockDoorS
	end

@EventScript_TryUnlockDoorS::
@	goto_if_set FLAG_ITEM_KENDOMA_CORP_S_CARD, EventScript_OpenDoorS
@	goto EventScript_NeedCardKeyS
@	end

@EventScript_TryUnlockDoorA::
@	goto_if_set FLAG_ITEM_KENDOMA_CORP_A_CARD, EventScript_OpenDoorA
@	goto EventScript_NeedCardKeyA
@	end

@EventScript_TryUnlockDoorB::
@	goto_if_set FLAG_ITEM_KENDOMA_CORP_B_CARD, EventScript_OpenDoorB
@	goto EventScript_NeedCardKeyB
@	end

EventScript_UnlockDoorS::
	playfanfare MUS_LEVEL_UP
	msgbox Text_CardKeyOpenedDoor, MSGBOX_DEFAULT
	waitfanfare
	call EventScript_Open10FDoorS
	waitse
	playse SE_UNLOCK
	special DrawWholeMapView
	waitse
	@special SetHiddenItemFlag
	releaseall
	end

EventScript_UnlockDoorA::
	playfanfare MUS_LEVEL_UP
	msgbox Text_CardKeyOpenedDoor, MSGBOX_DEFAULT
	waitfanfare
	call_if_eq VAR_TEMP_1, 1, EventScript_Open4FDoorA1
	call_if_eq VAR_TEMP_1, 2, EventScript_Open5FDoorA1
	call_if_eq VAR_TEMP_1, 3, EventScript_Open6FDoorA1
	call_if_eq VAR_TEMP_1, 4, EventScript_Open7FDoorA1
	call_if_eq VAR_TEMP_1, 5, EventScript_Open7FDoorA2
	call_if_eq VAR_TEMP_1, 6, EventScript_Open8FDoorA1
	call_if_eq VAR_TEMP_1, 7, EventScript_Open9FDoorA1
	call_if_eq VAR_TEMP_1, 8, EventScript_Open9FDoorA2
	waitse
	playse SE_UNLOCK
	special DrawWholeMapView
	waitse
	@special SetHiddenItemFlag
	releaseall
	end

EventScript_UnlockDoorB::
	playfanfare MUS_LEVEL_UP
	msgbox Text_CardKeyOpenedDoor, MSGBOX_DEFAULT
	waitfanfare
	call_if_eq VAR_TEMP_1, 1, EventScript_Open2FDoorB1
	call_if_eq VAR_TEMP_1, 2, EventScript_Open2FDoorB2
	call_if_eq VAR_TEMP_1, 3, EventScript_Open3FDoorB1
	call_if_eq VAR_TEMP_1, 4, EventScript_Open3FDoorB2
	call_if_eq VAR_TEMP_1, 5, EventScript_Open3FDoorB3
	call_if_eq VAR_TEMP_1, 6, EventScript_Open4FDoorB1
	call_if_eq VAR_TEMP_1, 7, EventScript_Open6FDoorB1
	call_if_eq VAR_TEMP_1, 8, EventScript_Open7FDoorB1
	call_if_eq VAR_TEMP_1, 9, EventScript_Open7FDoorB2
	call_if_eq VAR_TEMP_1, 10, EventScript_Open8FDoorB1
	waitse
	playse SE_UNLOCK
	special DrawWholeMapView
	waitse
	@special SetHiddenItemFlag
	releaseall
	end

Text_CardKeyOpenedDoor:
	.string "The card key opened the door.$"

Text_ItNeedsCardKeyS:
	.string "Key card required.\n"
	.string "Clearance level S.$"

Text_ItNeedsCardKeyA:
	.string "Key card required.\n"
	.string "Clearance level A.$"

Text_ItNeedsCardKeyB:
	.string "Key card required.\n"
	.string "Clearance level B.$"

Text_TheDoorIsOpen:
	.string "The door is open.$"



