UndergroundCity_Building3_4F_MapScripts::
	.byte 0

UndergroundCity_Building3_4F_EventScript_Scientist::
	msgbox UndergroundCity_Building3_4F_Text_VastUltraSpace, MSGBOX_NPC
	end

UndergroundCity_Building3_4F_Text_VastUltraSpace:
	.string "Some believe that Ultra Space is so vast\n"
	.string "that all possibilities become likely.\p"
	.string "The sheer number of worlds mean that all\n"
	.string "scenarios have likely been exhausted.\p"
	.string "Imagine a world just like ours except\n"
	.string "you're a millionaire or a celebrity!\p"
	.string "Who knows what possibilities lie in\n"
	.string "the deep dark world of Ultra Space!$"

