.set LOCALID_BETTERMAN, 1

PitchblakCity_KendomaCorp_SecretBasement_MapScripts::
	.byte 0


PitchblakCity_KendomaCorp_EventScript_Log1::
	msgbox PitchblakCity_KendomaCorp_Text_Log1, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log2::
	msgbox PitchblakCity_KendomaCorp_Text_Log2, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log3::
	msgbox PitchblakCity_KendomaCorp_Text_Log3, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log4::
	msgbox PitchblakCity_KendomaCorp_Text_Log4, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log5::
	msgbox PitchblakCity_KendomaCorp_Text_Log5, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log6::
	msgbox PitchblakCity_KendomaCorp_Text_Log6, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log7::
	msgbox PitchblakCity_KendomaCorp_Text_Log7, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log8::
	msgbox PitchblakCity_KendomaCorp_Text_Log8, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log9::
	msgbox PitchblakCity_KendomaCorp_Text_Log9, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log10::
	msgbox PitchblakCity_KendomaCorp_Text_Log10, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_EventScript_Log11::
	msgbox PitchblakCity_KendomaCorp_Text_Log11, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_Text_Log1:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 1\p" 
	.string "Initial approval for tests to begin.\p"
	.string "DNA sample for RS-000 submitted and\n"
	.string "undergoing initial sequencing.\p"
	.string "Request for additional funding\n"
	.string "for new equipment.$"

PitchblakCity_KendomaCorp_Text_Log2:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 43\p"
	.string "DNA insertion successful.\n"
	.string "Several viable embryos were obtained.\p"
	.string "Accelerated growth treatments\n"
	.string "to begin ASAP.$"

PitchblakCity_KendomaCorp_Text_Log3:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 79\p"
	.string "Fetal development of RS-001 is complete.\n"
	.string "All vitals are normal.\p"
	.string "Subject has been transfered from\n"
	.string "in vitro unit.\p"
	.string "Fetal development of RS-002 and\n"
	.string "RS-003 is underway.$"

PitchblakCity_KendomaCorp_Text_Log4:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 265\p"
	.string "Subjects continue to develop normally.\p"
	.string "Subjects appear identical to RS-000\n"
	.string "except for a characteristic albinism.\p"
	.string "As in previous series, red sclera are\n"
	.string "a constant but harmless side effect.$"

PitchblakCity_KendomaCorp_Text_Log5:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 415\p"
	.string "Subjects consistently outperform their\n"
	.string "nonclone peers in all metrics.\p"
	.string "However, they exhibit indifference\n"
	.string "toward both people and POKéMON.\p"
	.string "Behavioral therapy is scheduled to\n"
	.string "condition them to fieldwork.$"

PitchblakCity_KendomaCorp_Text_Log6:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 469\p"
	.string "RS-001 placed in indefinite cryosleep\n"
	.string "after being deemed a failure.\p"
	.string "Other subjects respond well to behavior\n"
	.string "therapy as field trials are underway.\p"
	.string "Recommend supplementary use of\n"
	.string "antipsychotic medication.$"

PitchblakCity_KendomaCorp_Text_Log7:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 547\p"
	.string "RS-004 exhibits strong paranoid traits.\n"
	.string "Therapy and medication are ineffective.\p"
	.string "To be placed in indefinite cryosleep\n"
	.string "awaiting executive approval.$"


PitchblakCity_KendomaCorp_Text_Log8:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 601\p"
	.string "A pattern of unscrupulous behaviors\n"
	.string "observed in RS-006 and RS-007.\p"
	.string "Defiance and aggression directed\n"
	.string "at other subjects and staff members.\p"
	.string "To be placed in indefinite cryosleep\n"
	.string "awaiting executive approval.$"

PitchblakCity_KendomaCorp_Text_Log9:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 613\p"
	.string "Cryo-units damaged after a possible\n"
	.string "breakin. Investigation still underway.\p"
	.string "RS-006 reported missing.\n"
	.string "Current whereabouts unknown.\p"
	.string "RS-005 and RS-007 found to be damaged\n"
	.string "beyond viability and terminated.$"

PitchblakCity_KendomaCorp_Text_Log10:
	.string "PROGRESS REPORT FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\l"
	.string "WEEK 667\p"
	.string "RS-008 and RS-009 show no improvements\n"
	.string "over previous subjects.\p"
	.string "Medication and therapy are ineffective\n"
	.string "at treating apathetic tendencies.\p"
	.string "To be placed in indefinite cryosleep\n"
	.string "awaiting executive approval.$"

PitchblakCity_KendomaCorp_Text_Log11:
	.string "BOARD REVIEW FOR CLONE SERIES {NO}496\n" 
	.string "PROJECT NAME: RAYNER SERIES\p"
	.string "After thorough review of materials,\n"
	.string "we have decided to close the project.\p"
	.string "All ongoing trials are\n"
	.string "to be aborted.\p"
	.string "All subjects are to be terminated.$"







PitchblakCity_KendomaCorp_EventScript_DrBetterman::
	lock
	faceplayer
	goto_if_eq VAR_BETTERMAN_STATE, 1, PitchblakCity_KendomaCorp_EventScript_DrBettermanPostMasterBall
	applymovement LOCALID_BETTERMAN, Common_Movement_ExclamationMark
	playse SE_PIN
	waitmovement 0
	@fadeoutbgm 0
	delay 60
	msgbox PitchblakCity_KendomaCorp_Text_IKnowYou, MSGBOX_DEFAULT
	closemessage
	delay 30
	applymovement LOCALID_BETTERMAN, Common_Movement_FaceUp
	waitmovement 0
	delay 120
	faceplayer
	delay 30
	msgbox PitchblakCity_KendomaCorp_Text_Specimens, MSGBOX_DEFAULT
	closemessage
	delay 120
	msgbox PitchblakCity_KendomaCorp_Text_WorkAtKendomaCorp, MSGBOX_DEFAULT
	closemessage
	delay 30
	applymovement LOCALID_BETTERMAN, Common_Movement_FaceUp
	waitmovement 0
	delay 120
	faceplayer
	delay 30
	msgbox PitchblakCity_KendomaCorp_Text_Tools, MSGBOX_DEFAULT
	closemessage
	delay 30
	applymovement LOCALID_BETTERMAN, Common_Movement_FaceUp
	waitmovement 0
	delay 120
	msgbox PitchblakCity_KendomaCorp_Text_WereFinished, MSGBOX_DEFAULT
	closemessage
	delay 120
	faceplayer
	delay 30
	msgbox PitchblakCity_KendomaCorp_Text_TeamGenesisUpstairs, MSGBOX_DEFAULT
	closemessage
	msgbox PitchblakCity_KendomaCorp_Text_HandOverCard, MSGBOX_DEFAULT
	removeitem ITEM_CLEARANCE_S_CARD
	delay 60
	msgbox PitchblakCity_KendomaCorp_Text_ThankYou, MSGBOX_DEFAULT
	giveitem ITEM_MASTER_BALL
	waitfanfare
	msgbox PitchblakCity_KendomaCorp_Text_ExplainMasterBall, MSGBOX_DEFAULT
	closemessage
	delay 30
	applymovement LOCALID_BETTERMAN, Common_Movement_FaceUp
	waitmovement 0
	delay 60
	faceplayer
	delay 30
	msgbox PitchblakCity_KendomaCorp_Text_ExplainExit, MSGBOX_DEFAULT
	closemessage
	setvar VAR_BETTERMAN_STATE, 1
	@fadeinbgm 0
	release
	end

PitchblakCity_KendomaCorp_Text_IKnowYou:
	.string "BETTERMAN: You, you're that trainer\n"
	.string "from ROUTE 90.\p"
	.string "To think that I would run into you\n"
	.string "of all people down here.\p"
	.string "When I heard the elevator, I thought\n"
	.string "for sure it was TEAM GENESIS.\p"
	.string "But if you found the other KEY CARD,\n"
	.string "then that means...\p"
	.string "I've been forturnate yet again!\p"
	.string "I was afraid I would be discovered\n"
	.string "down here.\p"
	.string "The thawing process takes a\n"
	.string "long time, you see...$"

PitchblakCity_KendomaCorp_Text_Specimens:
	.string "The specimens in these cryotanks\n"
	.string "are important to me.\p"
	.string "One could say that they're my sons\n"
	.string "in a way.\p"
	.string "Although I know now they can never\n"
	.string "be like my real son.\p"
	.string "My RYLAND...$"

PitchblakCity_KendomaCorp_Text_WorkAtKendomaCorp:
	.string "I've worked here at KENDOM CORP\n"
	.string "for a long time now.\p"
	.string "We've seen some amazing breakthoughs\n"
	.string "and applications of genetic science.\p"
	.string "Things that no one ever dreamed\n"
	.string "was possible before!\p"
	.string "I suppose in my hubris, I thought I could\n"
	.string "recreate life from the ground up.\p"
	.string "Human beings are just chemical\n"
	.string "processes too, right?\p"
	.string "But no matter what I tried to control for,\n"
	.string "the result each time was somehow\l"
	.string "different than what I intended.\p"
	.string "And it wasn't long before this project\n"
	.string "got out of my control altogether.\p"
	.string "I should've foreseen that too...$"

PitchblakCity_KendomaCorp_Text_Tools:
	.string "The board only ever saw them\n"
	.string "as experiments.\p"
	.string "Just like our other projects.\p"
	.string "They wanted me to breed soldiers\n"
	.string "for them.\p"
	.string "Or corporate servants, as they liked\n"
	.string "to call them.\p"
	.string "\p"
	.string "In the end, no one got what they wanted.\p"
	.string "The project was deemed a failure.\n"
	.string "They wanted me to shut everything down.\l"
	.string "And I had no choice but to comply.\p"
	.string "Until TEAM GENESIS arrived that is...$"

PitchblakCity_KendomaCorp_Text_WereFinished:
	.string "KENDOM CORP is finished,\n"
	.string "one way or another.\p"
	.string "As is my career here and the dream I\n"
	.string "spent half a lifetime working toward.\p"
	.string "And yet this whole ordeal has been\n"
	.string "strangely fortunate for me.\p"
	.string "I never got back the family I lost.\p"
	.string "But now it seems I have a chance to\n"
	.string "start over with a new one.\p"
	.string "It's funny how things work out sometimes.$"

PitchblakCity_KendomaCorp_Text_TeamGenesisUpstairs:
	.string "I know TEAM GENESIS is upstairs\n"
	.string "looking for this place.\p"
	.string "They'll undoubtedly find it too.\p"
	.string "But you've bought me a great deal of time\n"
	.string "bringing the second key card down here.\p"
	.string "Please, if you would hand it over.$"

PitchblakCity_KendomaCorp_Text_HandOverCard:
	.string "{PLAYER} gave the doctor the\n"
	.string "CLEARANCE S CARD.$"

PitchblakCity_KendomaCorp_Text_ThankYou:
	.string "Thank you very much.\p"
	.string "This is the second time\n"
	.string "you've helped me.\p"
	.string "I don't know why you came here or what\n"
	.string "business you have with KENDOM CORP.\p"
	.string "But I'd like you to have this as a\n"
	.string "token of my thanks.\p"
	.string "Somehow it seems right to give it to you.$"

PitchblakCity_KendomaCorp_Text_ExplainMasterBall:
	.string "That is a rare POKé BALL that will\n"
	.string "catch any POKéMON without fail.\p"
	.string "It's highly coveted by thugs like\n"
	.string "TEAM GENESIS for obvious reasons.\p"
	.string "But you seem like a good soul.\p"
	.string "I trust you'll know the right\n"
	.string "time to use it.$"

PitchblakCity_KendomaCorp_Text_ExplainExit:
	.string "I won't be leaving this place for a while.\p"
	.string "But I can send you out through one of\n"
	.string "the emergency exits we designed.\p"
	.string "It's how I planned to leave myself.\p"
	.string "You see that X on the second floor?\p"
	.string "Step on it when you're ready\n"
	.string "and I'll see you off.$"

PitchblakCity_KendomaCorp_EventScript_DrBettermanPostMasterBall::
	msgbox PitchblakCity_KendomaCorp_Text_LeaveWhenReady, MSGBOX_DEFAULT
	closemessage
	end

PitchblakCity_KendomaCorp_Text_LeaveWhenReady:
	.string "Step onto the X upstairs when\n"
	.string "you're ready. I'll see you off.$"




PitchblakCity_KendomaCorp_EventScript_EscapeTunnel::
	lockall
	msgbox PitchblakCity_KendomaCorp_Text_ReadyToLeave, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, PitchblakCity_KendomaCorp_EventScript_SkipExit
	@fadeoutbgm 0
	@playse SE_TRUCK_MOVE
	@delay 60
	@@special ShakeCamera
	@@waitstate
	applymovement OBJ_EVENT_ID_PLAYER, KendomaCorp_Movement_PlayerSpin
	waitmovement 0
	delay 10
	warpteleport MAP_ROUTE72, 36, 18
	@warpteleport MAP_UMBER_TOWN, 21, 20
	waitstate
	releaseall
	end

PitchblakCity_KendomaCorp_EventScript_SkipExit::
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkUp
	waitmovement 0
	releaseall
	end

PitchblakCity_KendomaCorp_Text_ReadyToLeave:
	.string "Ready to leave?$"

KendomaCorp_Movement_PlayerSpin:
	face_right
	delay_16
	delay_16
	face_up
	delay_16
	delay_16
	face_left
	delay_16
	delay_16
	face_down
	delay_16
	delay_16

	face_right
	delay_8
	delay_16
	face_up
	delay_8
	delay_16
	face_left
	delay_8
	delay_16
	face_down
	delay_8
	delay_16

	face_right
	delay_16
	face_up
	delay_16
	face_left
	delay_16
	face_down
	delay_16

	face_right
	delay_4
	delay_8
	face_up
	delay_4
	delay_8
	face_left
	delay_4
	delay_8
	face_down
	delay_4
	delay_8

	face_right
	delay_8
	face_up
	delay_8
	face_left
	delay_8
	face_down
	delay_8

	face_right
	delay_4
	delay_2
	face_up
	delay_4
	delay_2
	face_left
	delay_4
	delay_2
	face_down
	delay_4
	delay_2

	face_right
	delay_4
	face_up
	delay_4
	face_left
	delay_4
	face_down
	delay_4

	face_right
	delay_4
	face_up
	delay_4
	face_left
	delay_4
	face_down
	delay_4

	face_right
	delay_2
	face_up
	delay_2
	face_left
	delay_2
	face_down
	delay_2

	face_right
	delay_2
	face_up
	delay_2
	face_left
	delay_2
	face_down
	delay_2

	face_right
	delay_2
	face_up
	delay_2
	face_left
	delay_2
	face_down
	delay_2

	face_right
	delay_2
	face_up
	delay_2
	face_left
	delay_2
	face_down

	step_end


