XanthosCity_Flat1_2F_MapScripts::
	.byte 0

XanthosCity_Flat1_2F_EventScript_Man::
	msgbox XanthosCity_Flat1_2F_Text_CrazyOldBeliefs, MSGBOX_NPC
	end

XanthosCity_Flat1_2F_EventScript_Woman::
	@msgbox XanthosCity_Flat1_2F_Text_GroudonKyogreBattle, MSGBOX_NPC
	msgbox XanthosCity_Flat1_2F_Text_PokemonGods, MSGBOX_NPC
	end

XanthosCity_Flat1_2F_Text_CrazyOldBeliefs:
	.string "There are a bunch of old legends\n"
	.string "about POKéMON creating the world.\p"
	.string "Some are supposed to have created\n"
	.string "the HOENN region.\p"
	.string "Others are said to have created the\n"
	.string "entire universe!\p"
	.string "Isn't it crazy what people used to\n"
	.string "believe?$"

XanthosCity_Flat1_2F_Text_GroudonKyogreBattle:
	.string "A strange weather phenomenon affected\n"
	.string "the seas around here a few years ago.\p"
	.string "Some say it was caused by GROUDON and\n"
	.string "KYOGRE fighting each other.\p"
	.string "Until a young POKéMON trainer put a\n"
	.string "stop to their battle.\p"
	.string "Personally, I think that's ridiculous.\p"
	.string "How could POKéMON that strong be\n"
	.string "stopped by a mere child?$"

XanthosCity_Flat1_2F_Text_PokemonGods:
	.string "People in the past used to think\n"
	.string "of certain POKéMON as gods.\p"
	.string "But here in ISSHO, we've largely\n"
	.string "outgrown such silly superstitions.\p"
	.string "A POKéMON is still just a POKéMON,\n"
	.string "after all.$"

