XanthosCity_Flat2_1F_MapScripts::
	.byte 0

XanthosCity_Flat2_1F_EventScript_FatMan::
	msgbox XanthosCity_Flat2_1F_Text_SurgeInSwarms, MSGBOX_NPC
	end

XanthosCity_Flat2_1F_EventScript_OldWoman::
	msgbox XanthosCity_Flat2_1F_Text_Landlording, MSGBOX_NPC
	end

XanthosCity_Flat2_1F_Text_Landlording:
	.string "Landlording isn't easy, you know.\p"
	.string "Fire codes, electrical codes\n"
	.string "chemicals in paint…\p"
	.string "And I've had tenants who trash their\n"
	.string "place and leave me with the bill!$"

XanthosCity_Flat2_1F_Text_SurgeInSwarms:
	.string "There's been a surge in POKéMON\n"
	.string "swarms lately.\p"
	.string "Some of the POKéMON even come from\n"
	.string "faraway regions like UNOVA.$"
