PitchblakCity_KendomaCorp_7F_MapScripts::
	.byte 0

PitchblakCity_KendomaCorp_7F_EventScript_Scientist::
	msgbox PitchblakCity_KendomaCorp_7F_Text_KynnadArchives, MSGBOX_NPC
	end

PitchblakCity_KendomaCorp_7F_Text_KynnadArchives:
	.string "The Kynnad Archives.\p"
	.string "It contains a genetic record for almost\n"
	.string "every known species of POKéMON.\p"
	.string "We thought we'd be using it to\n"
	.string "cure diseases.\p"
	.string "It was never supposed to be weaponized.$"


