OffwiteTown_House1_MapScripts::
	.byte 0

OffwiteTown_House1_EventScript_Boy::
	msgbox OffwiteTown_House1_Text_Isolated, MSGBOX_NPC
	end

OffwiteTown_House1_Text_Isolated:
	.string "Here in OFFWITE TOWN, we're\n"
	.string "pretty isolated.\p"
	.string "We didn't even have a POKéMON\n"
	.string "CENTER until a few years ago.\p"
	.string "Can you believe that?$"

OffwiteTown_House1_EventScript_Man::
	msgbox OffwiteTown_House1_Text_Cable, MSGBOX_NPC
	end

OffwiteTown_House1_Text_Cable:
	.string "You wouldn't believe how hard it was\n"
	.string "to get television out here.$"

