XanthosCity_Flat2_2F_MapScripts::
	.byte 0

XanthosCity_Flat2_2F_EventScript_Man::
	msgbox XanthosCity_Flat2_2F_Text_KendomaCorp, MSGBOX_NPC
	end

XanthosCity_Flat2_2F_Text_KendomaCorp:
	.string "Hi! I'm an engineer.\p"
	.string "I helped design the dam\n"
	.string "on ROUTE 83.\p"
	.string "It converts mechanical energy from\n"
	.string "the water into electricity.\p"
	.string "And that electricity is used to\n"
	.string "power the whole city!\p"
	.string "That's the awesome power of scientific\n"
	.string "thinking! Wouldn't you agree?$"

XanthosCity_Flat2_2F_EventScript_Girl::
	msgbox XanthosCity_Flat2_2F_Text_ManyPeople, MSGBOX_NPC
	end

XanthosCity_Flat2_2F_Text_ManyPeople:
	.string "Have you ever thought about how many\n"
	.string "people live here in XANTHOS CITY?\p"
	.string "I don't even know most of the\n"
	.string "people in this building.\p"
	.string "We're so close and yet\n"
	.string "so far away.$"
